"""
Sales (DIBBS Bidding) app URL configuration.
"""
from django.urls import path
from .views import (
    dashboard,
    import_upload,
    import_fetch_dibbs,
    import_history,
    import_batch_delete,
    import_job_progress,
    import_step_parse,
    import_step_solicitations,
    import_step_lines,
    import_step_match,
    import_step_awards,
    solicitation_list,
    solicitation_detail,
    no_bid,
    global_search,
    backfill_nsn,
    rfq_pending,
    rfq_sent,
    rfq_send_single,
    rfq_send_batch,
    rfq_mailto,
    rfq_mark_sent,
    rfq_center,
    rfq_center_detail,
    rfq_enter_quote,
    rfq_send_followup,
    rfq_mark_no_response,
    rfq_mark_declined,
    quote_select_for_bid,
    rfq_cage_preview,
    rfq_send_to_approved_source,
    rfq_send_to_adhoc,
    rfq_supplier_search,
    rfq_send_to_existing,
    rfq_inbox_refresh,
    rfq_inbox_list,
    rfq_inbox_detail,
    rfq_inbox_assign,
    rfq_queue_view,
    rfq_queue_add,
    supplier_create_and_queue,
    rfq_queue_fetch_pdfs,
    rfq_queue_send,
    bids_ready,
    bid_builder,
    bid_select_quote,
    bids_export_queue,
    bids_export_download,
    bids_history,
    supplier_list,
    supplier_detail,
    supplier_add_nsn,
    supplier_add_fsc,
    supplier_remove_nsn,
    supplier_remove_fsc,
    supplier_no_quote_add,
    settings_index,
    settings_cages,
    settings_cage_add,
    settings_cage_edit,
    email_template_list,
    email_template_edit,
    email_template_delete,
    email_template_set_default,
    email_template_preview,
    settings_greetings,
    settings_greeting_add,
    settings_greeting_delete,
    settings_greeting_toggle,
    settings_salutations,
    settings_salutation_add,
    settings_salutation_delete,
    settings_salutation_toggle,
    no_quote_list,
    no_quote_deactivate,
    sync_awards_view,
    entity_lookup,
    entity_no_quote_add,
)

app_name = "sales"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("import/", import_upload, name="import_upload"),
    path("import/fetch-dibbs/", import_fetch_dibbs, name="import_fetch_dibbs"),
    path("import/history/", import_history, name="import_history"),
    path("import/batch/<int:batch_id>/delete/", import_batch_delete, name="import_batch_delete"),
    path("import/job/<str:job_id>/", import_job_progress, name="import_job_progress"),
    path("import/job/<str:job_id>/step/parse/", import_step_parse, name="import_step_parse"),
    path("import/job/<str:job_id>/step/solicitations/", import_step_solicitations, name="import_step_solicitations"),
    path("import/job/<str:job_id>/step/lines/", import_step_lines, name="import_step_lines"),
    path("import/job/<str:job_id>/step/match/", import_step_match, name="import_step_match"),
    path("import/job/<str:job_id>/step/awards/", import_step_awards, name="import_step_awards"),
    path("solicitations/", solicitation_list, name="solicitation_list"),
    path("solicitations/<str:sol_number>/", solicitation_detail, name="solicitation_detail"),
    path("solicitations/<str:sol_number>/nobid/", no_bid, name="no_bid"),
    path("dashboard/", dashboard, name="dashboard"),
    path("search/", global_search, name="global_search"),
    path("suppliers/backfill-nsn/", backfill_nsn, name="backfill_nsn"),
    # RFQ Center
    path("rfq/", rfq_pending, name="rfq_pending"),
    path("rfq/pending/", rfq_pending, name="rfq_pending"),
    path("rfq/center/", rfq_center, name="rfq_center"),
    path("rfq/center/<int:rfq_id>/detail/", rfq_center_detail, name="rfq_center_detail"),
    path("rfq/sent/", rfq_sent, name="rfq_sent"),
    path("rfq/send/", rfq_send_single, name="rfq_send_single"),
    path("rfq/mailto/<int:match_id>/", rfq_mailto, name="rfq_mailto"),
    path("rfq/<int:match_id>/mark-sent/", rfq_mark_sent, name="rfq_mark_sent"),
    path("rfq/<str:sol_number>/send-batch/", rfq_send_batch, name="rfq_send_batch"),
    path("rfq/<int:rfq_id>/quote/", rfq_enter_quote, name="rfq_enter_quote"),
    path("rfq/<int:rfq_id>/followup/", rfq_send_followup, name="rfq_send_followup"),
    path("rfq/<int:rfq_id>/no-response/", rfq_mark_no_response, name="rfq_mark_no_response"),
    path("rfq/<int:rfq_id>/declined/", rfq_mark_declined, name="rfq_mark_declined"),
    path("quotes/<int:quote_id>/select-for-bid/", quote_select_for_bid, name="quote_select_for_bid"),
    path("rfq/cage-preview/", rfq_cage_preview, name="rfq_cage_preview"),
    path("rfq/send-to-approved-source/", rfq_send_to_approved_source, name="rfq_send_to_approved_source"),
    path("rfq/send-to-adhoc/", rfq_send_to_adhoc, name="rfq_send_to_adhoc"),
    path("rfq/supplier-search/", rfq_supplier_search, name="rfq_supplier_search"),
    path("rfq/send-to-existing/", rfq_send_to_existing, name="rfq_send_to_existing"),
    # RFQ Inbox (IMAP)
    path("rfq/inbox/refresh/", rfq_inbox_refresh, name="rfq_inbox_refresh"),
    path("rfq/inbox/", rfq_inbox_list, name="rfq_inbox_list"),
    path("rfq/inbox/<int:email_id>/", rfq_inbox_detail, name="rfq_inbox_detail"),
    path("rfq/inbox/<int:email_id>/assign/", rfq_inbox_assign, name="rfq_inbox_assign"),
    # RFQ Queue (grouped add / fetch PDFs / send)
    path("rfq/queue/", rfq_queue_view, name="rfq_queue_view"),
    path("rfq/queue/add/", rfq_queue_add, name="rfq_queue_add"),
    path("rfq/supplier-create-and-queue/", supplier_create_and_queue, name="supplier_create_and_queue"),
    path("rfq/queue/fetch-pdfs/", rfq_queue_fetch_pdfs, name="rfq_queue_fetch_pdfs"),
    path("rfq/queue/send/", rfq_queue_send, name="rfq_queue_send"),
    # Bid Center
    path("bids/", bids_ready, name="bids_ready"),
    path("bids/ready/", bids_ready, name="bids_ready"),
    path("bids/<str:sol_number>/build/", bid_builder, name="bid_builder"),
    path("bids/select-quote/", bid_select_quote, name="bid_select_quote"),
    path("bids/export/", bids_export_queue, name="bids_export_queue"),
    path("bids/export/download/", bids_export_download, name="bids_export_download"),
    path("bids/history/", bids_history, name="bids_history"),
    # Suppliers (DIBBS capability management)
    path("suppliers/", supplier_list, name="supplier_list"),
    path("suppliers/<int:supplier_id>/no-quote/add/", supplier_no_quote_add, name="supplier_no_quote_add"),
    path("suppliers/<int:supplier_id>/", supplier_detail, name="supplier_detail"),
    path("suppliers/<int:supplier_id>/nsn/add/", supplier_add_nsn, name="supplier_add_nsn"),
    path("suppliers/<int:supplier_id>/fsc/add/", supplier_add_fsc, name="supplier_add_fsc"),
    path("suppliers/<int:supplier_id>/nsn/remove/", supplier_remove_nsn, name="supplier_remove_nsn"),
    path("suppliers/<int:supplier_id>/fsc/remove/", supplier_remove_fsc, name="supplier_remove_fsc"),
    # Settings
    path("settings/", settings_index, name="settings_index"),
    path("settings/cages/", settings_cages, name="settings_cages"),
    path("settings/cages/add/", settings_cage_add, name="settings_cage_add"),
    path("settings/cages/<int:cage_id>/edit/", settings_cage_edit, name="settings_cage_edit"),
    path("settings/email/", email_template_list, name="email_template_list"),
    path("settings/email/new/", email_template_edit, name="email_template_new"),
    path("settings/email/<int:pk>/edit/", email_template_edit, name="email_template_edit"),
    path("settings/email/<int:pk>/delete/", email_template_delete, name="email_template_delete"),
    path("settings/email/<int:pk>/set-default/", email_template_set_default, name="email_template_set_default"),
    path("settings/email/preview/", email_template_preview, name="email_template_preview"),
    path("settings/greetings/", settings_greetings, name="settings_greetings"),
    path("settings/greetings/add/", settings_greeting_add, name="settings_greeting_add"),
    path("settings/greetings/<int:pk>/delete/", settings_greeting_delete, name="settings_greeting_delete"),
    path("settings/greetings/<int:pk>/toggle/", settings_greeting_toggle, name="settings_greeting_toggle"),
    path("settings/salutations/", settings_salutations, name="settings_salutations"),
    path("settings/salutations/add/", settings_salutation_add, name="settings_salutation_add"),
    path("settings/salutations/<int:pk>/delete/", settings_salutation_delete, name="settings_salutation_delete"),
    path("settings/salutations/<int:pk>/toggle/", settings_salutation_toggle, name="settings_salutation_toggle"),
    path("settings/no-quote/", no_quote_list, name="no_quote_list"),
    path("settings/no-quote/<int:pk>/deactivate/", no_quote_deactivate, name="no_quote_deactivate"),
    # SAM.gov awards sync
    path("awards/sync/", sync_awards_view, name="sync_awards"),
    # SAM.gov entity lookup + No Quote add (POST)
    path("entity/cage/<str:cage_code>/no-quote/add/", entity_no_quote_add, name="entity_no_quote_add"),
    path("entity/cage/<str:cage_code>/", entity_lookup, name="entity_cage_lookup"),
]
