# Generated by Django 4.2.30 on 2026-09-25 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_supplieralias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dibbs', '0003_drop_sales_workflow_columns'),
        ('quote', '0002_seed_app_registry_and_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotebid',
            name='solicitation',
        ),
        migrations.AddField(
            model_name='quotesupplierquote',
            name='source_email',
            field=models.ForeignKey(blank=True, help_text='The supplier reply these numbers were transcribed from, so the quote screen can link straight back to it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_quotes', to='quote.quoteemail'),
        ),
        migrations.CreateModel(
            name='QuoteSupplierNSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, help_text='Normalized 13-digit NSN, no hyphens.', max_length=13)),
                ('notes', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_nsn_capabilities', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier NSN capability',
                'verbose_name_plural': 'Supplier NSN capabilities',
                'db_table': 'quote_supplier_nsn',
                'unique_together': {('supplier', 'nsn')},
            },
        ),
        migrations.CreateModel(
            name='QuoteSupplierFSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsc', models.CharField(db_index=True, max_length=4)),
                ('notes', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_fsc_capabilities', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier FSC capability',
                'verbose_name_plural': 'Supplier FSC capabilities',
                'db_table': 'quote_supplier_fsc',
                'unique_together': {('supplier', 'fsc')},
            },
        ),
        migrations.CreateModel(
            name='QuoteSolicitationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('NSN', 'NSN'), ('FSC', 'FSC'), ('MANUAL', 'Manual')], max_length=10)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('matched_by', models.ForeignKey(blank=True, help_text='Null for engine-created NSN / FSC matches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_matches', to='dibbs.solicitation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_solicitation_matches', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Solicitation supplier match',
                'verbose_name_plural': 'Solicitation supplier matches',
                'db_table': 'quote_solicitation_match',
                'unique_together': {('solicitation', 'supplier', 'source')},
            },
        ),
        migrations.CreateModel(
            name='QuoteSolicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('RFQ_SENT', 'RFQ sent'), ('QUOTING', 'Quoting'), ('BID_READY', 'Bid ready'), ('BID_SUBMITTED', 'Bid submitted'), ('NO_BID', 'No bid'), ('ARCHIVED', 'Archived')], db_index=True, default='UNMATCHED', max_length=20)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_claimed_solicitations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote_state', to='dibbs.solicitation')),
            ],
            options={
                'verbose_name': 'Quote solicitation',
                'verbose_name_plural': 'Quote solicitations',
                'db_table': 'quote_solicitation',
                'indexes': [models.Index(fields=['status', 'status_changed_at'], name='quote_sol_status_changed')],
            },
        ),
    ]
