# Generated by Django 4.2.30 on 2026-09-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0015_supplieralias'),
        ('quote', '0005_seed_archive_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteemail',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_emails', to='suppliers.supplier'),
        ),
    ]
