# Generated by Django 4.2.30 on 2026-09-28 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0015_supplieralias'),
        ('quote', '0007_seed_reconcile_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCapabilityImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_name', models.CharField(blank=True, default='', help_text='Uploaded file name, or a label for pasted text.', max_length=255)),
                ('mode', models.CharField(choices=[('SINGLE', 'One supplier'), ('MULTI', 'Several suppliers')], default='MULTI', max_length=8)),
                ('suppliers_touched', models.PositiveIntegerField(default=0)),
                ('nsns_added', models.PositiveIntegerField(default=0)),
                ('fscs_added', models.PositiveIntegerField(default=0)),
                ('nsns_existing', models.PositiveIntegerField(default=0)),
                ('fscs_existing', models.PositiveIntegerField(default=0)),
                ('unreadable', models.PositiveIntegerField(default=0)),
                ('matches_created', models.PositiveIntegerField(default=0)),
                ('solicitations_matched', models.PositiveIntegerField(default=0, help_text='Open solicitations moved Unmatched -> Matched by this import.')),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, help_text='Set for one-supplier imports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_capability_imports', to='suppliers.supplier')),
                ('undone_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capability import',
                'verbose_name_plural': 'Capability imports',
                'db_table': 'quote_capability_import',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='quotesupplierfsc',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='The bulk import that created this row, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fsc_rows', to='quote.quotecapabilityimport'),
        ),
        migrations.AddField(
            model_name='quotesuppliernsn',
            name='import_batch',
            field=models.ForeignKey(blank=True, help_text='The bulk import that created this row, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nsn_rows', to='quote.quotecapabilityimport'),
        ),
    ]
