# Generated by Django 4.2.30 on 2026-09-29 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0015_supplieralias'),
        ('dibbs', '0005_seed_contract_admin_group'),
        ('quote', '0008_capability_imports'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotePackhouseRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RESPONDED', 'Replied')], db_index=True, default='SENT', max_length=12)),
                ('quantity', models.PositiveIntegerField(help_text='Units the packhouse was asked to price (sum of the lines covered).')),
                ('unit_of_issue', models.CharField(blank=True, default='', max_length=10)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, help_text='Unit weight, lb, as sent.', max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='', help_text="The rep's own note to the packhouse.")),
                ('email_sent_to', models.CharField(blank=True, default='', max_length=255)),
                ('sent_at', models.DateTimeField()),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_total', models.DecimalField(blank=True, decimal_places=2, help_text='Total pack cost for ``quantity``, if the packhouse quoted a total.', max_digits=15, null=True)),
                ('quoted_unit', models.DecimalField(blank=True, decimal_places=5, help_text='Per-unit pack cost. Derived from the total when only that was quoted.', max_digits=13, null=True)),
                ('quoted_lead_days', models.PositiveIntegerField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, help_text='Null = the request covers every line on the solicitation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_packhouse_rfqs', to='dibbs.solicitationline')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('packhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_packhouse_rfqs', to='suppliers.supplier')),
                ('quoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_packhouse_rfqs_recorded', to=settings.AUTH_USER_MODEL)),
                ('response_email', models.ForeignKey(blank=True, help_text='The mailbox message this request was answered by.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packhouse_replies', to='quote.quoteemail')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_packhouse_rfqs_sent', to=settings.AUTH_USER_MODEL)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_packhouse_rfqs', to='dibbs.solicitation')),
            ],
            options={
                'verbose_name': 'Quote packhouse RFQ',
                'verbose_name_plural': 'Quote packhouse RFQs',
                'db_table': 'quote_packhouse_rfq',
                'ordering': ['-sent_at', '-pk'],
                'indexes': [models.Index(fields=['solicitation', 'packhouse'], name='quote_phrfq_sol_ph')],
            },
        ),
    ]
