# Generated by Django 4.2.30 on 2026-09-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_packhouse_rfq'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesupplierquote',
            name='entry',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Shared by the rows one drawer save created (Combined = every line, Split = one line), so the drawer can reopen and edit that quote as one thing. Blank on rows saved before quotes could be edited.', max_length=36),
        ),
    ]
