# Generated by Django 4.2.30 on 2026-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0010_supplier_quote_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotesupplierquote',
            name='contact_name',
            field=models.CharField(blank=True, default='', help_text='Who at the supplier gave it, or a fax / reference number, for quotes entered by hand.', max_length=100),
        ),
        migrations.AddField(
            model_name='quotesupplierquote',
            name='received_on',
            field=models.DateField(blank=True, help_text='The day the supplier gave us the quote (the message date for email).', null=True),
        ),
        migrations.AddField(
            model_name='quotesupplierquote',
            name='source_channel',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('PHONE', 'Phone'), ('FAX', 'Fax'), ('WEB', 'Website / portal'), ('OTHER', 'Other')], default='EMAIL', help_text='How the quote reached us. Null source_email + a non-email channel = entered by hand.', max_length=8),
        ),
    ]
