# Generated by Django 6.0.3 on 2026-06-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ai_instruction',
            field=models.TextField(blank=True, help_text='Instruction prompt for the LLM', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='ai_status',
            field=models.CharField(choices=[('IDLE', 'Idle'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=20),
        ),
    ]
