# Generated by Django 6.0.3 on 2026-06-11 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_campaign_ai_instruction_campaign_ai_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='follow_up_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='current_followup_step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='follow_up_active',
            field=models.BooleanField(default=True, help_text='Set to False if the recipient replied so they stop getting pings'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CampaignFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('delay_days', models.PositiveIntegerField(help_text='Days to wait after the previous email was sent')),
                ('subject_template', models.CharField(blank=True, help_text="Leave blank to use 'Re: original subject'", max_length=255, null=True)),
                ('body_template', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='mailer.campaign')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('campaign', 'step_number')},
            },
        ),
    ]
