# Generated by Django 6.0.3 on 2026-06-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_campaign_follow_up_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_html_body',
            field=models.BooleanField(default=True, help_text='When True, body_template contains rich HTML from the editor. When False, plain text with auto-linking.'),
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='campaign_attachments/')),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='mailer.campaign')),
            ],
        ),
    ]
