# Generated by Django 5.0.11 on 2025-02-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appregistry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'verbose_name': 'App Permission', 'verbose_name_plural': 'App Permissions'},
        ),
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.appregistry', to_field='app_name'),
        ),
    ]
