# Generated by Django 5.0.11 on 2025-02-27 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_apppermission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermission',
            name='app_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appregistry'),
        ),
    ]
