# Generated by Django 5.0.11 on 2025-03-26 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_apppermission_app_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('setting_type', models.CharField(choices=[('boolean', 'Boolean'), ('string', 'String'), ('integer', 'Integer'), ('json', 'JSON')], max_length=20)),
                ('default_value', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSettingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='users.usersetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setting_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Setting State',
                'verbose_name_plural': 'User Setting States',
                'indexes': [models.Index(fields=['user', 'setting'], name='users_users_user_id_b55aa6_idx')],
                'unique_together': {('user', 'setting')},
            },
        ),
    ]
