# Generated by Django 4.2.20 on 2025-04-23 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0006_usersetting_usersettingstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='microsoft', max_length=50)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User OAuth Token',
                'verbose_name_plural': 'User OAuth Tokens',
            },
        ),
        migrations.RemoveIndex(
            model_name='usersettingstate',
            name='users_users_user_id_b55aa6_idx',
        ),
        migrations.RemoveField(
            model_name='usersettingstate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usersettingstate',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='usersettingstate',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='users.usersetting'),
        ),
        migrations.AlterField(
            model_name='usersettingstate',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useroauthtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_token', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='useroauthtoken',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider_token'),
        ),
    ]
