# Generated by Django 4.2.20 on 2025-05-19 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_useroauthtoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('source_app', models.CharField(help_text='The app that generated this message', max_length=50)),
                ('source_model', models.CharField(help_text='The model that generated this message', max_length=50)),
                ('source_id', models.CharField(help_text='The ID of the record that generated this message', max_length=50)),
                ('action_url', models.CharField(blank=True, help_text='URL to relevant action/page', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_syste_user_id_91b74c_idx'), models.Index(fields=['user', 'read_at'], name='users_syste_user_id_a49d8e_idx')],
            },
        ),
    ]
