# Generated by Django 4.2.25 on 2025-10-23 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_user_company_memberships(apps, schema_editor):
    Company = apps.get_model('contracts', 'Company')
    Membership = apps.get_model('users', 'UserCompanyMembership')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(app_label, model_name)

    company, _ = Company.objects.get_or_create(
        slug='company-a',
        defaults={'name': 'Company A', 'is_active': True},
    )

    for user in UserModel.objects.all():
        membership, created = Membership.objects.get_or_create(
            user=user,
            company=company,
            defaults={'is_default': True},
        )
        if not membership.is_default:
            membership.is_default = True
            membership.save(update_fields=['is_default'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "contracts",
            "0023_company_alter_foldertracking_stack_id_clin_company_and_more",
        ),
        ("users", "0008_systemmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCompanyMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="contracts.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Company Membership",
                "verbose_name_plural": "User Company Memberships",
                "unique_together": {("user", "company")},
            },
        ),
        migrations.RunPython(seed_user_company_memberships, migrations.RunPython.noop),
    ]
