# Generated by Django 6.0.3 on 2026-05-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_release_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='releasenote',
            new_name='users_relea_publish_2d1cf3_idx',
            old_name='users_relea_publish_0ab0ec_idx',
        ),
        migrations.RenameIndex(
            model_name='releasenoteacknowledgement',
            new_name='users_relea_user_id_d68843_idx',
            old_name='users_relea_user_id_7f8a1d_idx',
        ),
    ]
