# Generated by Django 4.2.25 on 2025-12-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0033_remove_contact_address_remove_contact_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CertificationType',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(blank=True, max_length=25, null=True)),
                        ('name', models.TextField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'contracts_certificationtype',
                    },
                ),
                migrations.CreateModel(
                    name='ClassificationType',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.TextField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'contracts_classificationtype',
                    },
                ),
                migrations.CreateModel(
                    name='Contact',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('salutation', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('', 'None')], default='', max_length=5)),
                        ('name', models.TextField()),
                        ('company', models.TextField(blank=True, null=True)),
                        ('title', models.TextField(blank=True, null=True)),
                        ('phone', models.CharField(blank=True, max_length=25, null=True)),
                        ('email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.address')),
                    ],
                    options={
                        'db_table': 'contracts_contact',
                    },
                ),
                migrations.CreateModel(
                    name='Supplier',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                        ('modified_on', models.DateTimeField(auto_now=True)),
                        ('name', models.CharField(blank=True, max_length=100, null=True)),
                        ('cage_code', models.CharField(blank=True, max_length=10, null=True)),
                        ('dodaac', models.CharField(blank=True, max_length=10, null=True)),
                        ('business_phone', models.CharField(blank=True, max_length=25, null=True)),
                        ('business_fax', models.CharField(blank=True, max_length=25, null=True)),
                        ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                        ('probation', models.BooleanField(blank=True, null=True)),
                        ('probation_on', models.DateTimeField(blank=True, null=True)),
                        ('conditional', models.BooleanField(blank=True, null=True)),
                        ('conditional_on', models.DateTimeField(blank=True, null=True)),
                        ('special_terms_on', models.DateTimeField(blank=True, null=True)),
                        ('prime', models.IntegerField(blank=True, null=True)),
                        ('ppi', models.BooleanField(blank=True, null=True)),
                        ('iso', models.BooleanField(blank=True, null=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('is_packhouse', models.BooleanField(blank=True, null=True)),
                        ('files_url', models.CharField(blank=True, max_length=400, null=True)),
                        ('allows_gsi', models.CharField(choices=[('UNK', 'Unknown'), ('YES', 'Yes'), ('NO', 'No')], default='UNK', help_text='Whether the supplier allows GSI at facility (Unknown until confirmed).', max_length=3)),
                        ('archived', models.BooleanField(default=False)),
                        ('archived_on', models.DateTimeField(blank=True, null=True)),
                        ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_supplier_archived', to=settings.AUTH_USER_MODEL)),
                        ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_billing', to='contracts.address')),
                        ('conditional_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_supplier_conditional', to=settings.AUTH_USER_MODEL)),
                        ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_for_supplier', to='suppliers.contact')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                        ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                        ('packhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                        ('physical_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_physical', to='contracts.address')),
                        ('probation_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_supplier_probation', to=settings.AUTH_USER_MODEL)),
                        ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_shipping', to='contracts.address')),
                        ('special_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.specialpaymentterms')),
                    ],
                    options={
                        'db_table': 'contracts_supplier',
                    },
                ),
                migrations.CreateModel(
                    name='SupplierCertification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('certification_date', models.DateTimeField(blank=True, null=True)),
                        ('certification_expiration', models.DateTimeField(blank=True, null=True)),
                        ('compliance_status', models.CharField(blank=True, default=None, max_length=25, null=True)),
                        ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.certificationtype')),
                        ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                    ],
                    options={
                        'db_table': 'contracts_suppliercertification',
                    },
                ),
                migrations.CreateModel(
                    name='SupplierClassification',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('classification_date', models.DateTimeField(blank=True, null=True)),
                        ('classification_expiration', models.DateTimeField(blank=True, null=True)),
                        ('classification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.classificationtype')),
                        ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
                    ],
                    options={
                        'db_table': 'contracts_supplierclassification',
                    },
                ),
                migrations.CreateModel(
                    name='SupplierType',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(blank=True, max_length=1, null=True)),
                        ('description', models.TextField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'contracts_suppliertype',
                    },
                ),
                migrations.CreateModel(
                    name='SupplierDocument',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                        ('modified_on', models.DateTimeField(auto_now=True)),
                        ('doc_type', models.CharField(choices=[('CERT', 'Certification'), ('CLASS', 'Classification'), ('GENERAL', 'General')], default='GENERAL', max_length=12)),
                        ('description', models.CharField(blank=True, max_length=255, null=True)),
                        ('file', models.FileField(upload_to='supplier-docs/')),
                        ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.suppliercertification')),
                        ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.supplierclassification')),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                        ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                        ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.supplier')),
                    ],
                    options={
                        'db_table': 'contracts_supplierdocument',
                    },
                ),
                migrations.AddField(
                    model_name='supplier',
                    name='supplier_type',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.suppliertype'),
                ),
                migrations.AddField(
                    model_name='contact',
                    name='supplier',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier'),
                ),
            ],
            database_operations=[],
        ),
    ]
