# Generated by Django 4.2.24 on 2025-12-09 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0002_supplier_last_enriched_at_supplier_logo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRouterModelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=100, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('needs_update', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_openrouter_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpenRouter Model Setting',
                'verbose_name_plural': 'OpenRouter Model Settings',
            },
        ),
    ]
