# Generated by Django for Session 10A — RFQ email on Supplier

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0003_openroutermodelsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="rfq_email",
            field=models.EmailField(
                blank=True,
                help_text="Preferred email address for RFQ dispatch. Set via the supplier profile.",
                max_length=254,
                null=True,
            ),
        ),
    ]
