# Generated by Django 5.0.14 on 2026-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_suppliercontactgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='archived_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='conditional_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='probation_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='special_terms_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercertification',
            name='certification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliercertification',
            name='certification_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierclassification',
            name='classification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierclassification',
            name='classification_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
