# Generated by Django 5.0.14 on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_alter_supplier_archived_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=(
                    'Designates this as a primary contact for the supplier. '
                    'Multiple contacts per supplier may be marked primary — '
                    'no uniqueness constraint is enforced.'
                ),
                null=True,
            ),
        ),
    ]
