# Generated by Django 5.0.14 on 2026-05-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_contact_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
    ]
