# Generated by Django 6.0.3 on 2026-08-13 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0014_supplier_cage_unique_and_portal_changelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_aliases_created', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'contracts_supplieralias',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'name'), name='uniq_supplieralias_supplier_name')],
            },
        ),
    ]
