# Generated by Django 5.0.14 on 2026-05-17 23:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0065_clin_fix_tool'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Unique identity; enforces dedup against re-injection.', max_length=25, unique=True)),
                ('contract_type', models.CharField(choices=[('AWD', 'Award'), ('PO', 'Purchase Order'), ('DO', 'Delivery Order'), ('IDIQ', 'IDIQ'), ('MOD', 'Modification'), ('AMD', 'Amendment'), ('INTERNAL', 'Internal')], max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_parse_status', models.CharField(choices=[('pending', 'Pending'), ('no_pdf', 'No PDF'), ('parseable', 'Parseable'), ('partial', 'Parsed with Warnings'), ('success', 'Success')], default='pending', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Type-specific fields, child records, parser provenance. Validated per contract_type by intake.schemas.validate_data.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('final_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_source_drafts', to='contracts.contract')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_locked_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Draft Contract',
                'verbose_name_plural': 'Draft Contracts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='intake_draf_status_748349_idx'), models.Index(fields=['contract_type'], name='intake_draf_contrac_5c7c45_idx'), models.Index(fields=['locked_by'], name='intake_draf_locked__3973d0_idx'), models.Index(fields=['created_at'], name='intake_draf_created_820b6b_idx')],
            },
        ),
    ]
