# Generated by Django 6.0.3 on 2026-07-08 15:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0088_contractlevelcharge_action_type'),
        ('intake', '0002_draftcontract_company_sharepoint'),
        ('sales', '0052_backfill_dibbs_award_mod_matched_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(help_text='Canonical (dashed) contract number — matches DraftContract.contract_number / Contract.contract_number.', max_length=25, unique=True)),
                ('award_basic_number', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_order_number', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_order_counter', models.CharField(blank=True, default='', max_length=20)),
                ('awardee_cage', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('nsn', models.CharField(blank=True, default='', max_length=46)),
                ('nomenclature', models.CharField(blank=True, default='', max_length=100)),
                ('purchase_request', models.CharField(blank=True, default='', max_length=20)),
                ('solicitation', models.CharField(blank=True, default='', max_length=50)),
                ('total_contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('aw_file_date', models.DateField(blank=True, null=True)),
                ('last_mod_posting_date', models.DateField(blank=True, null=True)),
                ('mod_count', models.PositiveIntegerField(default=0)),
                ('is_we_won', models.BooleanField(default=False)),
                ('has_award', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft_created_at', models.DateTimeField(blank=True, null=True)),
                ('draft_worked_at', models.DateTimeField(blank=True, null=True)),
                ('mod_record_created_at', models.DateTimeField(blank=True, null=True)),
                ('live_contract_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_state', models.CharField(choices=[('not_we_won', 'Not We-Won'), ('mod_only', 'Mod Only'), ('awaiting_draft', 'Awaiting Draft'), ('in_draft', 'In Draft'), ('draft_worked', 'Draft Worked'), ('live_contract', 'Live Contract')], db_index=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award_ledger_entries', to='contracts.contract')),
                ('dibbs_award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='sales.dibbsaward')),
            ],
            options={
                'verbose_name': 'Award Ledger Entry',
                'verbose_name_plural': 'Award Ledger Entries',
                'db_table': 'intake_award_ledger',
                'ordering': ['-first_seen_at'],
                'indexes': [models.Index(fields=['is_we_won'], name='award_ledger_we_won_idx'), models.Index(fields=['lifecycle_state'], name='award_ledger_state_idx'), models.Index(fields=['awardee_cage'], name='award_ledger_cage_idx'), models.Index(fields=['first_seen_at'], name='award_ledger_seen_idx'), models.Index(fields=['live_contract_at'], name='award_ledger_live_idx')],
            },
        ),
    ]
