# Generated by Django 4.2.30 on 2026-07-17 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_legacy_source(apps, schema_editor):
    AwardLedger = apps.get_model('intake', 'AwardLedger')
    AwardLedger.objects.all().update(ingestion_source='legacy')


def reverse_backfill(apps, schema_editor):
    AwardLedger = apps.get_model('intake', 'AwardLedger')
    AwardLedger.objects.all().update(ingestion_source='')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intake', '0003_award_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awardledger',
            name='draft_worked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_worked_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awardledger',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_finalized_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='awardledger',
            name='ingestion_source',
            field=models.CharField(blank=True, choices=[('dibbs_scrape', 'DIBBS Scrape'), ('dibbs_poll', 'DIBBS Poll'), ('pdf_upload', 'PDF Upload'), ('manual', 'Manual Entry'), ('legacy', 'Legacy (pre-tracking)')], default='', max_length=20),
        ),
        migrations.RunPython(backfill_legacy_source, reverse_backfill),
    ]
