# Generated by Django 5.0.14 on 2026-06-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('last_sync_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Budget',
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('call_site', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.IntegerField()),
                ('output_tokens', models.IntegerField()),
                ('cost_usd', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
