# Generated by Django 6.0.3 on 2026-06-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('interval_minutes', models.IntegerField()),
                ('run_order', models.IntegerField(default=0, help_text='Lower numbers run first when multiple tasks are due simultaneously.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('freeze_count', models.IntegerField(default=0, help_text='Incremented each time a stale lock is detected and cleared on this task.')),
            ],
            options={
                'ordering': ['run_order'],
            },
        ),
    ]
