# Generated by Django 5.0.11 on 2025-02-07 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField(default=django.utils.timezone.now)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_company', models.CharField(max_length=100)),
                ('reason_for_visit', models.CharField(max_length=200)),
                ('id_confirm', models.CharField(blank=True, max_length=50)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('departed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_of_visit', '-time_in'],
            },
        ),
    ]
