# Generated by Django 5.0.11 on 2025-02-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='id_confirm',
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_us_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
