# Generated by Django 5.0.11 on 2025-02-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslog', '0002_remove_visitor_id_confirm_visitor_is_us_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_company', models.CharField(max_length=100)),
                ('reason_for_visit', models.CharField(max_length=200)),
            ],
        ),
    ]
