# Generated by Django 5.0.11 on 2025-02-10 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslog', '0003_staged'),
    ]

    operations = [
        migrations.AddField(
            model_name='staged',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staged',
            name='is_us_citizen',
            field=models.BooleanField(default=False),
        ),
    ]
