# Generated by Django 5.0.11 on 2025-02-11 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesslog', '0004_staged_date_added_staged_is_us_citizen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='time_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
