# Generated by Django 4.2.20 on 2025-04-10 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0007_remove_clinqueue_contract_queue_and_more'),
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50)),
                ('buyer_text', models.CharField(blank=True, max_length=255)),
                ('award_date', models.DateField()),
                ('due_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('queue_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.buyer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_process_contracts', to=settings.AUTH_USER_MODEL)),
                ('final_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contract')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_process_contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Processing Contract',
                'verbose_name_plural': 'Processing Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessCLIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clin_number', models.CharField(max_length=50)),
                ('nsn_text', models.CharField(blank=True, max_length=255)),
                ('nsn_description_text', models.TextField(blank=True)),
                ('supplier_text', models.CharField(blank=True, max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('final_clin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.clin')),
                ('nsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.nsn')),
                ('process_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clins', to='processing.processcontract')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.supplier')),
            ],
            options={
                'verbose_name': 'Processing CLIN',
                'verbose_name_plural': 'Processing CLINs',
                'ordering': ['clin_number'],
            },
        ),
    ]
