# Generated by Django 4.2.20 on 2025-04-11 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0002_alter_processclin_process_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processcontract',
            name='planned_split',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='ppi_split',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='ppi_split_paid',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='statz_split',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='statz_split_paid',
        ),
        migrations.CreateModel(
            name='ContractSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('split_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('split_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('process_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='processing.processcontract')),
            ],
            options={
                'verbose_name': 'Contract Split',
                'verbose_name_plural': 'Contract Splits',
                'ordering': ['company_name'],
            },
        ),
    ]
