# Generated by Django 4.2.20 on 2025-04-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0003_remove_processcontract_planned_split_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processclin',
            name='clin_type_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processclin',
            name='special_payment_terms_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processcontract',
            name='contract_type_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processcontract',
            name='sales_class_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='queueclin',
            name='uom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
