# Generated by Django 4.2.20 on 2025-04-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0004_processclin_clin_type_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcontract',
            name='planned_split',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
