# Generated by Django 4.2.20 on 2025-04-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0005_processcontract_planned_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processclin',
            name='plan_gross',
        ),
        migrations.RemoveField(
            model_name='processclin',
            name='planned_split',
        ),
        migrations.RemoveField(
            model_name='processclin',
            name='ppi_split',
        ),
        migrations.RemoveField(
            model_name='processclin',
            name='ppi_split_paid',
        ),
        migrations.RemoveField(
            model_name='processclin',
            name='statz_split',
        ),
        migrations.RemoveField(
            model_name='processclin',
            name='statz_split_paid',
        ),
    ]
