# Generated by Django 4.2.20 on 2025-04-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0006_remove_processclin_plan_gross_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcontract',
            name='plan_gross',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
