# Generated by Django 4.2.20 on 2025-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0008_alter_contractsplit_split_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcontract',
            name='queue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
