# Generated by Django 4.2.20 on 2025-04-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0009_alter_processcontract_queue_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractsplit',
            table='processing_contractsplit',
        ),
    ]
