# Generated by Django 4.2.20 on 2025-04-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0010_alter_contractsplit_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContractSplit',
            new_name='ProcessContractSplit',
        ),
    ]
