# Generated by Django 4.2.25 on 2025-10-23 13:11

from django.db import migrations, models
import django.db.models.deletion


def seed_processing_companies(apps, schema_editor):
    Company = apps.get_model('contracts', 'Company')
    ProcessContract = apps.get_model('processing', 'ProcessContract')
    ProcessClin = apps.get_model('processing', 'ProcessClin')
    QueueContract = apps.get_model('processing', 'QueueContract')
    QueueClin = apps.get_model('processing', 'QueueClin')

    company, _ = Company.objects.get_or_create(
        slug='company-a',
        defaults={'name': 'Company A', 'is_active': True},
    )

    ProcessContract.objects.filter(company__isnull=True).update(company=company)
    ProcessClin.objects.filter(company__isnull=True).update(company=company)
    QueueContract.objects.filter(company__isnull=True).update(company=company)
    QueueClin.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        (
            "contracts",
            "0023_company_alter_foldertracking_stack_id_clin_company_and_more",
        ),
        ("processing", "0011_rename_contractsplit_processcontractsplit"),
    ]

    operations = [
        migrations.AddField(
            model_name="processclin",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processing_clins",
                to="contracts.company",
            ),
        ),
        migrations.AddField(
            model_name="processcontract",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processing_contracts",
                to="contracts.company",
            ),
        ),
        migrations.AddField(
            model_name="queueclin",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_clins",
                to="contracts.company",
            ),
        ),
        migrations.AddField(
            model_name="queuecontract",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_contracts",
                to="contracts.company",
            ),
        ),
        migrations.RunPython(seed_processing_companies, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="processclin",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processing_clins",
                to="contracts.company",
            ),
        ),
        migrations.AlterField(
            model_name="processcontract",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processing_contracts",
                to="contracts.company",
            ),
        ),
        migrations.AlterField(
            model_name="queueclin",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_clins",
                to="contracts.company",
            ),
        ),
        migrations.AlterField(
            model_name="queuecontract",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_contracts",
                to="contracts.company",
            ),
        ),
    ]
