# Generated by Django 4.2.25 on 2025-12-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
        ('processing', '0012_processclin_company_processcontract_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processclin',
            name='nsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.nsn'),
        ),
        migrations.AlterField(
            model_name='processclin',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='queueclin',
            name='matched_nsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.nsn'),
        ),
        migrations.AlterField(
            model_name='queueclin',
            name='matched_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.supplier'),
        ),
    ]
