# Generated by Django 4.2.25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("processing", "0013_alter_processclin_nsn_alter_processclin_supplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuecontract",
            name="idiq_number",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Populated automatically when this contract originated from a DIBBS "
                    "delivery order. Stores the IDIQ parent contract number as a hint for "
                    "the analyst to match the IDIQ contract in the processing form."
                ),
                max_length=50,
                null=True,
                verbose_name="IDIQ Contract Number",
            ),
        ),
    ]
