# Generated by Django 6.0.3 on 2026-04-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0014_queuecontract_idiq_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuecontract',
            name='pdf_parse_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='queuecontract',
            name='pdf_parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Parsed with Errors')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='queuecontract',
            name='pdf_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
