# Generated by Django 6.0.3 on 2026-04-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0017_queuecontract_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuecontract',
            name='award_pdf_status',
            field=models.CharField(choices=[('pending', 'Not Uploaded'), ('uploaded', 'Uploaded'), ('error', 'Upload Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='queuecontract',
            name='sharepoint_folder_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('exists', 'Already Exists'), ('error', 'Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='queuecontract',
            name='sharepoint_folder_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='queuecontract',
            name='sharepoint_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
