# Generated by Django 6.0.3 on 2026-04-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0019_replace_processcontractsplit_with_processclin_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcontract',
            name='solicitation_type',
            field=models.CharField(blank=True, default='SDVOSB', max_length=50, null=True),
        ),
    ]
