# Generated by Django 5.0.14 on 2026-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0020_alter_processcontract_solicitation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcontract',
            name='pr_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PR Number'),
        ),
        migrations.AddField(
            model_name='queuecontract',
            name='pr_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PR Number'),
        ),
    ]
