# Generated by Django 5.0.14 on 2026-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0021_processcontract_pr_number_queuecontract_pr_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processcontract',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processcontract',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuecontract',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queuecontract',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
