# Generated by Django 6.0.3 on 2026-05-12 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0022_alter_processcontract_award_date_and_more'),
        ('suppliers', '0006_alter_supplier_archived_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcontract',
            name='packhouse',
            field=models.ForeignKey(blank=True, help_text='Packhouse for this contract. Optional — most contracts have none.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='processcontract',
            name='packhouse_notes',
            field=models.TextField(blank=True, help_text='Analyst notes about the packhouse arrangement. Copied to ContractPackaging.notes on finalization.', null=True),
        ),
        migrations.AddField(
            model_name='processcontract',
            name='packhouse_quote_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packaging quote captured during processing. Copied to ContractPackaging.quote_amount on finalization.', max_digits=15, null=True),
        ),
    ]
