# Generated by Django 6.0.3 on 2026-05-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0023_processcontract_packhouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processcontract',
            name='packhouse_cage',
            field=models.CharField(blank=True, help_text='CAGE code from queue contract packhouse inspection block.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='queuecontract',
            name='packhouse_cage',
            field=models.CharField(blank=True, help_text="CAGE code parsed from 'PLACE of INSPECTION for PACKAGING' in Section B.", max_length=20, null=True),
        ),
    ]
