# Generated by Django 5.0.14 on 2026-06-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0024_processcontract_packhouse_cage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessContractCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='processing.processcontract')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
