# Generated by Django 5.0.11 on 2025-02-25 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CanceledReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nsn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn_code', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('part_number', models.CharField(blank=True, max_length=25, null=True)),
                ('revision', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_team', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.address')),
            ],
        ),
        migrations.CreateModel(
            name='Clin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('sub_contract', models.CharField(blank=True, max_length=20, null=True)),
                ('po_num_ext', models.CharField(blank=True, max_length=5, null=True)),
                ('tab_num', models.CharField(blank=True, max_length=10, null=True)),
                ('clin_po_num', models.CharField(blank=True, max_length=10, null=True)),
                ('po_number', models.CharField(blank=True, max_length=10, null=True)),
                ('ia', models.CharField(blank=True, max_length=5, null=True)),
                ('fob', models.CharField(blank=True, max_length=5, null=True)),
                ('order_qty', models.FloatField(blank=True, null=True)),
                ('ship_qty', models.FloatField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_date_late', models.BooleanField(blank=True, null=True)),
                ('supplier_due_date', models.DateField(blank=True, null=True)),
                ('supplier_due_date_late', models.BooleanField(blank=True, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('ship_date_late', models.BooleanField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcknowledgementLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('letter_date', models.DateTimeField(blank=True, null=True)),
                ('salutation', models.TextField(blank=True, null=True)),
                ('addr_fname', models.TextField(blank=True, null=True)),
                ('addr_lname', models.TextField(blank=True, null=True)),
                ('supplier', models.TextField(blank=True, null=True)),
                ('st_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip', models.IntegerField(blank=True, null=True)),
                ('po', models.IntegerField(blank=True, null=True)),
                ('po_ext', models.IntegerField(blank=True, null=True)),
                ('contract_num', models.IntegerField(blank=True, null=True)),
                ('fat_plt_due_date', models.DateTimeField(blank=True, null=True)),
                ('supplier_due_date', models.DateTimeField(blank=True, null=True)),
                ('dpas_priority', models.IntegerField(blank=True, null=True)),
                ('statz_contact', models.TextField(blank=True, null=True)),
                ('statz_contact_title', models.TextField(blank=True, null=True)),
                ('statz_contact_phone', models.IntegerField(blank=True, null=True)),
                ('statz_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('clin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.clin')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('po_to_supplier_bool', models.BooleanField(blank=True, null=True)),
                ('po_to_supplier_date', models.DateTimeField(blank=True, null=True)),
                ('po_to_supplier_user', models.TextField(blank=True, null=True)),
                ('clin_reply_bool', models.BooleanField(blank=True, null=True)),
                ('clin_reply_date', models.DateTimeField(blank=True, null=True)),
                ('clin_reply_user', models.TextField(blank=True, null=True)),
                ('clin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.clin')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClinFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('special_payment_terms_paid', models.BooleanField(blank=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('po_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('wawf_payment', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('wawf_recieved', models.DateTimeField(blank=True, null=True)),
                ('wawf_invoice', models.CharField(blank=True, max_length=25, null=True)),
                ('plan_gross', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('planned_split', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('special_payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.specialpaymentterms')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clin',
            name='clin_finance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.clinfinance'),
        ),
        migrations.CreateModel(
            name='ClinNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('clin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.clin')),
            ],
        ),
        migrations.AddField(
            model_name='clin',
            name='clin_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.clintype'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('title', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.address')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(blank=True, max_length=25, null=True)),
                ('open', models.BooleanField(blank=True, null=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(blank=True, null=True)),
                ('date_canceled', models.DateTimeField(blank=True, null=True)),
                ('po_number', models.CharField(blank=True, max_length=10, null=True)),
                ('tab_num', models.CharField(blank=True, max_length=10, null=True)),
                ('award_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('due_date_late', models.BooleanField(blank=True, null=True)),
                ('survey_date', models.DateField(blank=True, null=True)),
                ('survey_type', models.CharField(blank=True, max_length=10, null=True)),
                ('assigned_user', models.CharField(blank=True, max_length=20, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('nist', models.BooleanField(blank=True, null=True)),
                ('files_url', models.CharField(blank=True, max_length=200, null=True)),
                ('reviewed', models.BooleanField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=20, null=True)),
                ('reviewed_on', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.buyer')),
                ('canceled_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.canceledreason')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contracttype')),
                ('sales_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.salesclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='clin',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
        ),
        migrations.CreateModel(
            name='ContractNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='IdiqContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True)),
                ('award_date', models.DateTimeField(blank=True, null=True)),
                ('term_length', models.IntegerField(blank=True, null=True)),
                ('option_length', models.IntegerField(blank=True, null=True)),
                ('closed', models.BooleanField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.buyer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdiqContractToContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('idiq_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.idiqcontract')),
            ],
        ),
        migrations.AddField(
            model_name='clin',
            name='nsn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.nsn'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('cage_code', models.IntegerField(blank=True, null=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.address')),
                ('supplier_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.suppliertype')),
            ],
        ),
        migrations.CreateModel(
            name='IdiqContractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiq_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.idiqcontract')),
                ('nsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.nsn')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='clin',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier'),
        ),
    ]
