# Generated by Django 4.2.20 on 2025-04-09 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(blank=True, max_length=25, null=True)),
                ('buyer', models.CharField(blank=True, max_length=255, null=True)),
                ('award_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=50, null=True)),
                ('solicitation_type', models.CharField(blank=True, default='SDVOSB', max_length=10, null=True)),
                ('is_being_processed', models.BooleanField(default=False)),
                ('processing_started', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matched_buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.buyer')),
                ('matched_contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.contracttype')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClinQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('item_number', models.CharField(blank=True, max_length=20, null=True)),
                ('item_type', models.CharField(blank=True, max_length=20, null=True)),
                ('nsn', models.CharField(blank=True, max_length=20, null=True)),
                ('nsn_description', models.TextField(blank=True, null=True)),
                ('ia', models.CharField(blank=True, choices=[('O', 'Origin'), ('D', 'Destination')], max_length=5, null=True)),
                ('fob', models.CharField(blank=True, choices=[('O', 'Origin'), ('D', 'Destination')], max_length=5, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order_qty', models.FloatField(blank=True, null=True)),
                ('item_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_due_date', models.DateField(blank=True, null=True)),
                ('supplier_unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('supplier_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('supplier_payment_terms', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clins', to='contracts.contractqueue')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('matched_nsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.nsn')),
                ('matched_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.supplier')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='contractqueue',
            index=models.Index(fields=['contract_number'], name='contracts_c_contrac_82ab9e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractqueue',
            index=models.Index(fields=['is_being_processed'], name='contracts_c_is_bein_ea9329_idx'),
        ),
        migrations.AddIndex(
            model_name='contractqueue',
            index=models.Index(fields=['processed_by'], name='contracts_c_process_d67728_idx'),
        ),
        migrations.AddIndex(
            model_name='clinqueue',
            index=models.Index(fields=['contract_queue'], name='contracts_c_contrac_14587e_idx'),
        ),
        migrations.AddIndex(
            model_name='clinqueue',
            index=models.Index(fields=['nsn'], name='contracts_c_nsn_905cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='clinqueue',
            index=models.Index(fields=['supplier'], name='contracts_c_supplie_f0d7a6_idx'),
        ),
    ]
