# Generated by Django 4.2.20 on 2025-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contractqueue_clinqueue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractqueue',
            name='solicitation_type',
            field=models.CharField(blank=True, default='SDVOSB', max_length=50, null=True),
        ),
    ]
