# Generated by Django 5.0.11 on 2025-03-24 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_create_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationstatus',
            name='code',
        ),
        migrations.RemoveField(
            model_name='certificationstatus',
            name='name',
        ),
        migrations.AddField(
            model_name='certificationstatus',
            name='certification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationstatus',
            name='certification_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationstatus',
            name='certification_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.certificationtype'),
        ),
        migrations.AddField(
            model_name='certificationstatus',
            name='compliance_status',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='certificationstatus',
            name='supplier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier'),
        ),
    ]
