# Generated by Django 5.0.11 on 2025-02-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contact_company_contact_notes_contact_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiqcontract',
            name='tab_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
