# Generated by Django 5.0.11 on 2025-03-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_remove_certificationstatus_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foldertracking',
            name='stack',
            field=models.CharField(choices=[('0 - NONE', 'NONE'), ('1 - COS', 'COS'), ('2 - PACK', 'PACK'), ('3 - PROCESS', 'PROCESS'), ('4 - W4QAR', 'W4QAR'), ('5 - W4BOL', 'W4BOL'), ('6 - W4POS', 'W4POS'), ('7 - W4POD', 'W4POD'), ('8 - W4PAY', 'W4PAY'), ('9 - QSIGN', 'QSIGN'), ('10 - PAID', 'PAID')], max_length=20),
        ),
    ]
