# Generated by Django 4.2.20 on 2025-04-10 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0003_alter_contractqueue_solicitation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(blank=True, max_length=25, null=True)),
                ('solicitation_type', models.CharField(blank=True, default='SDVOSB', max_length=10, null=True)),
                ('po_number', models.CharField(blank=True, max_length=10, null=True)),
                ('tab_num', models.CharField(blank=True, max_length=10, null=True)),
                ('award_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('due_date_late', models.BooleanField(blank=True, null=True)),
                ('nist', models.BooleanField(blank=True, null=True)),
                ('files_url', models.CharField(blank=True, max_length=200, null=True)),
                ('contract_value', models.FloatField(blank=True, default=0, null=True)),
                ('planned_split', models.CharField(blank=True, max_length=50, null=True)),
                ('ppi_split', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('statz_split', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('ppi_split_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('statz_split_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.buyer')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_process_contracts', to=settings.AUTH_USER_MODEL)),
                ('contract_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contracttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('idiq_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.idiqcontract')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('queue_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contractqueue')),
                ('sales_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.salesclass')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessClin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('item_number', models.CharField(blank=True, max_length=20, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('P', 'Production'), ('G', 'GFAT'), ('C', 'CFAT'), ('L', 'PLT'), ('M', 'Miscellaneous')], max_length=20, null=True)),
                ('item_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('po_num_ext', models.CharField(blank=True, max_length=5, null=True)),
                ('tab_num', models.CharField(blank=True, max_length=10, null=True)),
                ('clin_po_num', models.CharField(blank=True, max_length=10, null=True)),
                ('po_number', models.CharField(blank=True, max_length=10, null=True)),
                ('ia', models.CharField(blank=True, choices=[('O', 'Origin'), ('D', 'Destination')], max_length=5, null=True)),
                ('fob', models.CharField(blank=True, choices=[('O', 'Origin'), ('D', 'Destination')], max_length=5, null=True)),
                ('order_qty', models.FloatField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_date_late', models.BooleanField(blank=True, null=True)),
                ('supplier_due_date', models.DateField(blank=True, null=True)),
                ('supplier_due_date_late', models.BooleanField(blank=True, null=True)),
                ('special_payment_terms_paid', models.BooleanField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('quote_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('plan_gross', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('planned_split', models.CharField(blank=True, max_length=50, null=True)),
                ('ppi_split', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('statz_split', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('ppi_split_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('statz_split_paid', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('special_payment_terms_interest', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('special_payment_terms_party', models.CharField(blank=True, max_length=50, null=True)),
                ('processing_status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('ready_for_review', 'Ready for Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('clin_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.clintype')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_process_clins', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('nsn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.nsn')),
                ('process_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clins', to='contracts.processcontract')),
                ('special_payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.specialpaymentterms')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier')),
            ],
        ),
        migrations.AddIndex(
            model_name='processcontract',
            index=models.Index(fields=['contract_number'], name='contracts_p_contrac_5ad685_idx'),
        ),
        migrations.AddIndex(
            model_name='processcontract',
            index=models.Index(fields=['processing_status'], name='contracts_p_process_fa1820_idx'),
        ),
        migrations.AddIndex(
            model_name='processcontract',
            index=models.Index(fields=['queue_id'], name='contracts_p_queue_i_401d65_idx'),
        ),
        migrations.AddIndex(
            model_name='processclin',
            index=models.Index(fields=['process_contract'], name='contracts_p_process_cc5346_idx'),
        ),
        migrations.AddIndex(
            model_name='processclin',
            index=models.Index(fields=['processing_status'], name='contracts_p_process_84edf9_idx'),
        ),
        migrations.AddIndex(
            model_name='processclin',
            index=models.Index(fields=['item_number'], name='contracts_p_item_nu_24e3fe_idx'),
        ),
    ]
