# Generated by Django 5.0.11 on 2025-02-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_nsn_created_by_nsn_created_on_nsn_directory_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsn',
            name='nsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cage_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
