# Generated by Django 4.2.20 on 2025-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_processcontract_processclin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processclin',
            name='nsn_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processclin',
            name='nsn_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='processclin',
            name='supplier_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processcontract',
            name='buyer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='processclin',
            index=models.Index(fields=['supplier_text'], name='contracts_p_supplie_64fa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='processclin',
            index=models.Index(fields=['nsn_text'], name='contracts_p_nsn_tex_408df1_idx'),
        ),
        migrations.AddIndex(
            model_name='processcontract',
            index=models.Index(fields=['buyer_text'], name='contracts_p_buyer_t_62f4fb_idx'),
        ),
    ]
