# Generated by Django 5.0.11 on 2025-03-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_usersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
