# Generated by Django 5.0.11 on 2025-02-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_alter_nsn_nsn_code_alter_supplier_cage_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpaymentterms',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
