# Generated by Django 4.2.20 on 2025-04-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_processclin_nsn_description_processclin_nsn_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processcontract',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='idiq_contract',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='queue_id',
        ),
        migrations.RemoveField(
            model_name='processcontract',
            name='sales_class',
        ),
        migrations.DeleteModel(
            name='ProcessCLIN',
        ),
        migrations.DeleteModel(
            name='ProcessContract',
        ),
    ]
