# Generated by Django 5.0.11 on 2025-03-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_delete_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_count', models.IntegerField()),
                ('export_time', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('filters_applied', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
