# Generated by Django 5.0.11 on 2025-02-25 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_specialpaymentterms_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.AddField(
            model_name='supplier',
            name='allows_gsi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_billing', to='contracts.address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_fax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='business_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='conditional',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='conditional_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_conditional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='conditional_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.contact'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='files_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_packhouse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='iso',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='packhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='physical_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_physical', to='contracts.address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ppi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='prime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='probation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='probation_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_probation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='probation_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_shipping', to='contracts.address'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='special_terms_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplier',
            name='special_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.specialterms'),
        ),
        migrations.CreateModel(
            name='SupplierCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_date', models.DateTimeField(blank=True, null=True)),
                ('certification_expiration', models.DateTimeField(blank=True, null=True)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.certificationtype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_date', models.DateTimeField(blank=True, null=True)),
                ('classification_expiration', models.DateTimeField(blank=True, null=True)),
                ('classification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.classificationtype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.supplier')),
            ],
        ),
    ]
