# Generated by Django 4.2.20 on 2025-04-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_processcontract_buyer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinqueue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='clinqueue',
            name='matched_nsn',
        ),
        migrations.RemoveField(
            model_name='clinqueue',
            name='matched_supplier',
        ),
        migrations.RemoveField(
            model_name='clinqueue',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='contractqueue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='contractqueue',
            name='matched_buyer',
        ),
        migrations.RemoveField(
            model_name='contractqueue',
            name='matched_contract_type',
        ),
        migrations.RemoveField(
            model_name='contractqueue',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='contractqueue',
            name='processed_by',
        ),
        migrations.DeleteModel(
            name='SequenceNumber',
        ),
        migrations.DeleteModel(
            name='ClinQueue',
        ),
        migrations.DeleteModel(
            name='ContractQueue',
        ),
    ]
