# Generated by Django 5.0.11 on 2025-02-25 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_certificationtype_classificationtype_specialterms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='special_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.specialpaymentterms'),
        ),
        migrations.DeleteModel(
            name='SpecialTerms',
        ),
    ]
