# Generated by Django 5.0.11 on 2025-03-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_exporttiming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliercertification',
            name='compliance_status',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterModelOptions(
            name='exporttiming',
            options={},
        ),
        migrations.AddField(
            model_name='suppliertype',
            name='code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='exporttiming',
            name='filters_applied',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='CertificationStatus',
        ),
    ]
