# Generated by Django 4.2.20 on 2025-04-14 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_remove_clinqueue_contract_queue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('split_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('split_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Split',
                'verbose_name_plural': 'Contract Splits',
                'ordering': ['company_name'],
            },
        ),
    ]
