# Generated by Django 5.0.11 on 2025-02-25 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_supplier_special_terms_delete_specialterms'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_fax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='suppliercertification',
            name='compliance_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.certificationstatus'),
        ),
    ]
