# Generated by Django 4.2.20 on 2025-04-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_contractsplit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractsplit',
            table='contract_contractsplit',
        ),
    ]
