# Generated by Django 5.0.11 on 2025-03-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_alter_suppliercertification_compliance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clin',
            name='special_payment_terms_interest',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='clin',
            name='special_payment_terms_party',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
