# Generated by Django 5.0.11 on 2025-02-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_certificationstatus_certificationtype_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='contract_num',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='dpas_priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='po',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='po_ext',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='statz_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
