# Generated by Django 5.0.11 on 2025-03-27 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_clin_special_payment_terms_interest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('clin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.clin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_history_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
