# Generated by Django 4.2.20 on 2025-04-16 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_alter_contractsplit_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contractsplit',
            table='contracts_contractsplit',
        ),
    ]
