# Generated by Django 4.2.20 on 2025-04-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contract_plan_gross_alter_clin_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clin',
            name='plan_gross',
        ),
        migrations.RemoveField(
            model_name='clin',
            name='planned_split',
        ),
        migrations.RemoveField(
            model_name='clin',
            name='ppi_split',
        ),
        migrations.RemoveField(
            model_name='clin',
            name='ppi_split_paid',
        ),
        migrations.RemoveField(
            model_name='clin',
            name='statz_split',
        ),
        migrations.RemoveField(
            model_name='clin',
            name='statz_split_paid',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ppi_split',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='ppi_split_paid',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='statz_split',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='statz_split_paid',
        ),
    ]
