# Generated by Django 5.0.11 on 2025-02-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='business_fax',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='business_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
