# Generated by Django 4.2.20 on 2025-04-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_remove_clin_plan_gross_remove_clin_planned_split_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contract',
            name='contract_open_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contract_cancelled_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contract_open_due_idx',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='cancelled',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='open',
        ),
    ]
