# Generated by Django 4.2.20 on 2025-04-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_remove_contract_contract_open_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='prime',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='prime_po_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
