# Generated by Django 5.0.11 on 2025-02-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_supplier_business_fax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='conditional_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='probation_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='special_terms_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
