# Generated by Django 4.2.20 on 2025-04-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_contract_prime_contract_prime_po_number'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['prime'], name='contract_prime_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['prime_po_number'], name='contract_prime_po_number_idx'),
        ),
    ]
