# Generated by Django 5.0.11 on 2025-02-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_supplier_conditional_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='statz_contact_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
