# Generated by Django 5.0.11 on 2025-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_alter_acknowledgementletter_statz_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinacknowledgment',
            name='POtoQAR_Bool',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinacknowledgment',
            name='POtoQAR_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinacknowledgment',
            name='POtoQAR_User',
            field=models.TextField(blank=True, null=True),
        ),
    ]
