# Generated by Django 5.0.11 on 2025-03-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_alter_acknowledgementletter_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgementletter',
            name='statz_contact_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
