# Generated by Django 4.2.20 on 2025-04-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_contract_contract_prime_idx_and_more'),
        ('contracts', 'remove_old_payment_history'),
    ]

    operations = [
    ]
