# Generated by Django 4.2.20 on 2025-04-21 19:24

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('contracts', '0016_merge_20250421_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('payment_type', models.CharField(choices=[('contract_value', 'Contract Value'), ('plan_gross', 'Plan Gross'), ('statz_split_paid', 'STATZ Split Paid'), ('ppi_split_paid', 'PPI Split Paid'), ('item_value', 'Item Value'), ('quote_value', 'Quote Value'), ('paid_amount', 'Paid Amount'), ('wawf_payment', 'WAWF Payment'), ('special_payment_terms_interest', 'Special Payment Terms Interest')], max_length=50)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_date', models.DateField()),
                ('payment_info', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment histories',
                'ordering': ['-payment_date', '-created_on'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='contracts_p_content_1ed278_idx'), models.Index(fields=['payment_type'], name='contracts_p_payment_bf9d81_idx'), models.Index(fields=['payment_date'], name='contracts_p_payment_814b25_idx')],
            },
        ),
    ]
