# Generated by Django 5.0.11 on 2025-02-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_clinacknowledgment_potoqar_bool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinacknowledgment',
            old_name='POtoQAR_Bool',
            new_name='po_to_qar_bool',
        ),
        migrations.RenameField(
            model_name='clinacknowledgment',
            old_name='POtoQAR_Date',
            new_name='po_to_qar_date',
        ),
        migrations.RenameField(
            model_name='clinacknowledgment',
            old_name='POtoQAR_User',
            new_name='po_to_qar_user',
        ),
    ]
