# Generated by Django 5.0.11 on 2025-02-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_rename_potoqar_bool_clinacknowledgment_po_to_qar_bool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
