# Generated by Django 4.2.20 on 2025-04-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_paymenthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('contract_value', 'Contract Value'), ('plan_gross', 'Plan Gross'), ('item_value', 'Item Value'), ('quote_value', 'Quote Value'), ('paid_amount', 'Paid Amount'), ('wawf_payment', 'WAWF Payment')], max_length=50),
        ),
    ]
