# Generated by Django 4.2.20 on 2025-04-25 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0018_alter_paymenthistory_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('ship_qty', models.FloatField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=10, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('clin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='contracts.clin')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ship_date', '-created_on'],
                'indexes': [models.Index(fields=['clin'], name='clinship_clin_idx'), models.Index(fields=['ship_date'], name='clinship_date_idx'), models.Index(fields=['clin', 'ship_date'], name='clinship_clin_date_idx')],
            },
        ),
    ]
