# Generated by Django 5.0.11 on 2025-02-27 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0018_alter_supplier_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_title', models.CharField(blank=True, max_length=50, null=True)),
                ('reminder_text', models.TextField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_completed', models.BooleanField(blank=True, null=True)),
                ('reminder_completed_date', models.DateTimeField(blank=True, null=True)),
                ('clin_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='contracts.clinnote')),
                ('contract_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='contracts.contractnote')),
                ('reminder_completed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_reminders', to=settings.AUTH_USER_MODEL)),
                ('reminder_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('clin_note__isnull', True), ('contract_note__isnull', True)), models.Q(('clin_note__isnull', False), ('contract_note__isnull', True)), models.Q(('clin_note__isnull', True), ('contract_note__isnull', False)), _connector='OR'), name='reminder_single_note_constraint'),
        ),
    ]
