# Generated by Django 4.2.20 on 2025-05-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_clinshipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClinView',
        ),
        migrations.DeleteModel(
            name='NsnView',
        ),
    ]
