# Generated by Django 5.0.11 on 2025-02-28 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('contracts', '0020_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinnote',
            name='clin',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='clin_note',
        ),
        migrations.RemoveField(
            model_name='contractnote',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='contract_note',
        ),
        migrations.RemoveConstraint(
            model_name='reminder',
            name='reminder_single_note_constraint',
        ),
        migrations.AddField(
            model_name='note',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_reminders', to='contracts.note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['content_type', 'object_id'], name='contracts_n_content_1ed443_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['note'], name='contracts_r_note_id_f761cf_idx'),
        ),
        migrations.DeleteModel(
            name='ClinNote',
        ),
        migrations.DeleteModel(
            name='ContractNote',
        ),
    ]
