# Generated by Django 4.2.20 on 2025-05-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_delete_clinview_delete_nsnview'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(max_length=20)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
