# Generated by Django 5.0.11 on 2025-02-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_remove_clinnote_clin_remove_reminder_clin_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='note',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='note',
            name='modified_on',
        ),
    ]
