# Generated by Django 4.2.20 on 2025-05-28 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_folderstack'),
    ]

    operations = [
        migrations.AddField(
            model_name='foldertracking',
            name='stack_id',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='folder_tracking', to='contracts.folderstack'),
            preserve_default=True,
        ),
    ]
