# Generated by Django 4.2.25 on 2025-10-23 13:11

from django.db import migrations, models
import django.db.models.deletion


def seed_default_company(apps, schema_editor):
    Company = apps.get_model('contracts', 'Company')
    Contract = apps.get_model('contracts', 'Contract')
    Clin = apps.get_model('contracts', 'Clin')

    company, _ = Company.objects.get_or_create(
        slug='company-a',
        defaults={'name': 'Company A', 'is_active': True},
    )

    Contract.objects.filter(company__isnull=True).update(company=company)
    Clin.objects.filter(company__isnull=True).update(company=company)


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0022_foldertracking_stack_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="foldertracking",
            name="stack_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_tracking",
                to="contracts.folderstack",
            ),
        ),
        migrations.AddField(
            model_name="clin",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clins",
                to="contracts.company",
            ),
        ),
        migrations.AddField(
            model_name="contract",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contracts.company",
            ),
        ),
        migrations.RunPython(seed_default_company, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clin",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clins",
                to="contracts.company",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="contracts.company",
            ),
        ),
    ]
