# Generated by Django 5.0.11 on 2025-02-28 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_note_created_by_note_created_on_note_modified_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinacknowledgment',
            name='clin_reply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clin_acknowledgment_clin_reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinacknowledgment',
            name='po_to_qar_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clin_acknowledgment_po_to_qar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinacknowledgment',
            name='po_to_supplier_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clin_acknowledgment_po_to_supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
