# Generated by Django 5.0.11 on 2025-03-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_clinacknowledgment_clin_reply_user_and_more'),
        ('contracts', 'add_note_id_to_reminder'),
    ]

    operations = [
    ]
