# Generated by Django 5.0.11 on 2025-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_clinacknowledgment_clin_reply_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.BigIntegerField(default=10000)),
                ('tab_number', models.BigIntegerField(default=10000)),
            ],
        ),
    ]
