# Generated by Django 5.0.11 on 2025-03-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_alter_contract_contract_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clintype',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
