# Generated by Django 4.2.24 on 2025-11-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0028_supplier_allows_gsi_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='dodaac',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='allows_gsi',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('YES', 'Yes'), ('NO', 'No')], default='UNK', help_text='Whether the supplier allows GSI at facility (Unknown until confirmed).', max_length=3),
        ),
    ]
