# Generated by Django 5.0.11 on 2025-03-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_contractstatus_clin_contract_value_clin_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clin',
            name='clin_finance',
        ),
        migrations.AddField(
            model_name='contract',
            name='idiq_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.idiqcontract'),
        ),
        migrations.DeleteModel(
            name='ClinFinance',
        ),
    ]
