# Generated by Django 4.2.24 on 2025-12-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0029_supplier_dodaac_alter_supplier_allows_gsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contracts.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_for_supplier', to='contracts.contact'),
        ),
    ]
