# Generated by Django 5.0.11 on 2025-03-06 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0030_remove_clin_clin_finance_contract_idiq_contract_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IdiqContractToContract',
        ),
    ]
