# Generated by Django 4.2.25 on 2025-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0031_supplierdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='files_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
