# Generated by Django 5.0.11 on 2025-03-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_update_reminder_note_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='bid_value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
