# Generated by Django 4.2.25 on 2025-12-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_alter_supplier_files_url'),
    ]

    operations = []
