# Generated by Django 4.2.25 on 2025-12-03 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0013_alter_processclin_nsn_alter_processclin_supplier_and_more'),
        ('contracts', '0033_remove_contact_address_remove_contact_supplier_and_more'),
        ('products', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='clin',
                    name='nsn',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.nsn'),
                ),
                migrations.AlterField(
                    model_name='clin',
                    name='supplier',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
                ),
                migrations.AlterField(
                    model_name='idiqcontractdetails',
                    name='nsn',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nsn'),
                ),
                migrations.AlterField(
                    model_name='idiqcontractdetails',
                    name='supplier',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='CertificationType',
                ),
                migrations.DeleteModel(
                    name='ClassificationType',
                ),
                migrations.DeleteModel(
                    name='Contact',
                ),
                migrations.DeleteModel(
                    name='Nsn',
                ),
                migrations.DeleteModel(
                    name='Supplier',
                ),
                migrations.DeleteModel(
                    name='SupplierCertification',
                ),
                migrations.DeleteModel(
                    name='SupplierClassification',
                ),
                migrations.DeleteModel(
                    name='SupplierDocument',
                ),
                migrations.DeleteModel(
                    name='SupplierType',
                ),
            ],
            database_operations=[],
        ),
    ]
