# Generated by Django 5.0.11 on 2025-03-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0033_contract_bid_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='statz_value',
        ),
        migrations.AddField(
            model_name='clin',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='clin',
            name='uom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
