# Generated by Django 5.0.11 on 2025-03-10 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_remove_contract_statz_value_clin_price_per_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['contract'], name='clin_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['clin_type'], name='clin_type_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['supplier'], name='clin_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['nsn'], name='clin_nsn_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['special_payment_terms'], name='clin_payment_terms_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['po_number'], name='clin_po_number_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['tab_num'], name='clin_tab_num_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['due_date'], name='clin_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['supplier_due_date'], name='clin_supp_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['ship_date'], name='clin_ship_date_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['contract', 'due_date'], name='clin_contract_due_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['supplier', 'due_date'], name='clin_supp_due_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['due_date_late'], name='clin_due_late_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['supplier_due_date_late'], name='clin_supp_due_late_idx'),
        ),
        migrations.AddIndex(
            model_name='clin',
            index=models.Index(fields=['ship_date_late'], name='clin_ship_late_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['idiq_contract'], name='contract_idiq_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['canceled_reason'], name='contract_cancel_reason_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['buyer'], name='contract_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_type'], name='contract_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['sales_class'], name='contract_sales_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_number'], name='contract_number_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['po_number'], name='contract_po_number_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['tab_num'], name='contract_tab_num_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['open'], name='contract_open_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['cancelled'], name='contract_cancelled_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['due_date'], name='contract_due_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['award_date'], name='contract_award_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['assigned_user'], name='contract_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['open', 'due_date'], name='contract_open_due_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'due_date'], name='contract_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['due_date_late'], name='contract_due_late_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['reviewed'], name='contract_reviewed_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontract',
            index=models.Index(fields=['buyer'], name='idiq_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontract',
            index=models.Index(fields=['contract_number'], name='idiq_contract_num_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontract',
            index=models.Index(fields=['tab_num'], name='idiq_tab_num_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontract',
            index=models.Index(fields=['award_date'], name='idiq_award_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontract',
            index=models.Index(fields=['closed'], name='idiq_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontractdetails',
            index=models.Index(fields=['idiq_contract'], name='idiq_details_contract_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontractdetails',
            index=models.Index(fields=['nsn'], name='idiq_details_nsn_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontractdetails',
            index=models.Index(fields=['supplier'], name='idiq_details_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='idiqcontractdetails',
            index=models.Index(fields=['idiq_contract', 'nsn'], name='idiq_details_contract_nsn_idx'),
        ),
    ]
