# Generated by Django 4.2.25 on 2025-12-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0034_contract_supplier_alter_clin_nsn_alter_clin_supplier_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clin',
            table='contracts_clin',
        ),
        migrations.AlterModelTable(
            name='contract',
            table='contracts_contract',
        ),
    ]
