# Generated by Django 5.0.11 on 2025-03-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0035_clin_clin_contract_idx_clin_clin_type_idx_and_more'),
        ('contracts', 'create_clin_view'),
    ]

    operations = [
    ]
