# Generated by Django 4.2.24 on 2026-02-11 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0035_alter_clin_table_alter_contract_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='clin',
            name='log_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clin',
            name='log_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GovAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(blank=True, choices=[('PAR', 'PAR'), ('RFV', 'RFV'), ('ECP', 'ECP'), ('QN', 'QN'), ('NCR', 'NCR')], max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('request', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Technical', 'Technical'), ('Extension', 'Extension'), ('Cancellation', 'Cancellation'), ('Qty Change', 'Qty Change'), ('Litigation', 'Litigation'), ('Price', 'Price'), ('Other', 'Other')], max_length=30, null=True)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('date_closed', models.DateField(blank=True, null=True)),
                ('initiated', models.CharField(blank=True, choices=[('STATZ', 'STATZ'), ('Gov', 'Gov'), ('Supplier', 'Supplier')], max_length=20, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gov_actions', to='contracts.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gov_actions', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gov Action',
                'verbose_name_plural': 'Gov Actions',
                'db_table': 'contracts_govaction',
                'ordering': ['-date_submitted', '-created_on'],
            },
        ),
    ]
