# Generated by Django 5.0.11 on 2025-03-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0036_merge_20250310_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contract_id', models.IntegerField(null=True)),
                ('contract_number', models.CharField(max_length=25, null=True)),
                ('clin_po_num', models.CharField(max_length=10, null=True)),
                ('po_number', models.CharField(max_length=10, null=True)),
                ('po_num_ext', models.CharField(max_length=5, null=True)),
                ('tab_num', models.CharField(max_length=10, null=True)),
                ('sub_contract', models.CharField(max_length=20, null=True)),
                ('clin_type_id', models.IntegerField(null=True)),
                ('clin_type_description', models.TextField(null=True)),
                ('supplier_id', models.IntegerField(null=True)),
                ('supplier_name', models.CharField(max_length=100, null=True)),
                ('supplier_cage_code', models.CharField(max_length=10, null=True)),
                ('nsn_id', models.IntegerField(null=True)),
                ('nsn_code', models.CharField(max_length=20, null=True)),
                ('nsn_description', models.TextField(null=True)),
                ('ia', models.CharField(max_length=5, null=True)),
                ('fob', models.CharField(max_length=5, null=True)),
                ('order_qty', models.FloatField(null=True)),
                ('ship_qty', models.FloatField(null=True)),
                ('due_date', models.DateField(null=True)),
                ('due_date_late', models.BooleanField(null=True)),
                ('supplier_due_date', models.DateField(null=True)),
                ('supplier_due_date_late', models.BooleanField(null=True)),
                ('ship_date', models.DateField(null=True)),
                ('ship_date_late', models.BooleanField(null=True)),
                ('special_payment_terms_id', models.IntegerField(null=True)),
                ('special_payment_terms_code', models.CharField(max_length=5, null=True)),
                ('special_payment_terms_description', models.CharField(max_length=30, null=True)),
                ('special_payment_terms_paid', models.BooleanField(null=True)),
                ('contract_value', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('po_amount', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('created_by_id', models.IntegerField(null=True)),
                ('created_by_username', models.CharField(max_length=150, null=True)),
                ('created_on', models.DateTimeField(null=True)),
                ('modified_by_id', models.IntegerField(null=True)),
                ('modified_by_username', models.CharField(max_length=150, null=True)),
                ('modified_on', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'clin_view',
                'managed': False,
            },
        ),
    ]
