# Generated by Django 4.2.24 on 2026-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0036_gov_actions_and_log_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sharepoint_base_url',
            field=models.CharField(blank=True, help_text='SharePoint base URL down to /sites/ (e.g. https://statzcorpgcch.sharepoint.us/sites)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sharepoint_documents_path',
            field=models.CharField(blank=True, help_text='Path under Shared Documents to contract root (e.g. Statz-Public/data/V87/aFed-DOD)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sharepoint_site_name',
            field=models.CharField(blank=True, help_text='Site name after /sites/ (e.g. Statz, JVIC)', max_length=64, null=True),
        ),
    ]
