# Generated by Django 5.0.11 on 2025-03-10 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0037_clinview'),
        ('contracts', 'add_nsn_indexes'),
    ]

    operations = [
    ]
