# Generated by Django 6.0.3 on 2026-04-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_idiqcontract_max_value_min_guarantee_idiqcontractdetails_min_order_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinshipment',
            name='pod_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
