# Generated by Django 5.0.11 on 2025-03-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0038_merge_0037_clinview_add_nsn_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsnView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nsn_code', models.CharField(max_length=20, null=True)),
                ('description', models.TextField(null=True)),
                ('part_number', models.CharField(max_length=25, null=True)),
                ('revision', models.CharField(max_length=25, null=True)),
                ('notes', models.TextField(null=True)),
                ('directory_url', models.CharField(max_length=200, null=True)),
                ('clin_count', models.IntegerField(null=True)),
                ('search_vector', models.TextField(null=True)),
            ],
            options={
                'db_table': 'nsn_view',
                'managed': False,
            },
        ),
    ]
