# Generated by Django 5.0.11 on 2025-03-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0039_nsnview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='bid_value',
        ),
    ]
