# Generated by Django 6.0.3 on 2026-04-22 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0040_trackerschema_contractrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractrecord',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractrecord',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trackerschema',
            name='column_order',
            field=models.JSONField(default=list),
        ),
        migrations.AddIndex(
            model_name='contractrecord',
            index=models.Index(fields=['schema', 'is_closed'], name='contracts_c_schema__f14e8d_idx'),
        ),
    ]
