# Generated by Django 5.0.11 on 2025-03-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0040_remove_contract_bid_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clin',
            name='fob',
            field=models.CharField(blank=True, choices=[('O', 'Origin'), ('D', 'Destination')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='clin',
            name='ia',
            field=models.CharField(blank=True, choices=[('O', 'Origin'), ('D', 'Destination')], max_length=5, null=True),
        ),
    ]
