# Generated by Django 6.0.3 on 2026-04-24 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0042_contract_cancelled_by_contract_closed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('split_value', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('split_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('clin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='contracts.clin')),
            ],
            options={
                'verbose_name': 'CLIN Split',
                'verbose_name_plural': 'CLIN Splits',
                'db_table': 'contracts_clinsplit',
                'ordering': ['company_name'],
            },
        ),
        migrations.DeleteModel(
            name='ContractSplit',
        ),
    ]
