# Generated by Django 5.0.11 on 2025-03-11 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0042_contract_assigned_user_tmp_contract_reviewed_by_tmp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='assigned_user_tmp',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='reviewed_by_tmp',
        ),
        migrations.AlterField(
            model_name='contract',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_assigned_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_reviewed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
