# Generated by Django 6.0.3 on 2026-04-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0043_replace_contractsplit_with_clinsplit"),
    ]

    operations = [
        migrations.AddField(
            model_name="idiqcontract",
            name="files_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
