# Generated by Django 5.0.11 on 2025-03-11 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0043_remove_contract_assigned_user_tmp_and_more'),
    ]

    operations = [
    ]
