# Generated by Django 5.0.14 on 2026-04-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_idiqcontract_files_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govaction',
            name='action',
            field=models.CharField(blank=True, choices=[('PAR', 'PAR'), ('RFV', 'RFV'), ('ECP', 'ECP'), ('QN', 'QN'), ('NCR', 'NCR'), ('SOW', 'SOW')], max_length=20, null=True),
        ),
    ]
