# Generated by Django 5.0.11 on 2025-03-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0044_auto_20250311_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clin',
            old_name='po_amount',
            new_name='clin_value',
        ),
    ]
