# Generated by Django 5.0.11 on 2025-03-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0046_clin_ppi_split_clin_ppi_split_paid_clin_statz_split_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clin',
            old_name='sub_contract',
            new_name='item_number',
        ),
        migrations.RenameField(
            model_name='clin',
            old_name='contract_value',
            new_name='item_value',
        ),
        migrations.AddField(
            model_name='clin',
            name='item_type',
            field=models.CharField(blank=True, choices=[('P', 'Production'), ('G', 'GFAT'), ('C', 'CFAT'), ('L', 'PLT')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='planned_split',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ppi_split',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='ppi_split_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='statz_split',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='statz_split_paid',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
