# Generated by Django 5.0.14 on 2026-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0046_remove_contract_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pr_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PR Number'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('contract_value', 'Contract Value'), ('plan_gross', 'Plan Gross'), ('item_value', 'Item Value'), ('quote_value', 'Quote Value'), ('paid_amount', 'Paid Amount'), ('wawf_payment', 'Customer Payment')], max_length=50),
        ),
    ]
