# Generated by Django 5.0.11 on 2025-03-13 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0047_rename_sub_contract_clin_item_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clin',
            name='item_type',
            field=models.CharField(blank=True, choices=[('P', 'Production'), ('G', 'GFAT'), ('C', 'CFAT'), ('L', 'PLT'), ('M', 'Miscellaneous')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Expedite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated', models.BooleanField(blank=True, default=False, null=True)),
                ('initiateddate', models.DateTimeField(blank=True, null=True)),
                ('successful', models.BooleanField(blank=True, default=False, null=True)),
                ('successfuldate', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(blank=True, default=False, null=True)),
                ('useddate', models.DateTimeField(blank=True, null=True)),
                ('clin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.clin')),
                ('initiatedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedite_initiated', to=settings.AUTH_USER_MODEL)),
                ('successfulby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedite_successful', to=settings.AUTH_USER_MODEL)),
                ('usedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedite_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['clin'], name='contracts_e_clin_id_474b60_idx')],
            },
        ),
    ]
