# Generated by Django 5.0.11 on 2025-03-13 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0048_alter_clin_item_type_expedite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='expedite',
            name='contracts_e_clin_id_474b60_idx',
        ),
        migrations.RemoveField(
            model_name='expedite',
            name='clin',
        ),
        migrations.AddField(
            model_name='expedite',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contracts.contract'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='expedite',
            index=models.Index(fields=['contract'], name='contracts_e_contrac_263d07_idx'),
        ),
    ]
