# Generated by Django 5.0.11 on 2025-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0049_remove_expedite_contracts_e_clin_id_474b60_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clin',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
    ]
