# Generated by Django 5.0.11 on 2025-03-17 14:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0050_clin_unit_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('stack', models.CharField(choices=[('1 - COS', 'COS'), ('2 - PACK', 'PACK'), ('3 - PROCESS', 'PROCESS'), ('4 - W4QAR', 'W4QAR'), ('5 - W4BOL', 'W4BOL'), ('6 - W4POS', 'W4POS'), ('7 - W4POD', 'W4POD'), ('8 - W4PAY', 'W4PAY'), ('9 - QSIGN', 'QSIGN'), ('10 - PAID', 'PAID')], max_length=20)),
                ('partial', models.CharField(blank=True, max_length=20, null=True)),
                ('rts_email', models.BooleanField(default=False)),
                ('qb_inv', models.CharField(blank=True, max_length=10, null=True)),
                ('wawf', models.BooleanField(default=False)),
                ('wawf_qar', models.BooleanField(default=False)),
                ('vsm_scn', models.CharField(blank=True, max_length=20, null=True)),
                ('sir_scn', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking', models.CharField(blank=True, max_length=20, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=20, null=True)),
                ('sort_data', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('highlight', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_tracking_added', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_tracking_closed', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_tracking', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['contract'], name='fld_track_contract_idx'), models.Index(fields=['stack'], name='fld_track_stack_idx'), models.Index(fields=['closed'], name='fld_track_closed_idx'), models.Index(fields=['date_added'], name='fld_track_added_idx'), models.Index(fields=['date_closed'], name='fld_track_dclosed_idx'), models.Index(fields=['contract', 'stack'], name='fld_track_con_stack_idx'), models.Index(fields=['closed', 'stack'], name='fld_track_cls_stack_idx')],
            },
        ),
    ]
