# Generated by Django 5.0.14 on 2026-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0052_clinshipment_financial_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinshipment',
            name='item_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contract value for this shipment (ship_qty × unit_price). Auto-calculated but editable.', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='clinshipment',
            name='quote_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Supplier cost for this shipment (ship_qty × price_per_unit). Auto-calculated but editable.', max_digits=19, null=True),
        ),
    ]
