# Generated by Django 5.0.14 on 2026-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0053_alter_clinshipment_item_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clin',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clin',
            name='wawf_recieved',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinacknowledgment',
            name='clin_reply_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinacknowledgment',
            name='po_to_qar_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clinacknowledgment',
            name='po_to_supplier_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='assigned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_canceled',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractrecord',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expedite',
            name='initiateddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedite',
            name='successfuldate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expedite',
            name='useddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foldertracking',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='foldertracking',
            name='date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='idiqcontract',
            name='award_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
