# Generated by Django 6.0.3 on 2026-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0055_clinsplit_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiqcontract',
            name='option_length',
            field=models.IntegerField(blank=True, help_text='Total option period length in months (e.g. 3 one-year options = 36).', null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('contract_value', 'Contract Value'), ('plan_gross', 'Plan Gross'), ('item_value', 'Item Value'), ('quote_value', 'Quote Value'), ('paid_amount', 'Paid Amount'), ('wawf_payment', 'Customer Payment'), ('partial_item_value', 'Partial Item Value'), ('partial_quote_value', 'Partial Quote Value'), ('partial_paid_amount', 'Partial Paid Amount'), ('partial_wawf_payment', 'Partial Customer Payment')], max_length=50),
        ),
    ]
