# Generated by Django 6.0.3 on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0056_idiq_option_length_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clin',
            name='pod_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
