# Generated by Django 6.0.3 on 2026-05-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0058_add_note_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clin',
            name='item_type',
            field=models.CharField(blank=True, choices=[('P', 'Production'), ('G', 'GFAT'), ('C', 'CFAT'), ('L', 'PLT'), ('M', 'Miscellaneous'), ('Q', 'QN'), ('D', 'PQDR')], max_length=20, null=True),
        ),
    ]
