# Generated by Django 6.0.3 on 2026-05-11 18:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0059_add_qn_pqdr_clin_item_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='contracts.contract')),
                ('from_status', models.ForeignKey(blank=True, help_text='Null for the initial creation row.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contracts.contractstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contracts.contractstatus')),
            ],
            options={
                'verbose_name': 'Contract Status History',
                'verbose_name_plural': 'Contract Status History',
                'db_table': 'contracts_contractstatushistory',
                'ordering': ['-changed_at', '-id'],
                'indexes': [models.Index(fields=['contract', '-changed_at'], name='csh_contract_changed_at_idx')],
            },
        ),
    ]
