# Generated by Django 6.0.3 on 2026-05-12 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0061_backfill_contract_status_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.CreateModel(
            name='DfasImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('row_count', models.IntegerField(default=0)),
                ('imported_count', models.IntegerField(default=0)),
                ('skipped_count', models.IntegerField(default=0)),
                ('duplicate_count', models.IntegerField(default=0)),
                ('unmatched_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded (awaiting review)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='uploaded', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dfas_import_batches', to='contracts.company')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DFAS Import Batch',
                'verbose_name_plural': 'DFAS Import Batches',
                'db_table': 'contracts_dfasimportbatch',
                'ordering': ['-uploaded_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DfasImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_contract_no', models.CharField(blank=True, default='', max_length=50)),
                ('raw_call_no', models.CharField(blank=True, default='', max_length=50)),
                ('raw_clin', models.CharField(blank=True, default='', max_length=20)),
                ('raw_voucher_no', models.CharField(blank=True, default='', max_length=50)),
                ('raw_invoice_no', models.CharField(blank=True, default='', max_length=50)),
                ('raw_payment_date', models.DateField(blank=True, null=True)),
                ('raw_check_eft_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('raw_data', models.JSONField(default=dict, help_text='The full DFAS row as parsed (key/value of all columns) for audit + future use.')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('matched', 'Matched (ready to import)'), ('clin_missing', 'Contract matched, CLIN not found'), ('contract_missing', 'No contract match'), ('duplicate', 'Duplicate (previously imported)'), ('skipped', 'Skipped by user'), ('imported', 'Imported'), ('error', 'Error')], default='pending', max_length=20)),
                ('match_notes', models.TextField(blank=True, default='', help_text="Human-readable notes about how the row was matched (or why it wasn't).")),
                ('error_message', models.TextField(blank=True, default='', help_text="Set when status='error'.")),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('resolved_on', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='contracts.dfasimportbatch')),
                ('matched_clin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contracts.clin')),
                ('matched_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contracts.contract')),
                ('matched_idiq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contracts.idiqcontract')),
                ('payment_history', models.ForeignKey(blank=True, help_text='The PaymentHistory row this DFAS row was imported as (null until imported).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contracts.paymenthistory')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DFAS Import Row',
                'verbose_name_plural': 'DFAS Import Rows',
                'db_table': 'contracts_dfasimportrow',
                'ordering': ['batch', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dfasimportbatch',
            index=models.Index(fields=['company', '-uploaded_at'], name='dfas_batch_co_uploaded_idx'),
        ),
        migrations.AddIndex(
            model_name='dfasimportbatch',
            index=models.Index(fields=['status'], name='dfas_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dfasimportrow',
            index=models.Index(fields=['batch', 'status'], name='dfas_row_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dfasimportrow',
            index=models.Index(fields=['raw_voucher_no', 'raw_invoice_no', 'raw_clin'], name='dfas_row_dedup_idx'),
        ),
        migrations.AddIndex(
            model_name='dfasimportrow',
            index=models.Index(fields=['status'], name='dfas_row_status_idx'),
        ),
    ]
