# Generated by Django 6.0.3 on 2026-05-14 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0064_paymenthistory_packaging_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinReclassificationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('packaging', 'Contract Packaging'), ('finance_line', 'Contract Finance Line'), ('partial_shipment', 'Partial Shipment'), ('deleted', 'Deleted (Garbage Row)')], max_length=20)),
                ('staged_data', models.JSONField(default=dict, help_text='Destination-specific field values entered by the user.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contracts.clin')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clin_reclassification_drafts', to='contracts.contract')),
                ('parent_clin', models.ForeignKey(blank=True, help_text='For partial_shipment destination: the Clin this partial belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contracts.clin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_clinreclassificationdraft',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='clinrecdraft_user_idx'), models.Index(fields=['contract', 'user'], name='clinrecdraft_contract_user_idx')],
                'constraints': [models.UniqueConstraint(fields=('contract', 'user', 'clin'), name='unique_draft_per_clin_per_user')],
            },
        ),
        migrations.CreateModel(
            name='ClinReclassificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_clin_id', models.IntegerField(help_text='The ID of the Clin row that was reclassified. Row no longer exists.')),
                ('original_data', models.JSONField(help_text='Full snapshot of the original Clin row data, including all fields.')),
                ('destination_type', models.CharField(choices=[('packaging', 'Contract Packaging'), ('finance_line', 'Contract Finance Line'), ('partial_shipment', 'Partial Shipment'), ('deleted', 'Deleted (Garbage Row)')], max_length=20)),
                ('destination_id', models.IntegerField(blank=True, help_text="ID of the new row created (ContractPackaging, ContractFinanceLine, or ClinShipment). Null for 'deleted'.", null=True)),
                ('notes_migrated_count', models.IntegerField(default=0, help_text='Number of Note rows migrated from the original Clin to the contract.')),
                ('payment_history_deleted_count', models.IntegerField(default=0, help_text='Number of PaymentHistory rows deleted with the original Clin.')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clin_reclassification_logs', to='contracts.contract')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_clinreclassificationlog',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['contract', '-performed_at'], name='clinreclog_contract_idx'), models.Index(fields=['performed_by', '-performed_at'], name='clinreclog_user_idx')],
            },
        ),
    ]
