# Generated by Django 6.0.3 on 2026-05-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0066_clinshipment_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('body', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_snippets', to='contracts.company')),
            ],
            options={
                'verbose_name': 'PO Snippet',
                'verbose_name_plural': 'PO Snippets',
                'ordering': ['category', 'sort_order', 'title'],
            },
        ),
    ]
