# Generated by Django 5.0.14 on 2026-05-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0067_add_po_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clin',
            name='item_type',
            field=models.CharField(blank=True, choices=[('P', 'Production'), ('G', 'GFAT'), ('C', 'CFAT'), ('L', 'PLT'), ('M', 'Miscellaneous'), ('Q', 'QN / PQDR'), ('D', 'PQDR')], max_length=20, null=True),
        ),
    ]
