# Generated by Django 6.0.3 on 2026-05-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0072_acknowledgementletter_is_user_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiqcontractdetails',
            name='supplier_part_number',
            field=models.CharField(blank=True, help_text="Supplier's part number for this NSN (e.g. SMTC-18). Parsed from IDIQ award document or entered manually.", max_length=100, null=True),
        ),
    ]
