# Generated by Django 5.0.14 on 2026-06-01 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0073_idiqcontractdetails_add_supplier_part_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractLevelCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billed_paid_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Actual billed/paid amount. Leave blank until invoice is settled.', max_digits=10, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_charges', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts_contractlevelcharge',
                'ordering': ['created_on'],
            },
        ),
    ]
