# Generated by Django 5.0.14 on 2026-06-04 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0074_add_contractlevelcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='dfasimportrow',
            name='matched_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contracts.clinshipment'),
        ),
        migrations.AlterField(
            model_name='dfasimportrow',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('matched', 'Matched (ready to import)'), ('clin_missing', 'Contract matched, CLIN not found'), ('contract_missing', 'No contract match'), ('shipment_missing', 'Shipment selection needed'), ('duplicate', 'Duplicate (previously imported)'), ('skipped', 'Skipped by user'), ('imported', 'Imported'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
