# Generated by Django 6.0.3 on 2026-06-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0075_dfasimportrow_matched_shipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfasimportrow',
            name='matched_shipment',
            field=models.ForeignKey(blank=True, help_text='The ClinShipment this DFAS payment is applied to. Auto-assigned when possible. Null for legacy CLINs without shipments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contracts.clinshipment'),
        ),
    ]
