# Generated by Django 6.0.3 on 2026-06-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0076_dfas_import_row_matched_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiqcontract',
            name='alert_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
