# Generated by Django 6.0.3 on 2026-06-05 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0077_add_idiqcontract_alert_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpaymentterms',
            name='net_days',
            field=models.IntegerField(blank=True, help_text="Number of days after the supplier ship date that payment is due. 0 = due on ship (COD/COS). Leave blank if this term has no fixed day count  rows using it will be flagged 'no terms' in the payment forecast rather than given a fabricated due date.", null=True),
        ),
        migrations.CreateModel(
            name='ShipmentPaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('planned_pay_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('on_hold', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plan', to='contracts.clinshipment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
