# Generated by Django 6.0.3 on 2026-06-08 18:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0078_specialpaymentterms_net_days_shipmentpaymentplan'),
        ('suppliers', '0008_remove_supplier_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_po_generator',
            field=models.BooleanField(default=False, help_text="When True, the 'Generate PO' button appears on the contract management page for this company. Leave False for companies that issue purchase orders through QuickBooks or another external system."),
        ),
        migrations.CreateModel(
            name='CompanyPOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_to_name', models.CharField(blank=True, default='', max_length=150)),
                ('ship_to_attn', models.CharField(blank=True, default='', max_length=150)),
                ('ship_to_title', models.CharField(blank=True, default='', max_length=100)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=200)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('zip', models.CharField(blank=True, default='', max_length=15)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('cage_code', models.CharField(blank=True, default='', max_length=20)),
                ('default_footer', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='po_profile', to='contracts.company')),
            ],
            options={
                'verbose_name': 'Company PO Profile',
                'verbose_name_plural': 'Company PO Profiles',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(blank=True, default='', help_text='Editable PO number including any revision suffix, e.g. J00121A.', max_length=30)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='contracts.company')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='contracts.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-modified_on'],
            },
        ),
        migrations.CreateModel(
            name='POLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('activity', models.TextField(blank=True, default='')),
                ('qty', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='contracts.purchaseorder')),
            ],
            options={
                'verbose_name': 'PO Line Item',
                'verbose_name_plural': 'PO Line Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
