# Generated by Django 6.0.3 on 2026-06-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0079_company_enable_po_generator_companypoprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypoprofile',
            name='contact_note',
            field=models.CharField(blank=True, default='', help_text="Optional extra line in the 'Per Contract' contact block (e.g. 'for shipping instructions').", max_length=200),
        ),
        migrations.AddField(
            model_name='companypoprofile',
            name='letterhead_html',
            field=models.TextField(blank=True, default='', help_text='Trusted, admin-authored HTML for the printed letterhead block (company legal name, CAGE codes, address, parent companies, phones, tagline). Rendered as-is next to the company logo.'),
        ),
    ]
