# Generated by Django 6.0.3 on 2026-06-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0080_companypoprofile_contact_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idiqcontract',
            name='company',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='idiq_contracts', to='contracts.company'),
        ),
    ]
