# Generated by Django 5.0.14 on 2026-06-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0081_idiqcontract_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_contact',
            field=models.TextField(blank=True, default='', help_text='Multi-line contact block: attn, title, note, phone, email.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='ship_to_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
