# Generated by Django 5.0.14 on 2026-06-09 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0082_purchaseorder_ship_to_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('total_partner_rows', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('amount_discrepancy_count', models.IntegerField(default=0)),
                ('payment_discrepancy_count', models.IntegerField(default=0)),
                ('missing_in_statz_count', models.IntegerField(default=0)),
                ('missing_in_partner_count', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_reconciliations', to='contracts.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Reconciliation',
                'verbose_name_plural': 'Partner Reconciliations',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerReconciliationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_contract_number', models.CharField(blank=True, default='', max_length=100)),
                ('partner_po_number', models.CharField(blank=True, default='', max_length=100)),
                ('partner_award_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('partner_commission_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Value from the partner's commission column (e.g. MSC/PPI column)", max_digits=19, null=True)),
                ('partner_tab', models.CharField(blank=True, default='', max_length=50)),
                ('statz_split_value', models.DecimalField(blank=True, decimal_places=2, help_text='SUM of ClinSplit.split_value for this partner on this contract', max_digits=19, null=True)),
                ('statz_split_paid', models.DecimalField(blank=True, decimal_places=2, help_text='SUM of ClinSplit.split_paid for this partner on this contract', max_digits=19, null=True)),
                ('status', models.CharField(choices=[('match', 'Match'), ('amount_discrepancy', 'Amount Discrepancy'), ('payment_discrepancy', 'Payment Discrepancy'), ('missing_in_statz', 'Missing in STATZ'), ('missing_in_partner', 'Missing in Partner Report')], max_length=30)),
                ('amount_variance', models.DecimalField(blank=True, decimal_places=2, help_text='partner_commission_amount minus statz_split_value. Positive = partner claims more than we have. Negative = we have more.', max_digits=19, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_rows', to='contracts.contract')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='contracts.partnerreconciliation')),
            ],
            options={
                'verbose_name': 'Partner Reconciliation Row',
                'verbose_name_plural': 'Partner Reconciliation Rows',
                'ordering': ['status', 'partner_contract_number'],
            },
        ),
    ]
