# Generated by Django 6.0.3 on 2026-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0083_partner_reconciliation_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypoprofile',
            name='signature_image_base64',
            field=models.TextField(blank=True, default='', help_text='Base64-encoded data URL of the company signature image (e.g. data:image/png;base64,...). Rendered on printed POs. Set via the PO editor page signature modal or admin.'),
        ),
    ]
