# Generated by Django 6.0.3 on 2026-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0084_companypoprofile_signature_image_base64'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerreconciliationrow',
            name='contract_date_closed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnerreconciliationrow',
            name='contract_status_at_upload',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='govaction',
            name='action',
            field=models.CharField(blank=True, choices=[('PAR', 'PAR'), ('RFV', 'RFV'), ('ECP', 'ECP'), ('QN', 'QN'), ('NCR', 'NCR'), ('SOW', 'SOW'), ('SWO', 'SWO')], max_length=20, null=True),
        ),
    ]
