# Generated by Django 6.0.3 on 2026-06-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0085_reconciliation_contract_snapshot'),
        ('suppliers', '0008_remove_supplier_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractlevelcharge',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Supplier invoice number for this charge.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contractlevelcharge',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date the charge was paid.', null=True),
        ),
        migrations.AddField(
            model_name='contractlevelcharge',
            name='supplier',
            field=models.ForeignKey(blank=True, help_text='Optional. Populate only when this charge is paid to a different supplier than the main contract supplier (e.g. a packhouse for packaging fees).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='level_charges', to='suppliers.supplier'),
        ),
    ]
