# Generated by Django 6.0.3 on 2026-06-26 13:23

from django.db import migrations, models


DESTINATION_TYPE_FIELD = models.CharField(
    choices=[
        ('contract_level_charge', 'Contract Level Cost'),
        ('finance_line', 'Contract Finance Line'),
        ('partial_shipment', 'Partial Shipment'),
        ('deleted', 'Deleted (Garbage Row)'),
    ],
    max_length=25,
)


def _alter_destination_type_max_length(apps, schema_editor):
    """
    django-mssql-backend raises FieldDoesNotExist on AlterField when the model
    has indexes with descending columns (e.g. fields=['user', '-updated_at']).
    Use raw T-SQL for SQL Server; SQLite does not enforce CharField max_length.
    """
    if schema_editor.connection.vendor != 'microsoft':
        return
    schema_editor.execute(
        "ALTER TABLE contracts_clinreclassificationdraft "
        "ALTER COLUMN destination_type NVARCHAR(25) NOT NULL"
    )
    schema_editor.execute(
        "ALTER TABLE contracts_clinreclassificationlog "
        "ALTER COLUMN destination_type NVARCHAR(25) NOT NULL"
    )


def _reverse_destination_type_max_length(apps, schema_editor):
    if schema_editor.connection.vendor != 'microsoft':
        return
    schema_editor.execute(
        "ALTER TABLE contracts_clinreclassificationdraft "
        "ALTER COLUMN destination_type NVARCHAR(20) NOT NULL"
    )
    schema_editor.execute(
        "ALTER TABLE contracts_clinreclassificationlog "
        "ALTER COLUMN destination_type NVARCHAR(20) NOT NULL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0086_contractlevelcharge_supplier_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='clinreclassificationdraft',
                    name='destination_type',
                    field=DESTINATION_TYPE_FIELD,
                ),
                migrations.AlterField(
                    model_name='clinreclassificationlog',
                    name='destination_type',
                    field=DESTINATION_TYPE_FIELD,
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _alter_destination_type_max_length,
                    _reverse_destination_type_max_length,
                ),
            ],
        ),
    ]
