# Generated by Django 6.0.3 on 2026-06-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0087_clin_reclassification_destination_type_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractlevelcharge',
            name='action_type',
            field=models.CharField(
                choices=[('charge', 'Charge'), ('advance', 'CIA Advance')],
                default='charge',
                help_text="'charge' deducts from adj_gross. 'advance' is a CIA pre-payment tracked separately.",
                max_length=20,
            ),
        ),
    ]
