# Generated by Django 6.0.3 on 2026-07-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0088_contractlevelcharge_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='cmmc_l1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='cmmc_l2_c3pao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='cmmc_l2_sa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='cmmc_l3',
            field=models.BooleanField(default=False),
        ),
    ]
