# Generated by Django 5.0.14 on 2026-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0089_contract_cmmc_l1_contract_cmmc_l2_c3pao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractlevelcharge',
            name='action_type',
            field=models.CharField(choices=[('charge', 'Charge'), ('advance', 'CIA Advance')], default='charge', help_text="'charge' is a misc contract-level cost (e.g. GSI Fee, Freight). 'advance' is a CIA pre-payment to the supplier. Both deduct from adj_gross once billed_paid_amount is set — see Contract.adjusted_gross.", max_length=20),
        ),
    ]
