# Generated by Django 6.0.3 on 2026-08-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0090_alter_contractlevelcharge_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govaction',
            name='action',
            field=models.CharField(blank=True, choices=[('PAR', 'PAR'), ('RFV', 'RFV'), ('ECP', 'ECP'), ('QN', 'QN'), ('NCR', 'NCR'), ('SWO', 'SWO'), ('WAV', 'WAV')], max_length=20, null=True),
        ),
    ]
