# Generated by Django 6.0.3 on 2026-08-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0091_alter_govaction_action_wav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='govaction',
            name='action',
            field=models.CharField(blank=True, choices=[('PAR', 'PAR'), ('RFV', 'RFV'), ('ECP', 'ECP'), ('QN', 'QN'), ('NCR', 'NCR'), ('SWO', 'SWO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='govaction',
            name='request',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Technical', 'Technical'), ('Extension', 'Extension'), ('Cancellation', 'Cancellation'), ('Qty Change', 'Qty Change'), ('Litigation', 'Litigation'), ('Price', 'Price'), ('Waiver', 'Waiver'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
