# Generated by Django 6.0.3 on 2026-08-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0092_alter_govaction_waiver_request'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clin',
            name='clin_due_late_idx',
        ),
        migrations.RemoveIndex(
            model_name='clin',
            name='clin_supp_due_late_idx',
        ),
        migrations.RemoveIndex(
            model_name='clin',
            name='clin_ship_late_idx',
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contract_due_late_idx',
        ),
        migrations.RemoveField(
            model_name='clin',
            name='due_date_late',
        ),
        migrations.RemoveField(
            model_name='clin',
            name='ship_date_late',
        ),
        migrations.RemoveField(
            model_name='clin',
            name='supplier_due_date_late',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='due_date_late',
        ),
    ]
