# Generated by Django 6.0.3 on 2026-09-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0095_contractlogexportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='solicitation_type',
            field=models.CharField(blank=True, default='SDVOSB', max_length=50, null=True),
        ),
    ]
