# Generated by Django 4.2.30 on 2026-10-01 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0098_folder_scan_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scannedfolder',
            new_name='contracts_s_run_id_0e0db4_idx',
            old_name='contracts_sc_run_id_6a8f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='scannedfolder',
            new_name='contracts_s_run_id_93de4e_idx',
            old_name='contracts_sc_run_id_9c4e1a_idx',
        ),
    ]
