# Generated by Django 4.2.30 on 2026-10-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0099_rename_contracts_sc_run_id_6a8f2d_idx_contracts_s_run_id_0e0db4_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderscanrun',
            name='db_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='deleted_seen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='delta_link',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='delta_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='files_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='folders_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='folders_changed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='folders_in_scope',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='folders_removed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='graph_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='items_seen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folderscanrun',
            name='scan_mode',
            field=models.CharField(blank=True, choices=[('full', 'Full'), ('incremental', 'Incremental')], default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='scannedfolder',
            name='in_scope',
            field=models.BooleanField(default=True),
        ),
    ]
