# Generated by Django 6.0.3 on 2026-10-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0100_folderscanrun_db_seconds_folderscanrun_deleted_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='extension_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='original_reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='preset_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
