# Generated by Django 6.0.3 on 2026-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0101_reminder_extension_and_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderscanrun',
            name='idiq_drive_ids_written',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idiqcontract',
            name='sharepoint_drive_item_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
