# Generated by Django 4.2.25 on 2025-11-04 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_health', models.FloatField(default=30.0)),
                ('speed', models.FloatField(default=1.0, help_text='Tiles per second')),
                ('bounty', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width_tiles', models.IntegerField(default=30)),
                ('height_tiles', models.IntegerField(default=20)),
                ('start_money', models.IntegerField(default=200)),
                ('start_lives', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='TowerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=50)),
                ('damage', models.FloatField(default=5.0)),
                ('range', models.FloatField(default=3.0, help_text='Range in tiles')),
                ('fire_rate', models.FloatField(default=1.0, help_text='Shots per second')),
            ],
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='td_now.map')),
            ],
            options={
                'ordering': ['wave_number'],
            },
        ),
        migrations.CreateModel(
            name='WaveEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('spawn_interval', models.FloatField(default=1.0, help_text='Seconds between spawns')),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_now.enemytype')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_enemies', to='td_now.wave')),
            ],
        ),
        migrations.CreateModel(
            name='PathNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_nodes', to='td_now.map')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='BuildSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_spots', to='td_now.map')),
            ],
        ),
    ]
