# Generated by Django 4.2.25 on 2025-11-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_now', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towertype',
            name='area_additional_targets',
            field=models.IntegerField(default=0, help_text='Number of extra enemies hit around the primary'),
        ),
        migrations.AddField(
            model_name='towertype',
            name='area_damage_ratio',
            field=models.FloatField(default=0.75, help_text='Damage multiplier for additional targets (0..1)'),
        ),
        migrations.AddField(
            model_name='towertype',
            name='area_range',
            field=models.FloatField(default=1.0, help_text='Radius in tiles around primary for additional targets'),
        ),
    ]
