# Generated by Django 4.2.25 on 2025-11-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td_now', '0002_towertype_area_additional_targets_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('damage_multiplier', models.FloatField(default=1.0, help_text='Damage is base damage * damage_multiplier')),
                ('cost_multiplier', models.FloatField(default=1.0, help_text='Cost for this level relative to base cost')),
                ('aoe_additional_targets', models.IntegerField(default=0)),
                ('aoe_damage_ratio', models.FloatField(default=0.75)),
                ('aoe_range', models.FloatField(default=1.0)),
                ('aoe2_additional_targets', models.IntegerField(default=0)),
                ('aoe2_damage_ratio', models.FloatField(default=0.25)),
                ('aoe2_range', models.FloatField(default=0.0)),
                ('tower_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='td_now.towertype')),
            ],
            options={
                'ordering': ['tower_type', 'level_number'],
                'unique_together': {('tower_type', 'level_number')},
            },
        ),
    ]
