# Generated by Django 4.2.25 on 2025-11-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_now', '0003_towerlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerlevel',
            name='fire_rate_multiplier',
            field=models.FloatField(default=1.0, help_text='Fire rate is base fire_rate * fire_rate_multiplier'),
        ),
        migrations.AddField(
            model_name='towerlevel',
            name='range_multiplier',
            field=models.FloatField(default=1.0, help_text='Range is base range * range_multiplier'),
        ),
        migrations.AddField(
            model_name='towertype',
            name='growth_cost_mult',
            field=models.FloatField(default=1.1, help_text='Per-level cost growth multiplier (e.g., 1.10 = +10%)'),
        ),
        migrations.AddField(
            model_name='towertype',
            name='growth_damage_mult',
            field=models.FloatField(default=1.5, help_text='Per-level damage growth multiplier'),
        ),
        migrations.AddField(
            model_name='towertype',
            name='growth_fire_rate_mult',
            field=models.FloatField(default=1.0, help_text='Per-level fire-rate growth multiplier'),
        ),
        migrations.AddField(
            model_name='towertype',
            name='growth_range_mult',
            field=models.FloatField(default=1.0, help_text='Per-level range growth multiplier'),
        ),
    ]
