# Generated by Django 4.2.25 on 2025-11-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('td_now', '0004_towerlevel_fire_rate_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_money', models.IntegerField(default=200)),
                ('start_lives', models.IntegerField(default=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField()),
                ('use_map_waves', models.BooleanField(default=False)),
                ('waves_to_play', models.IntegerField(default=0, help_text='0 = all waves when using map waves')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='td_now.campaign')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_now.map')),
            ],
            options={
                'ordering': ['campaign', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='StageWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.IntegerField()),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='td_now.campaignstage')),
            ],
            options={
                'ordering': ['stage', 'wave_number'],
            },
        ),
        migrations.CreateModel(
            name='StageWaveGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('spawn_interval', models.FloatField(default=1.0)),
                ('start_delay', models.FloatField(default=0.0, help_text='Seconds to wait before this group begins spawning')),
                ('enemy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='td_now.enemytype')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='td_now.stagewave')),
            ],
            options={
                'ordering': ['wave', 'order_index'],
            },
        ),
    ]
