# Generated by Django 4.2.25 on 2025-11-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_now', '0005_campaign_campaignstage_stagewave_stagewavegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignstage',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaignstage',
            name='start_lives_override',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignstage',
            name='start_money_override',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
