# Generated by Django 4.2.25 on 2025-11-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('td_now', '0006_campaignstage_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemytype',
            name='icon_color',
            field=models.CharField(default='#f87171', max_length=7),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='icon_hit_color',
            field=models.CharField(blank=True, default='#fca5a5', max_length=7),
        ),
        migrations.AddField(
            model_name='enemytype',
            name='icon_shape',
            field=models.CharField(default='circle', max_length=20),
        ),
        migrations.AddField(
            model_name='towertype',
            name='beam_color',
            field=models.CharField(blank=True, default='#a7f3d0', max_length=7),
        ),
        migrations.AddField(
            model_name='towertype',
            name='beam_dash',
            field=models.CharField(blank=True, default='', help_text='Comma-separated dash pattern, e.g., "6,6"', max_length=50),
        ),
        migrations.AddField(
            model_name='towertype',
            name='beam_width',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='towertype',
            name='icon_blink_color',
            field=models.CharField(blank=True, default='#93c5fd', max_length=7),
        ),
        migrations.AddField(
            model_name='towertype',
            name='icon_color',
            field=models.CharField(default='#60a5fa', max_length=7),
        ),
        migrations.AddField(
            model_name='towertype',
            name='icon_shape',
            field=models.CharField(default='square', max_length=20),
        ),
    ]
