"""
Baseline for the dibbs app.

The DIBBS data models (solicitations, lines, approved sources, awards, CAGE and
SAM reference tables, notices, competitor intel) previously lived in the
`sales` app. They moved here with their tables untouched -- same table names,
same data -- and the rest of `sales` (quoting workflow) was deleted.

`replaces` lists every historical `sales` migration. On a database where they
are all applied (every existing environment), Django marks this migration
applied without running it, so nothing is created or altered. On a fresh
database (CI, new dev box) it runs and builds the tables from scratch, plus the
non-Django objects the old chain installed (see dibbs/db_objects.py).

Never edit `replaces`, and never delete the `sales` rows in django_migrations:
Django uses them to recognise this migration as already applied.
"""
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from dibbs import db_objects


def seed_check_dibbs_notices_task(apps, schema_editor):
    ScheduledTask = apps.get_model("core", "ScheduledTask")
    ScheduledTask.objects.get_or_create(
        name="check_dibbs_notices",
        defaults={
            "interval_minutes": 1440,
            "run_order": 7,
            "is_enabled": True,
            "is_running": False,
            "freeze_count": 0,
            "last_run_at": None,
        },
    )


def unseed_check_dibbs_notices_task(apps, schema_editor):
    ScheduledTask = apps.get_model("core", "ScheduledTask")
    ScheduledTask.objects.filter(name="check_dibbs_notices").delete()


class Migration(migrations.Migration):

    initial = True

    replaces = [
        ('sales', '0001_initial'),
        ('sales', '0002_suppliermatch_match_score_suppliernsn_last_synced_and_more'),
        ('sales', '0003_add_solicitation_bucket'),
        ('sales', '0004_rfq_extra_fields_and_cage_smtp'),
        ('sales', '0005_bq_raw_columns_and_bid_fields'),
        ('sales', '0006_add_hubzone_requested_by'),
        ('sales', '0007_add_importjob'),
        ('sales', '0008_add_dibbs_award'),
        ('sales', '0009_email_template'),
        ('sales', '0010_suppliermatch_manual_method'),
        ('sales', '0011_companycage_imap_fields_and_inboxemail'),
        ('sales', '0012_companycage_imap_oauth2_fields'),
        ('sales', '0013_companycage_imap_oauth_cloud'),
        ('sales', '0014_companycage_remove_imap_oauth_fields'),
        ('sales', '0015_companycage_remove_imap_auth_fields'),
        ('sales', '0016_solicitation_pdf_fields'),
        ('sales', '0017_rfqgreeting_rfqsalutation'),
        ('sales', '0018_no_quote_cage'),
        ('sales', '0019_award_import_batch_and_dibbs_award_file_fields'),
        ('sales', '0020_graph_inbox_and_remove_imap'),
        ('sales', '0021_inboxmessage_claim_expires_at_and_more'),
        ('sales', '0022_solicitation_status_lifecycle'),
        ('sales', '0023_dibbsaward_aw_file_date'),
        ('sales', '0024_remove_dibbsaward_award_amount_and_more'),
        ('sales', '0025_remove_dibbsaward_synced_at'),
        ('sales', '0026_wewonaward_remove_awardimportbatch_created_count_and_more'),
        ('sales', '0027_awardimportbatch_scrape_tracking'),
        ('sales', '0028_nsn_procurement_history'),
        ('sales', '0029_awardimportbatch_missing_pages_scraped'),
        ('sales', '0030_solicitation_pdf_fetch_attempts_and_more'),
        ('sales', '0031_solicitation_pdf_data_pulled'),
        ('sales', '0032_solpackaging_solicitation_research_flagged_at_and_more'),
        ('sales', '0033_dibbs_award_dedup_and_lookup_indexes'),
        ('sales', '0034_alter_suppliermatch_match_method'),
        ('sales', '0035_dibbs_award_staging_tables'),
        ('sales', '0036_alter_dibbsawardstaging_stage_id_and_more'),
        ('sales', '0037_sam_entity_cache'),
        ('sales', '0038_masspasslog'),
        ('sales', '0039_companycage_company_alter_companycage_company_name'),
        ('sales', '0040_savedfilter'),
        ('sales', '0041_seed_system_saved_filters'),
        ('sales', '0042_suppliernsn_live_score_fields'),
        ('sales', '0043_solicitationmatchcount_suppliernsnscored'),
        ('sales', '0044_solanalysis'),
        ('sales', '0045_solanalysis_extraction_confidence_and_more'),
        ('sales', '0046_supplierrfq_ready_to_send_and_send_tracking'),
        ('sales', '0047_solicitation_match_count'),
        ('sales', '0048_award_import_batch_hot_poll_source'),
        ('sales', '0049_dibbsnotice'),
        ('sales', '0050_seed_check_dibbs_notices_task'),
        ('sales', '0051_dibbs_award_mod_contract_match_ack'),
        ('sales', '0052_backfill_dibbs_award_mod_matched_contract'),
        ('sales', '0053_competitor_watchlist'),
        ('sales', '0054_dibbs_award_competitor_stats_index'),
        ('sales', '0055_competitor_award_supplier'),
        ('sales', '0056_seed_competitor_supplier_backfill_task'),
        ('sales', '0057_replace_competitor_award_supplier_with_entities'),
        ('sales', '0058_remove_competitor_supplier_backfill_task'),
        ('sales', '0059_competitor_award_parse_status_unavailable'),
        ('sales', '0060_competitor_award_parse_status_resolved_pdf_url'),
        ('sales', '0061_dibbs_award_pdf_url'),
        ('sales', '0062_dibbsaward_award_basic_number_url_and_more'),
        ('sales', '0063_dibbs_award_url_default_constraints'),
    ]

    dependencies = [
        ('contracts', '0096_alter_contract_solicitation_type'),
        ('core', '0003_seed_scheduled_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeWonAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dibbs_we_won_awards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AwardImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('filename', models.CharField(max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('awards_created', models.IntegerField(default=0)),
                ('faux_created', models.IntegerField(default=0)),
                ('faux_upgraded', models.IntegerField(default=0)),
                ('mods_created', models.IntegerField(default=0)),
                ('mods_skipped', models.IntegerField(default=0)),
                ('we_won_count', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('FILE_UPLOAD', 'Manual File Upload'), ('AUTO_SCRAPE', 'Automated Scraper'), ('hot_poll', 'Daytime we-won poll')], default='FILE_UPLOAD', max_length=20)),
                ('scrape_date', models.DateField(blank=True, null=True)),
                ('expected_rows', models.IntegerField(blank=True, null=True)),
                ('scrape_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], max_length=20, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('pages_scraped', models.IntegerField(blank=True, default=0, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dibbs_award_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dibbs_award_import_batch',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='DibbsAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol_number', models.CharField(db_index=True, max_length=50)),
                ('notice_id', models.CharField(max_length=100, unique=True)),
                ('award_date', models.DateField()),
                ('awardee_cage', models.CharField(blank=True, db_index=True, max_length=10)),
                ('we_won', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('SAM', 'SAM.gov'), ('DIBBS_FILE', 'DIBBS File')], db_index=True, default='SAM', max_length=10)),
                ('award_basic_number', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_order_number', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_order_counter', models.CharField(blank=True, max_length=20, null=True)),
                ('last_mod_posting_date', models.DateField(blank=True, null=True)),
                ('total_contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('aw_file_date', models.DateField(blank=True, db_index=True, help_text='Date of the AW file that last wrote this record (from filename, e.g. aw260321.txt → 2026-03-21).', null=True)),
                ('nsn', models.CharField(blank=True, db_index=True, max_length=46, null=True)),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_request', models.CharField(blank=True, max_length=20, null=True)),
                ('dibbs_solicitation_number', models.CharField(blank=True, max_length=30, null=True)),
                ('is_faux', models.BooleanField(default=False, help_text='True when this record was synthesized as a placeholder because a MOD arrived before the original award was imported. Set to False when the real award is subsequently imported.')),
                ('pdf_url', models.CharField(blank=True, default='', help_text='Real dibbs2 Downloads/Awards PDF URL captured from the AwdRecs.aspx grid document-link anchor at scrape time (blank when absent).', max_length=500)),
                ('award_basic_number_url', models.CharField(blank=True, default='', help_text='The Award/Basic PDF document href (blank when absent).', max_length=500)),
                ('award_basic_package_view_url', models.CharField(blank=True, default='', help_text='The Award/Basic Package View AwdRec.aspx href (blank when absent).', max_length=500)),
                ('delivery_order_number_url', models.CharField(blank=True, default='', help_text='The Delivery Order PDF document href (blank when absent).', max_length=500)),
                ('delivery_order_package_view_url', models.CharField(blank=True, default='', help_text='The Delivery Order Package View AwdRec.aspx href (blank when absent).', max_length=500)),
                ('aw_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='dibbs.awardimportbatch')),
            ],
            options={
                'db_table': 'dibbs_award',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField()),
                ('in_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bq_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('as_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('imported_at', models.DateTimeField()),
                ('solicitation_count', models.IntegerField(default=0)),
                ('imported_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Import batch',
                'verbose_name_plural': 'Import batches',
                'db_table': 'tbl_ImportBatch',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=36, unique=True)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('in_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('bq_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('as_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('in_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bq_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('as_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('import_date', models.DateField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('step_results', models.TextField(default='{}')),
                ('imported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Import job',
                'db_table': 'tbl_ImportJob',
            },
        ),
        migrations.CreateModel(
            name='SAMEntityCache',
            fields=[
                ('cage_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('website', models.CharField(blank=True, default='', max_length=500)),
                ('physical_address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('physical_address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('physical_city', models.CharField(blank=True, default='', max_length=100)),
                ('physical_state', models.CharField(blank=True, default='', max_length=50)),
                ('physical_zip', models.CharField(blank=True, default='', max_length=20)),
                ('mailing_address', models.TextField(blank=True, default='')),
                ('sba_flags', models.JSONField(blank=True, default=list)),
                ('naics_codes', models.JSONField(blank=True, default=list)),
                ('psc_codes', models.JSONField(blank=True, default=list)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('last_fetched', models.DateTimeField()),
                ('fetch_error', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SAM Entity Cache',
                'db_table': 'dibbs_sam_entity_cache',
            },
        ),
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitation_number', models.CharField(db_index=True, max_length=13, unique=True)),
                ('solicitation_type', models.CharField(blank=True, max_length=1, null=True)),
                ('small_business_set_aside', models.CharField(blank=True, max_length=1, null=True)),
                ('return_by_date', models.DateField(blank=True, null=True)),
                ('pdf_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_code', models.CharField(blank=True, max_length=5, null=True)),
                ('import_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('RESEARCH', 'Research'), ('Matching', 'Matching'), ('RFQ_PENDING', 'RFQ Pending'), ('RFQ_SENT', 'RFQ Sent'), ('QUOTING', 'Quoting'), ('BID_READY', 'Bid Ready'), ('BID_SUBMITTED', 'Bid Submitted'), ('WON', 'Won'), ('LOST', 'Lost'), ('NO_BID', 'No Bid'), ('Archived', 'Archived')], default='New', max_length=20)),
                ('bucket', models.CharField(choices=[('UNSET', 'Not Yet Triaged'), ('SDVOSB', 'SDVOSB Priority'), ('HUBZONE', 'HUBZone'), ('GROWTH', 'Growth'), ('SKIP', 'Skip')], db_index=True, default='UNSET', max_length=10)),
                ('bucket_assigned_by', models.CharField(blank=True, choices=[('auto', 'Auto'), ('manual', 'Manual'), ('hubzone', 'HUBZone')], max_length=10, null=True)),
                ('hubzone_requested_by', models.CharField(blank=True, default='', help_text='Name or note from HUBZone partner who requested this solicitation be worked.', max_length=100)),
                ('pdf_blob', models.BinaryField(blank=True, null=True)),
                ('pdf_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_fetch_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('FETCHING', 'Fetching'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default=None, max_length=10, null=True)),
                ('pdf_fetch_attempts', models.PositiveSmallIntegerField(default=0)),
                ('pdf_data_pulled', models.DateTimeField(blank=True, default=None, help_text="Set when procurement history data has been extracted from this sol's PDF, either via CA zip or individual fetch.", null=True)),
                ('review_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('review_claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('match_count', models.IntegerField(db_index=True, default=0)),
                ('research_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitations', to='dibbs.importbatch')),
                ('research_flagged_by', models.ForeignKey(blank=True, db_column='research_flagged_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_flagged_sols', to=settings.AUTH_USER_MODEL)),
                ('review_claimed_by', models.ForeignKey(blank=True, db_column='review_claimed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sol_review_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitation',
                'verbose_name_plural': 'Solicitations',
                'db_table': 'dibbs_solicitation',
            },
        ),
        migrations.CreateModel(
            name='SolPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitation_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('packaging_standard', models.CharField(blank=True, max_length=200)),
                ('preservation_requirements', models.TextField(blank=True)),
                ('marking_requirements', models.TextField(blank=True)),
                ('raw_section_d', models.TextField(blank=True, help_text='Raw extracted Section D text for reference')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dibbs_sol_packaging',
            },
        ),
        migrations.CreateModel(
            name='SolicitationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(blank=True, max_length=4, null=True)),
                ('purchase_request_number', models.CharField(blank=True, max_length=13, null=True)),
                ('nsn', models.CharField(db_index=True, max_length=46)),
                ('fsc', models.CharField(blank=True, max_length=4, null=True)),
                ('niin', models.CharField(blank=True, max_length=9, null=True)),
                ('unit_of_issue', models.CharField(blank=True, max_length=2, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('nomenclature', models.CharField(blank=True, max_length=21, null=True)),
                ('amsc', models.CharField(blank=True, max_length=1, null=True)),
                ('item_type_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('item_description_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('trade_agreements_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('buy_american_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('higher_level_quality_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('bq_raw_columns', models.JSONField(blank=True, null=True)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='dibbs.solicitation')),
            ],
            options={
                'verbose_name': 'Solicitation line',
                'verbose_name_plural': 'Solicitation lines',
                'db_table': 'dibbs_solicitation_line',
            },
        ),
        migrations.CreateModel(
            name='SolAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('dpas_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('issuing_office', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fat_required', models.BooleanField(blank=True, null=True)),
                ('fat_units', models.IntegerField(blank=True, null=True)),
                ('fat_days', models.IntegerField(blank=True, null=True)),
                ('fat_summary', models.TextField(blank=True, null=True)),
                ('itar_export_control', models.BooleanField(blank=True, null=True)),
                ('origin_inspection_required', models.BooleanField(blank=True, null=True)),
                ('iso_9001_required', models.BooleanField(blank=True, null=True)),
                ('buy_american_applies', models.BooleanField(blank=True, null=True)),
                ('additive_manufacturing_prohibited', models.BooleanField(blank=True, null=True)),
                ('cmmc_required', models.BooleanField(blank=True, null=True)),
                ('cmmc_level', models.IntegerField(blank=True, null=True)),
                ('quantity_ranges_encouraged', models.BooleanField(blank=True, null=True)),
                ('fob_point', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_destination', models.CharField(blank=True, max_length=200, null=True)),
                ('need_ship_date', models.DateField(blank=True, null=True)),
                ('required_delivery_date', models.DateField(blank=True, null=True)),
                ('packaging_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('preservation_method', models.CharField(blank=True, max_length=200, null=True)),
                ('special_packaging_instructions', models.TextField(blank=True, null=True)),
                ('marking_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('other_notable_requirements', models.TextField(blank=True, help_text='JSON array of strings stored as text', null=True)),
                ('extraction_confidence', models.CharField(blank=True, help_text='HIGH / MEDIUM / LOW from LLM self-assessment', max_length=10, null=True)),
                ('extraction_notes', models.TextField(blank=True, null=True)),
                ('solicitation', models.OneToOneField(db_column='solicitation_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='dibbs.solicitation')),
            ],
            options={
                'db_table': 'dibbs_sol_analysis',
            },
        ),
        migrations.CreateModel(
            name='NsnProcurementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, help_text='Normalized 13-digit NSN, no hyphens. e.g. 5935011299512', max_length=13)),
                ('fsc', models.CharField(db_index=True, help_text='First 4 chars of NSN — FSC code', max_length=4)),
                ('cage_code', models.CharField(max_length=5)),
                ('contract_number', models.CharField(max_length=25)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=5, max_digits=14)),
                ('award_date', models.DateField()),
                ('surplus_material', models.BooleanField(default=False)),
                ('first_seen_sol', models.CharField(blank=True, help_text='Solicitation number where this row was first extracted', max_length=13)),
                ('last_seen_sol', models.CharField(blank=True, help_text='Solicitation number where this row was most recently seen', max_length=13)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NSN Procurement History',
                'verbose_name_plural': 'NSN Procurement History',
                'db_table': 'dibbs_nsn_procurement_history',
                'ordering': ['-award_date'],
                'unique_together': {('nsn', 'contract_number')},
            },
        ),
        migrations.CreateModel(
            name='DibbsNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('external_url', models.URLField(max_length=1000)),
                ('posted_date', models.DateField()),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DIBBS Notice',
                'verbose_name_plural': 'DIBBS Notices',
                'db_table': 'sales_dibbsnotice',
                'ordering': ['-posted_date'],
                'unique_together': {('title', 'posted_date')},
            },
        ),
        migrations.CreateModel(
            name='DibbsAwardStagingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.CharField(db_index=True, max_length=36)),
                ('staged_at', models.DateTimeField()),
                ('raw_award_basic_number', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_nsn', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_delivery_order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('error_reason', models.CharField(max_length=255)),
                ('errored_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_errors', to='dibbs.awardimportbatch')),
            ],
            options={
                'db_table': 'dibbs_award_staging_errors',
            },
        ),
        migrations.CreateModel(
            name='DibbsAwardStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.CharField(db_index=True, help_text='Isolates concurrent staging runs. One UUID per scrape/upload run.', max_length=36)),
                ('staged_at', models.DateTimeField(auto_now_add=True)),
                ('notice_id', models.CharField(max_length=66)),
                ('award_basic_number', models.CharField(max_length=50)),
                ('delivery_order_number', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_order_counter', models.CharField(blank=True, max_length=50, null=True)),
                ('last_mod_posting_date', models.CharField(blank=True, max_length=20, null=True)),
                ('awardee_cage', models.CharField(blank=True, max_length=10, null=True)),
                ('total_contract_price', models.CharField(blank=True, max_length=20, null=True)),
                ('award_date', models.CharField(blank=True, max_length=20, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=20, null=True)),
                ('nsn', models.CharField(blank=True, max_length=50, null=True)),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_request', models.CharField(blank=True, max_length=50, null=True)),
                ('dibbs_solicitation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aw_file_date', models.CharField(blank=True, max_length=20, null=True)),
                ('pdf_url', models.CharField(blank=True, default='', max_length=500)),
                ('award_basic_number_url', models.CharField(blank=True, default='', max_length=500)),
                ('award_basic_package_view_url', models.CharField(blank=True, default='', max_length=500)),
                ('delivery_order_number_url', models.CharField(blank=True, default='', max_length=500)),
                ('delivery_order_package_view_url', models.CharField(blank=True, default='', max_length=500)),
                ('row_type', models.CharField(blank=True, max_length=5, null=True)),
                ('solicitation_id', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_rows', to='dibbs.awardimportbatch')),
            ],
            options={
                'db_table': 'dibbs_award_staging',
            },
        ),
        migrations.CreateModel(
            name='DibbsAwardMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_basic_number', models.CharField(max_length=50)),
                ('delivery_order_number', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_order_counter', models.CharField(blank=True, max_length=20, null=True)),
                ('nsn', models.CharField(blank=True, db_index=True, max_length=46, null=True)),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True)),
                ('awardee_cage', models.CharField(blank=True, db_index=True, max_length=10)),
                ('mod_date', models.DateField(db_index=True, help_text='last_mod_posting_date from the AW file row.')),
                ('mod_contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('purchase_request', models.CharField(blank=True, max_length=20, null=True)),
                ('dibbs_solicitation_number', models.CharField(blank=True, max_length=30, null=True)),
                ('sol_number', models.CharField(blank=True, default='', max_length=50)),
                ('aw_file_date', models.DateField(blank=True, db_index=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_dibbs_mods', to=settings.AUTH_USER_MODEL)),
                ('aw_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mods', to='dibbs.awardimportbatch')),
                ('award', models.ForeignKey(help_text='The original award this MOD relates to. May be a faux placeholder.', on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='dibbs.dibbsaward')),
                ('matched_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dibbs_mods', to='contracts.contract')),
            ],
            options={
                'db_table': 'dibbs_award_mod',
                'ordering': ['-mod_date'],
            },
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='solicitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='dibbs.solicitation'),
        ),
        migrations.CreateModel(
            name='CompetitorWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_watchlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_competitor_watchlist',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAwardParseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('unavailable', 'Unavailable')], default='', max_length=20)),
                ('parse_notes', models.TextField(blank=True, default='')),
                ('resolved_pdf_url', models.CharField(blank=True, default='', help_text='Real dibbs2 Downloads/Awards PDF URL resolved from AwdRec.aspx. Cached so retries skip re-resolution.', max_length=500)),
                ('fetch_error', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity_parse_status', to='dibbs.dibbsaward')),
            ],
            options={
                'db_table': 'sales_competitor_award_parse_status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAwardEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('code_type', models.CharField(choices=[('CAGE', 'CAGE'), ('DODAAC', 'DoDAAC'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('role', models.CharField(choices=[('CONTRACTOR', 'Contractor'), ('OEM_DESIGN_AUTHORITY', 'OEM / Design Authority'), ('MANUFACTURER', 'Manufacturer'), ('BUYER', 'Buyer'), ('PAYMENT_OFFICE', 'Payment Office'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_note', models.TextField(blank=True, default='')),
                ('extraction_method', models.CharField(choices=[('REGEX', 'Regex'), ('LLM', 'LLM')], default='REGEX', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='dibbs.dibbsaward')),
            ],
            options={
                'db_table': 'sales_competitor_award_entity',
                'ordering': ['role', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_code', models.CharField(max_length=5, unique=True)),
                ('company_name', models.CharField(blank=True, default='', help_text="Legacy display label; prefer linking contracts.Company via 'company'.", max_length=150)),
                ('sb_representations_code', models.CharField(max_length=1)),
                ('affirmative_action_code', models.CharField(max_length=2)),
                ('previous_contracts_code', models.CharField(max_length=2)),
                ('alternate_disputes_resolution', models.CharField(max_length=1)),
                ('default_fob_point', models.CharField(default='D', max_length=1)),
                ('default_payment_terms', models.CharField(default='1', max_length=2)),
                ('default_child_labor_code', models.CharField(default='N', max_length=1)),
                ('default_markup_pct', models.DecimalField(decimal_places=2, default=3.5, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('smtp_reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Link this CAGE code to the corresponding company in the contracts system. Required for automatic award queue injection.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cage_codes', to='contracts.company', verbose_name='Linked Company')),
            ],
            options={
                'verbose_name': 'Company CAGE',
                'verbose_name_plural': 'Company CAGEs',
                'db_table': 'dibbs_company_cage',
            },
        ),
        migrations.CreateModel(
            name='ApprovedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, max_length=46)),
                ('approved_cage', models.CharField(db_index=True, max_length=5)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sources', to='dibbs.importbatch')),
            ],
            options={
                'verbose_name': 'Approved source',
                'verbose_name_plural': 'Approved sources',
                'db_table': 'tbl_ApprovedSource',
            },
        ),
        migrations.AddConstraint(
            model_name='dibbsawardmod',
            constraint=models.UniqueConstraint(fields=('award', 'mod_date', 'nsn', 'mod_contract_price'), name='dibbs_award_mod_dedup'),
        ),
        migrations.AddIndex(
            model_name='dibbsaward',
            index=models.Index(fields=['award_basic_number', 'delivery_order_number', 'nsn'], name='dibbs_award_dedup'),
        ),
        migrations.AddIndex(
            model_name='dibbsaward',
            index=models.Index(fields=['award_basic_number'], name='dibbs_award_basic_number'),
        ),
        migrations.AddIndex(
            model_name='dibbsaward',
            index=models.Index(fields=['delivery_order_number'], name='dibbs_award_delivery_order'),
        ),
        migrations.RunPython(db_objects.add_url_defaults, db_objects.drop_url_defaults),
        migrations.RunPython(
            db_objects.create_competitor_stats_index,
            db_objects.drop_competitor_stats_index,
        ),
        migrations.RunPython(
            db_objects.recreate_we_won_awards_view,
            db_objects.drop_we_won_awards_view,
        ),
        migrations.RunPython(seed_check_dibbs_notices_task, unseed_check_dibbs_notices_task),
    ]
