# Generated by Django 4.2.30 on 2026-09-25 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dibbs', '0002_drop_sales_workflow_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitation',
            name='bucket',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='bucket_assigned_by',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='hubzone_requested_by',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='match_count',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='research_flagged_at',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='research_flagged_by',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='review_claim_expires_at',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='review_claimed_at',
        ),
        migrations.RemoveField(
            model_name='solicitation',
            name='review_claimed_by',
        ),
        migrations.AlterModelTable(
            name='competitorawardentity',
            table='dibbs_competitor_award_entity',
        ),
        migrations.AlterModelTable(
            name='competitorawardparsestatus',
            table='dibbs_competitor_award_parse_status',
        ),
        migrations.AlterModelTable(
            name='competitorwatchlist',
            table='dibbs_competitor_watchlist',
        ),
        migrations.AlterModelTable(
            name='dibbsnotice',
            table='dibbs_notice',
        ),
    ]
