# Generated by Django 6.0.3 on 2026-05-06 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_filename', models.CharField(max_length=255)),
                ('target_model', models.CharField(max_length=100)),
                ('match_field', models.CharField(max_length=100)),
                ('column_map', models.JSONField(default=dict)),
                ('matched_count', models.IntegerField(default=0)),
                ('unmatched_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('previewing', 'Previewing'), ('committed', 'Committed')], default='draft', max_length=20)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('skipped', 'Skipped'), ('committed', 'Committed')], default='unmatched', max_length=20)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('proposed_changes', models.JSONField(default=dict)),
                ('matched_target_id', models.IntegerField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importsession')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='ValueTranslationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(max_length=100)),
                ('target_field', models.CharField(max_length=100)),
                ('raw_value', models.CharField(max_length=255)),
                ('resolved_id', models.IntegerField()),
            ],
            options={
                'ordering': ['target_model', 'target_field', 'raw_value'],
                'unique_together': {('target_model', 'target_field', 'raw_value')},
            },
        ),
    ]
