# Generated by Django 4.2.20 on 2025-05-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='model_name',
            field=models.CharField(default='contracts', max_length=200),
            preserve_default=False,
        ),
    ]
