# Generated by Django 4.2.20 on 2025-05-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_savedreport_model_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='savedreport',
            name='model_name',
        ),
        migrations.AddField(
            model_name='savedreport',
            name='selected_tables',
            field=models.JSONField(default='', help_text='List of selected table names'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='filters',
            field=models.JSONField(help_text='Filter criteria for each table'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='group_by',
            field=models.JSONField(help_text='Group by configuration for each table'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='selected_fields',
            field=models.JSONField(help_text='Dictionary mapping table names to their selected fields'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='sort_by',
            field=models.JSONField(help_text='Sort configuration for each table'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='sort_direction',
            field=models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], max_length=4),
        ),
    ]
