# Generated by Django 4.2.20 on 2025-05-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_alter_savedreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='selected_tables',
            field=models.JSONField(default='', help_text='List of selected table names'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='sort_by',
            field=models.JSONField(help_text='Sort by configuration for each table'),
        ),
    ]
