# Generated by Django 4.2.20 on 2025-05-14 19:39

from django.db import migrations, models
import reporting.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_alter_savedreport_selected_tables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedreport',
            name='filters',
            field=models.JSONField(default=reporting.models.get_default_list, help_text='Filter criteria for each table'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='group_by',
            field=models.JSONField(default=reporting.models.get_default_dict, help_text='Group by configuration for each table'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='selected_fields',
            field=models.JSONField(default=reporting.models.get_default_dict, help_text='Dictionary mapping table names to their selected fields'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='selected_tables',
            field=models.JSONField(default=reporting.models.get_default_list, help_text='List of selected table names'),
        ),
        migrations.AlterField(
            model_name='savedreport',
            name='sort_by',
            field=models.JSONField(default=reporting.models.get_default_dict, help_text='Sort by configuration for each table'),
        ),
    ]
