# Generated by Django 4.2.20 on 2025-05-15 16:39

from django.db import migrations, models
import reporting.models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_alter_savedreport_filters_alter_savedreport_group_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedreport',
            name='aggregations',
            field=models.JSONField(default=reporting.models.get_default_dict, help_text='Aggregation settings for numeric fields. Format: {"field_path": {"type": "sum|avg|min|max|count", "label": "Custom Label"}}'),
        ),
    ]
