# Generated by Django 5.0.11 on 2025-02-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nsn', models.CharField(blank=True, db_column='NSN', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=250, null=True)),
                ('partnumber', models.CharField(blank=True, db_column='PartNumber', max_length=50, null=True)),
                ('manufacturer', models.CharField(blank=True, db_column='Manufacturer', max_length=50, null=True)),
                ('itemlocation', models.CharField(blank=True, db_column='ItemLocation', max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('purchaseprice', models.DecimalField(blank=True, db_column='PurchasePrice', decimal_places=2, max_digits=19, null=True)),
                ('totalcost', models.DecimalField(blank=True, db_column='TotalCost', decimal_places=2, editable=False, max_digits=19, null=True)),
            ],
            options={
                'db_table': 'STATZ_WAREHOUSE_INVENTORY_TBL',
            },
        ),
    ]
