# Generated by Django 5.0.11 on 2025-02-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='description',
            field=models.CharField(blank=True, db_column='Description', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='itemlocation',
            field=models.CharField(blank=True, db_column='ItemLocation', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='manufacturer',
            field=models.CharField(blank=True, db_column='Manufacturer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='nsn',
            field=models.CharField(blank=True, db_column='NSN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='partnumber',
            field=models.CharField(blank=True, db_column='PartNumber', max_length=50, null=True),
        ),
    ]
