# Generated by Django 5.0.11 on 2025-02-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventoryitem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='purchaseprice',
            field=models.FloatField(blank=True, db_column='PurchasePrice', null=True),
        ),
    ]
