# Generated by Django 5.0.11 on 2025-02-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_purchaseprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='totalcost',
            field=models.FloatField(blank=True, db_column='TotalCost', editable=False, null=True),
        ),
    ]
