# Generated by Django 6.0.3 on 2026-09-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
