# Generated by Django 4.2.20 on 2025-05-16 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField(help_text='The query pattern template')),
                ('field_mappings', models.JSONField(help_text='Mapping of natural language terms to field names')),
                ('success_rate', models.FloatField(default=0.0)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['success_rate'], name='reports_que_success_72d882_idx'), models.Index(fields=['usage_count'], name='reports_que_usage_c_efca6d_idx'), models.Index(fields=['last_used'], name='reports_que_last_us_11b5ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_query', models.TextField(help_text='The original natural language query')),
                ('normalized_query', models.TextField(help_text='Normalized version of the query')),
                ('parsed_fields', models.JSONField(help_text='Fields extracted from the query')),
                ('query_type', models.CharField(help_text='Type of query (LIST, FILTER, etc.)', max_length=50)),
                ('was_successful', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time', models.FloatField(help_text='Query execution time in seconds')),
                ('result_count', models.IntegerField(default=0)),
                ('was_helpful', models.BooleanField(null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('similar_queries', models.ManyToManyField(help_text='Queries that are semantically similar', related_name='related_queries', to='reports.querylog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['query_type'], name='reports_que_query_t_09c539_idx'), models.Index(fields=['was_successful'], name='reports_que_was_suc_cea534_idx'), models.Index(fields=['created_at'], name='reports_que_created_424f0a_idx')],
            },
        ),
    ]
