# Generated by Django 4.2.20 on 2025-05-16 17:49

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_term', models.CharField(help_text='The natural language term', max_length=100, unique=True)),
                ('db_field', models.CharField(help_text='The corresponding database field', max_length=100)),
                ('confidence', models.FloatField(default=0.5, help_text='Confidence score for this mapping')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this mapping has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this mapping was first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this mapping was last updated')),
            ],
            options={
                'ordering': ['-confidence', '-usage_count'],
            },
        ),
        migrations.AlterModelOptions(
            name='querylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='querypattern',
            options={'ordering': ['-usage_count']},
        ),
        migrations.RemoveIndex(
            model_name='querylog',
            name='reports_que_created_424f0a_idx',
        ),
        migrations.RemoveIndex(
            model_name='querypattern',
            name='reports_que_success_72d882_idx',
        ),
        migrations.RemoveIndex(
            model_name='querypattern',
            name='reports_que_last_us_11b5ce_idx',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='similar_queries',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='was_helpful',
        ),
        migrations.RemoveField(
            model_name='querypattern',
            name='field_mappings',
        ),
        migrations.RemoveField(
            model_name='querypattern',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='querypattern',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='querypattern',
            name='success_rate',
        ),
        migrations.AddField(
            model_name='querylog',
            name='corrected_query',
            field=models.TextField(blank=True, help_text='Corrected version of the query provided through training', null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='corrections_processed',
            field=models.BooleanField(default=False, help_text='Whether corrections have been processed by the learning engine'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='field_mappings',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Manual field mappings provided through training'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='generated_sql',
            field=models.TextField(blank=True, help_text='SQL query generated by the NLI system', null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='notes',
            field=models.TextField(blank=True, help_text='Training notes about this query', null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='orm_translation',
            field=models.TextField(blank=True, help_text='Django ORM translation of the verified SQL', null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='sql_verification_date',
            field=models.DateTimeField(blank=True, help_text='When this query was verified', null=True),
        ),
        migrations.AddField(
            model_name='querylog',
            name='sql_verified',
            field=models.BooleanField(default=False, help_text='Whether this query has been verified in SSMS'),
        ),
        migrations.AddField(
            model_name='querylog',
            name='sql_verified_by',
            field=models.ForeignKey(help_text='User who verified the SQL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sql_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the query was made'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querylog',
            name='verified_sql',
            field=models.TextField(blank=True, help_text='Correct SQL query verified in SSMS', null=True),
        ),
        migrations.AddField(
            model_name='querypattern',
            name='corrected_pattern',
            field=models.TextField(default='', help_text='The corrected/normalized query pattern'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querypattern',
            name='original_pattern',
            field=models.TextField(default='', help_text='The original query pattern'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querypattern',
            name='success_count',
            field=models.IntegerField(default=0, help_text='Number of successful queries using this pattern'),
        ),
        migrations.AddField(
            model_name='querypattern',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this pattern was last updated'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if query failed', null=True),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='execution_time',
            field=models.FloatField(help_text='Time taken to execute the query in seconds'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='normalized_query',
            field=models.TextField(help_text='The normalized/preprocessed query text'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='parsed_fields',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Dictionary mapping natural language terms to database fields'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='query_type',
            field=models.CharField(help_text='Type of query (e.g., SELECT, COUNT, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='raw_query',
            field=models.TextField(help_text='The original query text as entered by the user'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='result_count',
            field=models.IntegerField(default=0, help_text='Number of results returned by the query'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='user',
            field=models.ForeignKey(help_text='User who made the query', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='user_feedback',
            field=models.TextField(blank=True, help_text='Feedback provided by the user about the query results', null=True),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='was_successful',
            field=models.BooleanField(default=False, help_text='Whether the query was executed successfully'),
        ),
        migrations.AlterField(
            model_name='querypattern',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this pattern was first created'),
        ),
        migrations.AlterField(
            model_name='querypattern',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='Number of times this pattern has been used'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['timestamp'], name='reports_que_timesta_f4a258_idx'),
        ),
        migrations.AddIndex(
            model_name='querypattern',
            index=models.Index(fields=['success_count'], name='reports_que_success_18424a_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldmapping',
            index=models.Index(fields=['natural_term'], name='reports_fie_natural_4c1b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldmapping',
            index=models.Index(fields=['db_field'], name='reports_fie_db_fiel_819899_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldmapping',
            index=models.Index(fields=['confidence'], name='reports_fie_confide_98d533_idx'),
        ),
    ]
