# Generated by Django 4.2.20 on 2025-05-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_fieldmapping_alter_querylog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='querypattern',
            name='success_rate',
            field=models.FloatField(default=0.0, help_text='Success rate of this pattern (percentage)'),
        ),
        migrations.AddIndex(
            model_name='querypattern',
            index=models.Index(fields=['success_rate'], name='reports_que_success_72d882_idx'),
        ),
    ]
