# Generated by Django 4.2.20 on 2025-05-16 17:59

from django.db import migrations

def update_success_rates(apps, schema_editor):
    QueryPattern = apps.get_model('reports', 'QueryPattern')
    for pattern in QueryPattern.objects.all():
        if pattern.usage_count == 0:
            pattern.success_rate = 0
        else:
            pattern.success_rate = (pattern.success_count / pattern.usage_count) * 100
        pattern.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_querypattern_success_rate_and_more'),
    ]

    operations = [
        migrations.RunPython(update_success_rates),
    ]
