# Generated by Django 4.2.20 on 2025-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20250516_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='querylog',
            name='similar_queries',
            field=models.ManyToManyField(help_text='Queries that are similar to this one', to='reports.querylog'),
        ),
    ]
