"""
Sales app views.
"""
from sales.views.dashboard import dashboard
from sales.views.imports import (
    import_upload,
    import_history,
    import_batch_delete,
    import_job_progress,
    import_step_parse,
    import_step_solicitations,
    import_step_lines,
    import_step_match,
    import_step_awards,
    sync_awards_view,
)
from sales.views.solicitations import (
    solicitation_list,
    solicitation_detail,
    no_bid,
    global_search,
)
from sales.views.suppliers import (
    backfill_nsn,
    supplier_list,
    supplier_detail,
    supplier_add_nsn,
    supplier_add_fsc,
    supplier_remove_nsn,
    supplier_remove_fsc,
)
from sales.views.rfq import (
    rfq_pending,
    rfq_sent,
    rfq_send_single,
    rfq_send_batch,
    rfq_center,
    rfq_center_detail,
    rfq_enter_quote,
    rfq_send_followup,
    rfq_mark_no_response,
    rfq_mark_declined,
    quote_select_for_bid,
)
from sales.views.bids import (
    bids_ready,
    bid_builder,
    bid_select_quote,
    bids_export_queue,
    bids_export_download,
    bids_history,
)
from sales.views.settings import (
    settings_index,
    settings_cages,
    settings_cage_add,
    settings_cage_edit,
)
from sales.views.entity_lookup import entity_lookup

__all__ = [
    "dashboard",
    "import_upload",
    "import_history",
    "import_batch_delete",
    "import_job_progress",
    "import_step_parse",
    "import_step_solicitations",
    "import_step_lines",
    "import_step_match",
    "import_step_awards",
    "sync_awards_view",
    "solicitation_list",
    "solicitation_detail",
    "no_bid",
    "global_search",
    "backfill_nsn",
    "supplier_list",
    "supplier_detail",
    "supplier_add_nsn",
    "supplier_add_fsc",
    "supplier_remove_nsn",
    "supplier_remove_fsc",
    "rfq_pending",
    "rfq_sent",
    "rfq_send_single",
    "rfq_send_batch",
    "rfq_center",
    "rfq_center_detail",
    "rfq_enter_quote",
    "rfq_send_followup",
    "rfq_mark_no_response",
    "rfq_mark_declined",
    "quote_select_for_bid",
    "bids_ready",
    "bid_builder",
    "bid_select_quote",
    "bids_export_queue",
    "bids_export_download",
    "bids_history",
    "settings_index",
    "settings_cages",
    "settings_cage_add",
    "settings_cage_edit",
    "entity_lookup",
]
