# Generated by Django 6.0.3 on 2026-10-08 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0104_folder_repair_log_stage_b'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanFilingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action', models.CharField(choices=[('FILED', 'Filed'), ('SKIPPED', 'Skipped'), ('FAILED', 'Failed')], max_length=10)),
                ('mailbox', models.CharField(blank=True, default='', max_length=320)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('internet_message_id', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_size', models.IntegerField(default=0)),
                ('contract_number', models.CharField(blank=True, default='', max_length=100)),
                ('destination_kind', models.CharField(blank=True, default='', max_length=20)),
                ('folder_item_id', models.CharField(blank=True, default='', max_length=255)),
                ('folder_path', models.CharField(blank=True, default='', max_length=400)),
                ('folder_created', models.BooleanField(default=False)),
                ('uploaded_item_id', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_name', models.CharField(blank=True, default='', max_length=255)),
                ('already_present', models.BooleanField(default=False)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=200)),
                ('error', models.CharField(blank=True, default='', max_length=1000)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_filing_logs', to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_filing_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tools_scan_filing_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
