# Generated by Django 6.0.3 on 2026-10-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0104_folder_repair_log_stage_b'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanfilinglog',
            name='idiq_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_filing_logs', to='contracts.idiqcontract'),
        ),
    ]
