# Generated by Django 5.0.14 on 2026-08-14 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcadeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_key', models.CharField(db_index=True, max_length=32)),
                ('puzzle_date', models.DateField(db_index=True)),
                ('seed', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('solved', 'Solved'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16)),
                ('par', models.PositiveSmallIntegerField()),
                ('moves_used', models.PositiveIntegerField(default=0)),
                ('over_par', models.IntegerField(blank=True, null=True)),
                ('active_ms', models.PositiveIntegerField(default=0)),
                ('state', models.TextField(default='{}')),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcade_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['game_key', 'puzzle_date', 'over_par', 'active_ms'], name='idx_arcade_leaderboard'), models.Index(fields=['user', 'game_key', 'status'], name='idx_arcade_user_handicap')],
            },
        ),
        migrations.AddConstraint(
            model_name='arcadeattempt',
            constraint=models.UniqueConstraint(fields=('user', 'game_key', 'puzzle_date'), name='uniq_arcade_attempt_per_day'),
        ),
    ]
