# Generated by Django 6.0.3 on 2026-08-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0002_rename_over_par_to_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordleRejectedGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=5, unique=True)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-hit_count', 'word'],
            },
        ),
        migrations.AlterField(
            model_name='arcadeattempt',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('solved', 'Solved'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='in_progress', max_length=16),
        ),
    ]
