# Generated by Django 5.0.14 on 2026-08-18 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcade', '0003_wordle_failed_and_rejected_guesses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(blank=True, default='', max_length=24)),
                ('credits', models.BigIntegerField(default=0)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('best_score', models.BigIntegerField(default=0, help_text='Denormalized personal-best score for cheap lobby display.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marauder_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarauderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.CharField(max_length=64, unique=True)),
                ('score', models.BigIntegerField(help_text="Higher is better. Only 'valid' runs count on leaderboards.")),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('credits_earned', models.PositiveIntegerField(default=0)),
                ('enemies_killed', models.PositiveIntegerField(default=0)),
                ('max_weapon_tier', models.PositiveSmallIntegerField(default=1)),
                ('wave_reached', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('flagged', 'Flagged'), ('rejected', 'Rejected')], default='valid', max_length=16)),
                ('flag_reason', models.CharField(blank=True, default='', max_length=64)),
                ('state', models.TextField(default='{}')),
                ('started_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marauder_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-score'], name='idx_marauder_global_top'), models.Index(fields=['user', 'status', '-score'], name='idx_marauder_user_top')],
            },
        ),
    ]
