# Generated by Django 4.2.20 on 2025-05-08 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcticwolfcourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
