# Generated by Django 4.2.20 on 2025-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_arcticwolfcourse_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcticwolfcourse',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
