# Generated by Django 4.2.20 on 2025-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_arcticwolfcourse_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='upload',
            field=models.BooleanField(default=False),
        ),
    ]
