# Generated by Django 4.2.25 on 2025-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_course_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="document",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
