# Generated by Django 4.2.24 on 2025-11-24 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0006_alter_tracker_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReviewClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_clicked', models.DateTimeField()),
                ('last_clicked', models.DateTimeField()),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.matrix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'matrix')},
            },
        ),
    ]
