# Generated by Django 4.2.25 on 2026-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_coursereviewclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrix',
            name='frequency',
            field=models.CharField(blank=True, choices=[('once', 'Once'), ('annually', 'Annually'), ('bi-annually', 'Semi-Annual')], max_length=100, null=True),
        ),
    ]
