# Generated by Django 4.2.24 on 2026-03-09 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0003_openroutermodelsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_code', models.CharField(max_length=5, unique=True)),
                ('company_name', models.CharField(max_length=150)),
                ('sb_representations_code', models.CharField(max_length=1)),
                ('affirmative_action_code', models.CharField(max_length=2)),
                ('previous_contracts_code', models.CharField(max_length=2)),
                ('alternate_disputes_resolution', models.CharField(max_length=1)),
                ('default_fob_point', models.CharField(default='D', max_length=1)),
                ('default_payment_terms', models.CharField(default='1', max_length=2)),
                ('default_child_labor_code', models.CharField(default='N', max_length=1)),
                ('default_markup_pct', models.DecimalField(decimal_places=2, default=3.5, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company CAGE',
                'verbose_name_plural': 'Company CAGEs',
                'db_table': 'dibbs_company_cage',
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateField()),
                ('in_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bq_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('as_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('imported_at', models.DateTimeField()),
                ('solicitation_count', models.IntegerField(default=0)),
                ('imported_by', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Import batch',
                'verbose_name_plural': 'Import batches',
                'db_table': 'tbl_ImportBatch',
            },
        ),
        migrations.CreateModel(
            name='Solicitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitation_number', models.CharField(db_index=True, max_length=13, unique=True)),
                ('solicitation_type', models.CharField(blank=True, max_length=1, null=True)),
                ('small_business_set_aside', models.CharField(blank=True, max_length=1, null=True)),
                ('return_by_date', models.DateField(blank=True, null=True)),
                ('pdf_file_name', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_code', models.CharField(blank=True, max_length=5, null=True)),
                ('import_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Reviewing', 'Reviewing'), ('RFQ Sent', 'RFQ Sent'), ('Bid Submitted', 'Bid Submitted'), ('No Bid', 'No Bid'), ('Won', 'Won'), ('Lost', 'Lost')], default='New', max_length=20)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitations', to='sales.importbatch')),
            ],
            options={
                'verbose_name': 'Solicitation',
                'verbose_name_plural': 'Solicitations',
                'db_table': 'dibbs_solicitation',
            },
        ),
        migrations.CreateModel(
            name='SolicitationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(blank=True, max_length=4, null=True)),
                ('purchase_request_number', models.CharField(blank=True, max_length=13, null=True)),
                ('nsn', models.CharField(db_index=True, max_length=46)),
                ('fsc', models.CharField(blank=True, max_length=4, null=True)),
                ('niin', models.CharField(blank=True, max_length=9, null=True)),
                ('unit_of_issue', models.CharField(blank=True, max_length=2, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('nomenclature', models.CharField(blank=True, max_length=21, null=True)),
                ('amsc', models.CharField(blank=True, max_length=1, null=True)),
                ('item_type_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('item_description_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('trade_agreements_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('buy_american_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('higher_level_quality_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.solicitation')),
            ],
            options={
                'verbose_name': 'Solicitation line',
                'verbose_name_plural': 'Solicitation lines',
                'db_table': 'dibbs_solicitation_line',
            },
        ),
        migrations.CreateModel(
            name='SupplierRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_to', models.EmailField(max_length=254)),
                ('response_received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RESPONDED', 'Responded'), ('NO_RESPONSE', 'No Response'), ('DECLINED', 'Declined')], default='SENT', max_length=20)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='sales.solicitationline')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rfqs_sent', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_dibbs_rfqs', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier RFQ',
                'verbose_name_plural': 'Supplier RFQs',
                'db_table': 'dibbs_supplier_rfq',
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, max_length=46)),
                ('unit_price', models.DecimalField(decimal_places=5, max_digits=13)),
                ('lead_time_days', models.IntegerField()),
                ('quantity_available', models.IntegerField(blank=True, null=True)),
                ('part_number_offered', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('quote_date', models.DateTimeField(auto_now_add=True)),
                ('is_selected_for_bid', models.BooleanField(default=False)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_quotes_entered', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotes', to='sales.solicitationline')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='sales.supplierrfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_dibbs_quotes', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier quote',
                'verbose_name_plural': 'Supplier quotes',
                'db_table': 'dibbs_supplier_quote',
            },
        ),
        migrations.CreateModel(
            name='SupplierContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('EMAIL_OUT', 'Outbound Email'), ('EMAIL_IN', 'Inbound Email'), ('PHONE', 'Phone Call'), ('FOLLOWUP', 'Follow-up Email'), ('NOTE', 'Internal Note')], max_length=20)),
                ('direction', models.CharField(choices=[('IN', 'Inbound'), ('OUT', 'Outbound')], max_length=3)),
                ('summary', models.TextField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_contact_logs', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_log', to='sales.supplierrfq')),
                ('solicitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_log', to='sales.solicitation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_contact_log', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier contact log',
                'verbose_name_plural': 'Supplier contact logs',
                'db_table': 'dibbs_supplier_contact_log',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='GovernmentBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quoter_cage', models.CharField(max_length=5)),
                ('quote_for_cage', models.CharField(max_length=5)),
                ('bid_type_code', models.CharField(max_length=2)),
                ('unit_price', models.DecimalField(decimal_places=5, max_digits=13)),
                ('delivery_days', models.IntegerField()),
                ('manufacturer_dealer', models.CharField(max_length=2)),
                ('mfg_source_cage', models.CharField(blank=True, max_length=5, null=True)),
                ('fob_point', models.CharField(default='D', max_length=1)),
                ('bid_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('exported_bq_file', models.CharField(blank=True, max_length=255, null=True)),
                ('bid_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='sales.solicitationline')),
                ('selected_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid', to='sales.supplierquote')),
                ('solicitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sales.solicitation')),
            ],
            options={
                'verbose_name': 'Government bid',
                'verbose_name_plural': 'Government bids',
                'db_table': 'dibbs_government_bid',
            },
        ),
        migrations.CreateModel(
            name='ApprovedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, max_length=46)),
                ('approved_cage', models.CharField(db_index=True, max_length=5)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sources', to='sales.importbatch')),
            ],
            options={
                'verbose_name': 'Approved source',
                'verbose_name_plural': 'Approved sources',
                'db_table': 'tbl_ApprovedSource',
            },
        ),
        migrations.CreateModel(
            name='SupplierNSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, max_length=46)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_nsn_capabilities', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier NSN',
                'verbose_name_plural': 'Supplier NSNs',
                'db_table': 'dibbs_supplier_nsn',
                'unique_together': {('supplier', 'nsn')},
            },
        ),
        migrations.CreateModel(
            name='SupplierMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_tier', models.IntegerField()),
                ('match_method', models.CharField(choices=[('DIRECT_NSN', 'Direct NSN'), ('APPROVED_SOURCE', 'Approved Source'), ('FSC', 'FSC Category')], max_length=20)),
                ('is_excluded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_matches', to='sales.solicitationline')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_dibbs_matches', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier match',
                'verbose_name_plural': 'Supplier matches',
                'db_table': 'dibbs_supplier_match',
                'unique_together': {('line', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierFSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fsc_code', models.CharField(db_index=True, max_length=4)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_fsc_capabilities', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier FSC',
                'verbose_name_plural': 'Supplier FSCs',
                'db_table': 'dibbs_supplier_fsc',
                'unique_together': {('supplier', 'fsc_code')},
            },
        ),
    ]
