# Generated by Django 4.2.28 on 2026-03-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_openroutermodelsetting'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliermatch',
            name='match_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='suppliernsn',
            name='last_synced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suppliernsn',
            name='match_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='suppliernsn',
            name='source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='suppliercontactlog',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_log', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierfsc',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsc_capabilities', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='suppliermatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dibbs_matches', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='suppliernsn',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nsn_capabilities', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dibbs_quotes', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='supplierrfq',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dibbs_rfqs', to='suppliers.supplier'),
        ),
    ]
