# Generated by Django 4.2.24 on 2026-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_suppliermatch_match_score_suppliernsn_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='bucket',
            field=models.CharField(choices=[('UNSET', 'Not Yet Triaged'), ('SDVOSB', 'SDVOSB Priority'), ('HUBZONE', 'HUBZone'), ('GROWTH', 'Growth'), ('SKIP', 'Skip')], db_index=True, default='UNSET', max_length=10),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='bucket_assigned_by',
            field=models.CharField(blank=True, choices=[('auto', 'Auto'), ('manual', 'Manual'), ('hubzone', 'HUBZone')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Matching', 'Matching'), ('RFQ_PENDING', 'RFQ Pending'), ('RFQ_SENT', 'RFQ Sent'), ('QUOTING', 'Quoting'), ('BID_READY', 'Bid Ready'), ('BID_SUBMITTED', 'Bid Submitted'), ('WON', 'Won'), ('LOST', 'Lost'), ('NO_BID', 'No Bid')], default='New', max_length=20),
        ),
    ]
