# Generated by Django 4.2.24 on 2026-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_solicitation_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycage',
            name='smtp_reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='declined_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='email_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='follow_up_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='follow_up_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierrfq',
            name='email_sent_to',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplierrfq',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RESPONDED', 'Responded'), ('NO_RESPONSE', 'No Response'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
    ]
