# Generated by Django 4.2.24 on 2026-03-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_bq_raw_columns_and_bid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='hubzone_requested_by',
            field=models.CharField(blank=True, default='', help_text='Name or note from HUBZone partner who requested this solicitation be worked.', max_length=100),
        ),
    ]
