# Generated by Django 4.2.28 on 2026-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_hubzone_requested_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=36, unique=True)),
                ('status', models.CharField(default='uploaded', max_length=20)),
                ('in_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('bq_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('as_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('in_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bq_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('as_file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('import_date', models.DateField(blank=True, null=True)),
                ('batch_id', models.IntegerField(blank=True, null=True)),
                ('step_results', models.TextField(default='{}')),
                ('imported_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Import job',
                'db_table': 'tbl_ImportJob',
            },
        ),
    ]
