# Generated by Django 4.2.24 on 2026-03-12 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_default_template(apps, schema_editor):
    EmailTemplate = apps.get_model("sales", "EmailTemplate")
    EmailTemplate.objects.create(
        name="Standard RFQ",
        is_default=True,
        subject_template="RFQ – {sol_number} / NSN {nsn} – Due {return_date}",
        body_template="""Dear {supplier_name},

We are requesting a quote for the following item on a U.S. Government solicitation:

  Solicitation #:  {sol_number}
  NSN:             {nsn}
  Nomenclature:    {nomenclature}
  Quantity:        {qty} {unit_of_issue}
  Return By:       {return_date}

Please provide your best unit price, lead time (days ARO), and any applicable
part number. If you are unable to quote, please let us know so we can update
our records.

Reply to this email or contact us directly.

Thank you,
{your_name}
{your_email}

STATZ LLC — SDVOSB
""",
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0008_add_dibbs_award"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("subject_template", models.CharField(max_length=255)),
                ("body_template", models.TextField()),
                ("is_default", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="email_templates_created", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "dibbs_email_template",
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.RunPython(seed_default_template, migrations.RunPython.noop),
    ]
