# Generated by Django for Session 10A — add PDF storage to Solicitation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_companycage_remove_imap_auth_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitation",
            name="pdf_blob",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitation",
            name="pdf_fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
