# Generated by Django for Session 10A — RFQ greeting and salutation phrases

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_solicitation_pdf_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFQGreeting",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(help_text="Greeting phrase. Use {supplier_name} or {contact_name} as variables.")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dibbs_rfq_greeting",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RFQSalutation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(help_text="Closing phrase. Use {your_name} or {your_email} as variables.")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dibbs_rfq_salutation",
                "ordering": ["id"],
            },
        ),
    ]
