# Generated by Django 5.0.14 on 2026-03-20 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0017_rfqgreeting_rfqsalutation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycage",
            name="imap_user",
            field=models.CharField(
                blank=True,
                help_text="Shared mailbox address, e.g. sales@statzcorp.com",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inboxemail",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="suppliermatch",
            name="match_method",
            field=models.CharField(
                choices=[
                    ("DIRECT_NSN", "Direct NSN"),
                    ("APPROVED_SOURCE", "Approved Source"),
                    ("FSC", "FSC Category"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="supplierrfq",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PENDING", "Pending"),
                    ("SENT", "Sent"),
                    ("RESPONDED", "Responded"),
                    ("NO_RESPONSE", "No Response"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="NoQuoteCAGE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cage_code",
                    models.CharField(
                        db_index=True,
                        help_text="Five-character CAGE code.",
                        max_length=5,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Optional reason or notes recorded by the team member.",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True = currently on the No Quote list. False = previously flagged but restored.",
                    ),
                ),
                (
                    "deactivated_at",
                    models.DateField(
                        blank=True,
                        help_text="Date the record was marked inactive (supplier restored).",
                        null=True,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="no_quote_cages_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dibbs_no_quote_cage",
                "ordering": ["-date_added"],
            },
        ),
        migrations.AddConstraint(
            model_name="noquotecage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("cage_code",),
                name="unique_active_no_quote_cage",
            ),
        ),
    ]
