# Generated by Django 4.2.24 on 2026-03-20 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0018_no_quote_cage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dibbsaward',
            name='award_basic_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='delivery_order_counter',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='delivery_order_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='dibbs_solicitation_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='last_mod_posting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='nomenclature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='nsn',
            field=models.CharField(blank=True, db_index=True, max_length=46, null=True),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='purchase_request',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='source',
            field=models.CharField(choices=[('SAM', 'SAM.gov'), ('DIBBS_FILE', 'DIBBS File')], db_index=True, default='SAM', max_length=10),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='total_contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='AwardImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('filename', models.CharField(max_length=50)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('created_count', models.IntegerField(default=0)),
                ('updated_count', models.IntegerField(default=0)),
                ('we_won_count', models.IntegerField(default=0)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dibbs_award_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dibbs_award_import_batch',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='aw_import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='sales.awardimportbatch'),
        ),
    ]
