# Generated by Django 4.2.24 on 2026-03-23 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0019_award_import_batch_and_dibbs_award_file_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_message_id', models.CharField(help_text='The immutable Graph message ID from the mailbox.', max_length=512, unique=True)),
                ('sender_email', models.EmailField(help_text='Email address of the sender (supplier contact).', max_length=255)),
                ('sender_name', models.CharField(blank=True, default='', help_text='Display name of the sender as provided by Graph.', max_length=255)),
                ('subject', models.CharField(blank=True, default='', help_text='Email subject line.', max_length=998)),
                ('received_at', models.DateTimeField(help_text='Timestamp the message was received, from Graph metadata.')),
                ('body_html', models.TextField(blank=True, default='', help_text='Raw HTML body from Graph. Rendered only inside a sandboxed iframe with no-scripts policy. Never injected directly into the page DOM.')),
                ('is_read', models.BooleanField(default=False, help_text='Read status at time of last fetch. Not synced continuously.')),
                ('linked_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this message was first linked to an RFQ by a sales rep.')),
            ],
            options={
                'verbose_name': 'Inbox Message',
                'verbose_name_plural': 'Inbox Messages',
                'db_table': 'dibbs_inbox_message',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxMessageRFQLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional free-text note from the sales rep at link time.')),
                ('linked_by', models.ForeignKey(blank=True, help_text='The sales rep who created this link.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_links', to='sales.inboxmessage')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_links', to='sales.supplierrfq')),
            ],
            options={
                'verbose_name': 'Inbox Message RFQ Link',
                'verbose_name_plural': 'Inbox Message RFQ Links',
                'db_table': 'dibbs_inbox_message_rfq_link',
                'unique_together': {('message', 'rfq')},
            },
        ),
        migrations.RemoveField(
            model_name='companycage',
            name='imap_folder',
        ),
        migrations.RemoveField(
            model_name='companycage',
            name='imap_host',
        ),
        migrations.RemoveField(
            model_name='companycage',
            name='imap_last_fetched',
        ),
        migrations.RemoveField(
            model_name='companycage',
            name='imap_port',
        ),
        migrations.RemoveField(
            model_name='companycage',
            name='imap_user',
        ),
        migrations.DeleteModel(
            name='InboxEmail',
        ),
    ]
