# Generated by Django 4.2.24 on 2026-03-24 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0020_graph_inbox_and_remove_imap'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxmessage',
            name='claim_expires_at',
            field=models.DateTimeField(blank=True, help_text='Precomputed expiry timestamp (claimed_at + 20 minutes). Null means no active claim.', null=True),
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When the current claim was made. Claims expire after 20 minutes.', null=True),
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='The user who currently has this message open and is working it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_inbox_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
