# Generated by Django 4.2.24 on 2026-03-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_inboxmessage_claim_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('Matching', 'Matching'), ('RFQ_PENDING', 'RFQ Pending'), ('RFQ_SENT', 'RFQ Sent'), ('QUOTING', 'Quoting'), ('BID_READY', 'Bid Ready'), ('BID_SUBMITTED', 'Bid Submitted'), ('WON', 'Won'), ('LOST', 'Lost'), ('NO_BID', 'No Bid'), ('Archived', 'Archived')], default='New', max_length=20),
        ),
    ]
