# Generated by Django 4.2.24 on 2026-03-24 18:56

from django.db import migrations, models
from django.db.models import F


def backfill_aw_file_date(apps, schema_editor):
    DibbsAward = apps.get_model("sales", "DibbsAward")
    DibbsAward.objects.filter(source="DIBBS_FILE", aw_file_date__isnull=True).update(
        aw_file_date=F("award_date")
    )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_solicitation_status_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dibbsaward',
            name='aw_file_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date of the AW file that last wrote this record (from filename, e.g. aw260321.txt → 2026-03-21).', null=True),
        ),
        migrations.RunPython(backfill_aw_file_date, noop_reverse),
    ]
