# Generated by Django 4.2.24 on 2026-03-25 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_dibbsaward_aw_file_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dibbsaward',
            name='award_amount',
        ),
        migrations.RemoveField(
            model_name='dibbsaward',
            name='awardee_name',
        ),
        migrations.RemoveField(
            model_name='dibbsaward',
            name='sam_data',
        ),
        migrations.RemoveField(
            model_name='dibbsaward',
            name='we_bid',
        ),
    ]
