# Generated by Django 4.2.24 on 2026-03-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_remove_dibbsaward_award_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dibbsaward',
            name='synced_at',
        ),
    ]
