# Generated by Django 4.2.24 on 2026-03-26 18:46

from django.db import migrations, models
import django.db.models.deletion


def _drop_we_won_awards_view(apps, schema_editor):
    """
    SQLite emulates ALTER TABLE by rebuilding dibbs_award. A pre-existing
    dibbs_we_won_awards view that references dibbs_award makes that rebuild fail.
    Drop before any dibbs_award schema change; recreate after (see below).
    """
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS dibbs_we_won_awards")


def _recreate_we_won_awards_view(apps, schema_editor):
    """Match DIBBS_System_Spec.md / SQL Server view semantics for local SQLite."""
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE VIEW dibbs_we_won_awards AS
            SELECT da.id
            FROM dibbs_award da
            INNER JOIN dibbs_company_cage cc
                ON UPPER(da.awardee_cage) = UPPER(cc.cage_code)
            WHERE cc.is_active = 1
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_remove_dibbsaward_synced_at'),
    ]

    operations = [
        migrations.RunPython(_drop_we_won_awards_view, _recreate_we_won_awards_view),
        migrations.CreateModel(
            name='WeWonAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dibbs_we_won_awards',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='awardimportbatch',
            name='created_count',
        ),
        migrations.RemoveField(
            model_name='awardimportbatch',
            name='updated_count',
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='awards_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='faux_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='faux_upgraded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='mods_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='mods_skipped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='is_faux',
            field=models.BooleanField(default=False, help_text='True when this record was synthesized as a placeholder because a MOD arrived before the original award was imported. Set to False when the real award is subsequently imported.'),
        ),
        migrations.CreateModel(
            name='DibbsAwardMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_basic_number', models.CharField(max_length=50)),
                ('delivery_order_number', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_order_counter', models.CharField(blank=True, max_length=20, null=True)),
                ('nsn', models.CharField(blank=True, db_index=True, max_length=46, null=True)),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True)),
                ('awardee_cage', models.CharField(blank=True, db_index=True, max_length=10)),
                ('mod_date', models.DateField(db_index=True, help_text='last_mod_posting_date from the AW file row.')),
                ('mod_contract_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('purchase_request', models.CharField(blank=True, max_length=20, null=True)),
                ('dibbs_solicitation_number', models.CharField(blank=True, max_length=30, null=True)),
                ('sol_number', models.CharField(blank=True, default='', max_length=50)),
                ('aw_file_date', models.DateField(blank=True, db_index=True, null=True)),
                ('aw_import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mods', to='sales.awardimportbatch')),
                ('award', models.ForeignKey(help_text='The original award this MOD relates to. May be a faux placeholder.', on_delete=django.db.models.deletion.CASCADE, related_name='mods', to='sales.dibbsaward')),
            ],
            options={
                'db_table': 'dibbs_award_mod',
                'ordering': ['-mod_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='dibbsawardmod',
            constraint=models.UniqueConstraint(fields=('award', 'mod_date', 'nsn', 'mod_contract_price'), name='dibbs_award_mod_dedup'),
        ),
        migrations.RunPython(_recreate_we_won_awards_view, _drop_we_won_awards_view),
    ]
