# Generated by Django 4.2.24 on 2026-03-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_wewonaward_remove_awardimportbatch_created_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardimportbatch',
            name='expected_rows',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='last_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='scrape_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='scrape_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='awardimportbatch',
            name='source',
            field=models.CharField(choices=[('FILE_UPLOAD', 'Manual File Upload'), ('AUTO_SCRAPE', 'Automated Scraper')], default='FILE_UPLOAD', max_length=20),
        ),
    ]
