# Generated by Django 4.2.24 on 2026-03-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_awardimportbatch_scrape_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsnProcurementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(db_index=True, help_text='Normalized 13-digit NSN, no hyphens. e.g. 5935011299512', max_length=13)),
                ('fsc', models.CharField(db_index=True, help_text='First 4 chars of NSN — FSC code', max_length=4)),
                ('cage_code', models.CharField(max_length=5)),
                ('contract_number', models.CharField(max_length=25)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=5, max_digits=14)),
                ('award_date', models.DateField()),
                ('surplus_material', models.BooleanField(default=False)),
                ('first_seen_sol', models.CharField(blank=True, help_text='Solicitation number where this row was first extracted', max_length=13)),
                ('last_seen_sol', models.CharField(blank=True, help_text='Solicitation number where this row was most recently seen', max_length=13)),
                ('extracted_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NSN Procurement History',
                'verbose_name_plural': 'NSN Procurement History',
                'db_table': 'dibbs_nsn_procurement_history',
                'ordering': ['-award_date'],
                'unique_together': {('nsn', 'contract_number')},
            },
        ),
    ]
