# Generated by Django 4.2.24 on 2026-03-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_nsn_procurement_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardimportbatch',
            name='pages_scraped',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='awardimportbatch',
            name='scrape_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('MISSING', 'Missing')], max_length=20, null=True),
        ),
    ]
