# Generated by Django 4.2.24 on 2026-03-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_awardimportbatch_missing_pages_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='pdf_fetch_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='pdf_fetch_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('FETCHING', 'Fetching'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default=None, max_length=10, null=True),
        ),
    ]
