# Generated by Django 4.2.24 on 2026-03-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_solicitation_pdf_fetch_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitation',
            name='pdf_data_pulled',
            field=models.DateTimeField(blank=True, default=None, help_text="Set when procurement history data has been extracted from this sol's PDF, either via CA zip or individual fetch.", null=True),
        ),
    ]
