# Generated by Django 4.2.24 on 2026-03-30 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0031_solicitation_pdf_data_pulled'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitation_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('packaging_standard', models.CharField(blank=True, max_length=200)),
                ('preservation_requirements', models.TextField(blank=True)),
                ('marking_requirements', models.TextField(blank=True)),
                ('raw_section_d', models.TextField(blank=True, help_text='Raw extracted Section D text for reference')),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dibbs_sol_packaging',
            },
        ),
        migrations.AddField(
            model_name='solicitation',
            name='research_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='research_flagged_by',
            field=models.ForeignKey(blank=True, db_column='research_flagged_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_flagged_sols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='review_claim_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='review_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitation',
            name='review_claimed_by',
            field=models.ForeignKey(blank=True, db_column='review_claimed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sol_review_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='personalization_text',
            field=models.TextField(blank=True, default='', help_text='Optional personal note injected into the top of this supplier RFQ email'),
        ),
        migrations.AlterField(
            model_name='solicitation',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Active', 'Active'), ('RESEARCH', 'Research'), ('Matching', 'Matching'), ('RFQ_PENDING', 'RFQ Pending'), ('RFQ_SENT', 'RFQ Sent'), ('QUOTING', 'Quoting'), ('BID_READY', 'Bid Ready'), ('BID_SUBMITTED', 'Bid Submitted'), ('WON', 'Won'), ('LOST', 'Lost'), ('NO_BID', 'No Bid'), ('Archived', 'Archived')], default='New', max_length=20),
        ),
    ]
