# Generated by Django 4.2.24 on 2026-04-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_solpackaging_solicitation_research_flagged_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dibbsaward',
            index=models.Index(fields=['award_basic_number', 'delivery_order_number', 'nsn'], name='dibbs_award_dedup'),
        ),
        migrations.AddIndex(
            model_name='dibbsaward',
            index=models.Index(fields=['award_basic_number'], name='dibbs_award_basic_number'),
        ),
        migrations.AddIndex(
            model_name='dibbsaward',
            index=models.Index(fields=['delivery_order_number'], name='dibbs_award_delivery_order'),
        ),
    ]
