# Generated by Django 4.2.24 on 2026-04-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_dibbs_award_dedup_and_lookup_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermatch',
            name='match_method',
            field=models.CharField(choices=[('DIRECT_NSN', 'Direct NSN'), ('APPROVED_SOURCE', 'Approved Source'), ('FSC', 'FSC Category'), ('MANUAL', 'Manual / Ad-hoc')], max_length=20),
        ),
    ]
