# Generated by Django 4.2.24 on 2026-04-01 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0034_alter_suppliermatch_match_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DibbsAwardStagingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.UUIDField(db_index=True)),
                ('staged_at', models.DateTimeField()),
                ('raw_award_basic_number', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_nsn', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_delivery_order_number', models.CharField(blank=True, max_length=50, null=True)),
                ('error_reason', models.CharField(max_length=255)),
                ('errored_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_errors', to='sales.awardimportbatch')),
            ],
            options={
                'db_table': 'dibbs_award_staging_errors',
            },
        ),
        migrations.CreateModel(
            name='DibbsAwardStaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Isolates concurrent staging runs. One UUID per scrape/upload run.')),
                ('staged_at', models.DateTimeField(auto_now_add=True)),
                ('notice_id', models.CharField(max_length=66)),
                ('award_basic_number', models.CharField(max_length=50)),
                ('delivery_order_number', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_order_counter', models.CharField(blank=True, max_length=50, null=True)),
                ('last_mod_posting_date', models.CharField(blank=True, max_length=20, null=True)),
                ('awardee_cage', models.CharField(blank=True, max_length=10, null=True)),
                ('total_contract_price', models.CharField(blank=True, max_length=20, null=True)),
                ('award_date', models.CharField(blank=True, max_length=20, null=True)),
                ('posted_date', models.CharField(blank=True, max_length=20, null=True)),
                ('nsn', models.CharField(blank=True, max_length=50, null=True)),
                ('nomenclature', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_request', models.CharField(blank=True, max_length=50, null=True)),
                ('dibbs_solicitation_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aw_file_date', models.CharField(blank=True, max_length=20, null=True)),
                ('row_type', models.CharField(blank=True, max_length=5, null=True)),
                ('solicitation_id', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_rows', to='sales.awardimportbatch')),
            ],
            options={
                'db_table': 'dibbs_award_staging',
            },
        ),
    ]
