# Generated by Django 5.0.14 on 2026-04-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_dibbs_award_staging_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dibbsawardstaging',
            name='stage_id',
            field=models.CharField(db_index=True, help_text='Isolates concurrent staging runs. One UUID per scrape/upload run.', max_length=36),
        ),
        migrations.AlterField(
            model_name='dibbsawardstagingerror',
            name='stage_id',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
