# Generated by Django 5.0.14 on 2026-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0036_alter_dibbsawardstaging_stage_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SAMEntityCache",
            fields=[
                (
                    "cage_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "entity_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "website",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "physical_address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "physical_address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "physical_city",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "physical_state",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "physical_zip",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("mailing_address", models.TextField(blank=True, default="")),
                ("sba_flags", models.JSONField(blank=True, default=list)),
                ("naics_codes", models.JSONField(blank=True, default=list)),
                ("psc_codes", models.JSONField(blank=True, default=list)),
                ("raw_json", models.JSONField(blank=True, default=dict)),
                ("last_fetched", models.DateTimeField()),
                ("fetch_error", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "SAM Entity Cache",
                "db_table": "dibbs_sam_entity_cache",
            },
        ),
    ]
