# Generated by Django 5.0.14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0037_sam_entity_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="MassPassLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "filter_description",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable description of active filters at time of mass pass",
                    ),
                ),
                (
                    "sol_count",
                    models.IntegerField(
                        help_text="Number of solicitations affected",
                    ),
                ),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="List of {sol_id, prior_status} dicts captured before the update",
                    ),
                ),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mass_pass_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mass_pass_undos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dibbs_mass_pass_log",
                "ordering": ["-performed_at"],
            },
        ),
    ]
