# Generated by Django 5.0.14

import django.db.models.deletion
from django.db import migrations, models

def _drop_we_won_awards_view(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS dibbs_we_won_awards")


def _recreate_we_won_awards_view(apps, schema_editor):
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE VIEW dibbs_we_won_awards AS
            SELECT da.id
            FROM dibbs_award da
            INNER JOIN dibbs_company_cage cc
                ON UPPER(da.awardee_cage) = UPPER(cc.cage_code)
            WHERE cc.is_active = 1
            """
        )

class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0037_company_sharepoint_urls"),
        ("sales", "0038_masspasslog"),
    ]

    operations = [
        migrations.RunPython(_drop_we_won_awards_view, _recreate_we_won_awards_view),  # ADD
        migrations.AlterField(
            model_name="companycage",
            name="company_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Legacy display label; prefer linking contracts.Company via 'company'."
                ),
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="companycage",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Link this CAGE code to the corresponding company in the contracts system. "
                    "Required for automatic award queue injection."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cage_codes",
                to="contracts.company",
                verbose_name="Linked Company",
            ),
        ),
        migrations.RunPython(_recreate_we_won_awards_view, _drop_we_won_awards_view),  # ADD
    ]
