# Generated by Django 5.0.14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0037_company_sharepoint_urls"),
        ("sales", "0038_masspasslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companycage",
            name="company_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Legacy display label; prefer linking contracts.Company via 'company'."
                ),
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="companycage",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Link this CAGE code to the corresponding company in the contracts system. "
                    "Required for automatic award queue injection."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cage_codes",
                to="contracts.company",
                verbose_name="Linked Company",
            ),
        ),
    ]
