# Generated by Django 5.0.14 on 2026-04-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_suppliernsn_live_score_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitationMatchCount',
            fields=[
                ('solicitation', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='sales.solicitation')),
                ('match_count', models.IntegerField()),
            ],
            options={
                'db_table': 'dibbs_solicitation_match_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierNSNScored',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nsn', models.CharField(max_length=46)),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'dibbs_supplier_nsn_scored',
                'managed': False,
            },
        ),
    ]
