# Generated by Django 6.0.3 on 2026-04-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_solicitationmatchcount_suppliernsnscored'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_key', models.CharField(max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('dpas_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('issuing_office', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_email', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fat_required', models.BooleanField(blank=True, null=True)),
                ('fat_units', models.IntegerField(blank=True, null=True)),
                ('fat_days', models.IntegerField(blank=True, null=True)),
                ('fat_summary', models.TextField(blank=True, null=True)),
                ('itar_export_control', models.BooleanField(blank=True, null=True)),
                ('origin_inspection_required', models.BooleanField(blank=True, null=True)),
                ('iso_9001_required', models.BooleanField(blank=True, null=True)),
                ('buy_american_applies', models.BooleanField(blank=True, null=True)),
                ('additive_manufacturing_prohibited', models.BooleanField(blank=True, null=True)),
                ('cmmc_required', models.BooleanField(blank=True, null=True)),
                ('cmmc_level', models.IntegerField(blank=True, null=True)),
                ('quantity_ranges_encouraged', models.BooleanField(blank=True, null=True)),
                ('fob_point', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_destination', models.CharField(blank=True, max_length=200, null=True)),
                ('need_ship_date', models.DateField(blank=True, null=True)),
                ('required_delivery_date', models.DateField(blank=True, null=True)),
                ('packaging_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('preservation_method', models.CharField(blank=True, max_length=200, null=True)),
                ('special_packaging_instructions', models.TextField(blank=True, null=True)),
                ('marking_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('other_notable_requirements', models.TextField(blank=True, help_text='JSON array of strings stored as text', null=True)),
                ('solicitation', models.OneToOneField(db_column='solicitation_id', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='sales.solicitation')),
            ],
            options={
                'db_table': 'dibbs_sol_analysis',
            },
        ),
    ]
