# Generated by Django 6.0.3 on 2026-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_solanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='solanalysis',
            name='extraction_confidence',
            field=models.CharField(blank=True, help_text='HIGH / MEDIUM / LOW from LLM self-assessment', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='solanalysis',
            name='extraction_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
