# Generated by Django 4.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_solanalysis_extraction_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierrfq',
            name='last_send_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrfq',
            name='send_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplierrfq',
            name='status',
            field=models.CharField(
                choices=[
                    ('QUEUED', 'Queued'),
                    ('READY_TO_SEND', 'Ready to send'),
                    ('PENDING', 'Pending'),
                    ('SENT', 'Sent'),
                    ('RESPONDED', 'Responded'),
                    ('NO_RESPONSE', 'No Response'),
                    ('DECLINED', 'Declined'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
    ]
