# Generated by Django 6.0.3 on 2026-06-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_solicitation_match_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardimportbatch',
            name='source',
            field=models.CharField(choices=[('FILE_UPLOAD', 'Manual File Upload'), ('AUTO_SCRAPE', 'Automated Scraper'), ('hot_poll', 'Daytime we-won poll')], default='FILE_UPLOAD', max_length=20),
        ),
    ]
