# Generated by Django 6.0.3 on 2026-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_award_import_batch_hot_poll_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='DibbsNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('external_url', models.URLField(max_length=1000)),
                ('posted_date', models.DateField()),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DIBBS Notice',
                'verbose_name_plural': 'DIBBS Notices',
                'ordering': ['-posted_date'],
                'unique_together': {('title', 'posted_date')},
            },
        ),
    ]
