# Generated by Django 6.0.3 on 2026-06-29 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0088_contractlevelcharge_action_type'),
        ('sales', '0050_seed_check_dibbs_notices_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dibbsawardmod',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dibbsawardmod',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_dibbs_mods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dibbsawardmod',
            name='matched_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dibbs_mods', to='contracts.contract'),
        ),
    ]
