# Generated by Django 6.0.3 on 2026-07-09 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_backfill_dibbs_award_mod_matched_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorWatchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_watchlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_competitor_watchlist',
                'ordering': ['-added_at'],
            },
        ),
    ]
