# Generated by Django 6.0.3 on 2026-07-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_dibbs_award_competitor_stats_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAwardSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_supplier_cage', models.CharField(blank=True, default='', max_length=10)),
                ('contract_supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('packhouse_cage', models.CharField(blank=True, default='', max_length=10)),
                ('contract_packhouse_name', models.CharField(blank=True, default='', max_length=255)),
                ('idiq_supplier_cage', models.CharField(blank=True, default='', max_length=10)),
                ('idiq_supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('idiq_supplier_part_number', models.CharField(blank=True, default='', max_length=100)),
                ('page1_reference_cage', models.CharField(blank=True, default='', max_length=10)),
                ('resolved_supplier_cage', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('parse_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='', max_length=20)),
                ('parse_notes', models.TextField(blank=True, default='')),
                ('fetch_error', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_intel', to='sales.dibbsaward')),
            ],
            options={
                'db_table': 'sales_competitor_award_supplier',
                'ordering': ['-created_at'],
            },
        ),
    ]
