# Generated by Django 6.0.3 on 2026-07-10 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_seed_competitor_supplier_backfill_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorAwardEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10)),
                ('code_type', models.CharField(choices=[('CAGE', 'CAGE'), ('DODAAC', 'DoDAAC'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('role', models.CharField(choices=[('CONTRACTOR', 'Contractor'), ('OEM_DESIGN_AUTHORITY', 'OEM / Design Authority'), ('MANUFACTURER', 'Manufacturer'), ('BUYER', 'Buyer'), ('PAYMENT_OFFICE', 'Payment Office'), ('PACKAGING', 'Packaging'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_note', models.TextField(blank=True, default='')),
                ('extraction_method', models.CharField(choices=[('REGEX', 'Regex'), ('LLM', 'LLM')], default='REGEX', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='sales.dibbsaward')),
            ],
            options={
                'db_table': 'sales_competitor_award_entity',
                'ordering': ['role', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorAwardParseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='', max_length=20)),
                ('parse_notes', models.TextField(blank=True, default='')),
                ('fetch_error', models.BooleanField(default=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('award', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity_parse_status', to='sales.dibbsaward')),
            ],
            options={
                'db_table': 'sales_competitor_award_parse_status',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CompetitorAwardSupplier',
        ),
    ]
