# Generated by Django 6.0.3 on 2026-07-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0059_competitor_award_parse_status_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorawardparsestatus',
            name='resolved_pdf_url',
            field=models.CharField(blank=True, default='', help_text='Real dibbs2 Downloads/Awards PDF URL resolved from AwdRec.aspx. Cached so retries skip re-resolution.', max_length=500),
        ),
    ]
