# Generated by Django 6.0.3 on 2026-07-10 20:09

from django.db import migrations, models


def _drop_we_won_awards_view(apps, schema_editor):
    """
    SQLite emulates ALTER TABLE by rebuilding dibbs_award. A pre-existing
    dibbs_we_won_awards view that references dibbs_award makes that rebuild fail.
    Drop before any dibbs_award schema change; recreate after (see below).
    """
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS dibbs_we_won_awards")


def _recreate_we_won_awards_view(apps, schema_editor):
    """Match DIBBS_System_Spec.md / SQL Server view semantics for local SQLite."""
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE VIEW dibbs_we_won_awards AS
            SELECT da.id
            FROM dibbs_award da
            INNER JOIN dibbs_company_cage cc
                ON UPPER(da.awardee_cage) = UPPER(cc.cage_code)
            WHERE cc.is_active = 1
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_competitor_award_parse_status_resolved_pdf_url'),
    ]

    operations = [
        migrations.RunPython(_drop_we_won_awards_view, migrations.RunPython.noop),
        migrations.AddField(
            model_name='dibbsaward',
            name='pdf_url',
            field=models.CharField(blank=True, default='', help_text='Real dibbs2 Downloads/Awards PDF URL captured from the AwdRecs.aspx grid document-link anchor at scrape time (blank when absent).', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsawardstaging',
            name='pdf_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.RunPython(_recreate_we_won_awards_view, migrations.RunPython.noop),
    ]
