# Generated by Django 6.0.3 on 2026-07-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_competitor_award_parse_status_resolved_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='dibbsaward',
            name='pdf_url',
            field=models.CharField(blank=True, default='', help_text='Real dibbs2 Downloads/Awards PDF URL captured from the AwdRecs.aspx grid document-link anchor at scrape time (blank when absent).', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsawardstaging',
            name='pdf_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
