# Generated by Django 4.2.30 on 2026-07-17 15:29

from django.db import migrations, models


def _drop_we_won_awards_view(apps, schema_editor):
    """
    SQLite emulates ALTER TABLE by rebuilding dibbs_award. A pre-existing
    dibbs_we_won_awards view that references dibbs_award makes that rebuild fail.
    Drop before any dibbs_award schema change; recreate after (see below).
    """
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP VIEW IF EXISTS dibbs_we_won_awards")


def _recreate_we_won_awards_view(apps, schema_editor):
    """Match DIBBS_System_Spec.md / SQL Server view semantics for local SQLite."""
    if schema_editor.connection.vendor != "sqlite":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            CREATE VIEW dibbs_we_won_awards AS
            SELECT da.id
            FROM dibbs_award da
            INNER JOIN dibbs_company_cage cc
                ON UPPER(da.awardee_cage) = UPPER(cc.cage_code)
            WHERE cc.is_active = 1
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0061_dibbs_award_pdf_url'),
    ]

    operations = [
        migrations.RunPython(_drop_we_won_awards_view, migrations.RunPython.noop),
        migrations.AddField(
            model_name='dibbsaward',
            name='award_basic_number_url',
            field=models.CharField(blank=True, default='', help_text='The Award/Basic PDF document href (blank when absent).', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='award_basic_package_view_url',
            field=models.CharField(blank=True, default='', help_text='The Award/Basic Package View AwdRec.aspx href (blank when absent).', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='delivery_order_number_url',
            field=models.CharField(blank=True, default='', help_text='The Delivery Order PDF document href (blank when absent).', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsaward',
            name='delivery_order_package_view_url',
            field=models.CharField(blank=True, default='', help_text='The Delivery Order Package View AwdRec.aspx href (blank when absent).', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsawardstaging',
            name='award_basic_number_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsawardstaging',
            name='award_basic_package_view_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsawardstaging',
            name='delivery_order_number_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='dibbsawardstaging',
            name='delivery_order_package_view_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.RunPython(_recreate_we_won_awards_view, migrations.RunPython.noop),
    ]

