# Generated by Django 5.0.11 on 2025-03-28 12:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_paymenthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name_plural': 'Payment histories'},
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='created_on',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='clin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to='contracts.clin'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('item_value', 'Item Value'), ('quote_value', 'Quote Value'), ('contract_value', 'Contract Value'), ('wawf_payment', 'WAWF Payment'), ('plan_gross', 'Plan Gross'), ('statz_split_paid', 'STATZ Split Paid'), ('ppi_split_paid', 'PPI Split Paid'), ('special_payment_terms_interest', 'Special Payment Terms Interest')], max_length=50),
        ),
    ]
