# Generated by Django 5.0.11 on 2025-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_paymenthistory_created_by_paymenthistory_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment_type',
            field=models.CharField(choices=[('item_value', 'Item Value'), ('quote_value', 'Quote Value'), ('paid_amount', 'Paid Amount'), ('contract_value', 'Contract Value'), ('wawf_payment', 'WAWF Payment'), ('plan_gross', 'Plan Gross'), ('statz_split_paid', 'STATZ Split Paid'), ('ppi_split_paid', 'PPI Split Paid'), ('special_payment_terms_interest', 'Special Payment Terms Interest')], max_length=50),
        ),
    ]
