# Generated by Django 5.0.11 on 2025-03-28 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_alter_paymenthistory_payment_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acknowledgementletter',
            options={'ordering': ['-modified_on'], 'verbose_name': 'Acknowledgement Letter', 'verbose_name_plural': 'Acknowledgement Letters'},
        ),
        migrations.RemoveField(
            model_name='acknowledgementletter',
            name='statz_contact_title',
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='addr_fname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='addr_lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='contract_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledgement_letters_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='dpas_priority',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='fat_plt_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='letter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledgement_letters_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='po',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='po_ext',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='salutation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='st_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='statz_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='statz_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='supplier_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
