# Generated by Django 5.0.11 on 2025-03-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_alter_acknowledgementletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgementletter',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('', 'None')], max_length=10, null=True),
        ),
    ]
