# Generated by Django 5.0.11 on 2025-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0016_acknowledgementletter_statz_contact_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='solicitation_type',
            field=models.CharField(blank=True, default='SDVOSB', max_length=10, null=True),
        ),
    ]
