# Generated by Django 4.2.25 on 2025-12-03 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Nsn',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                        ('modified_on', models.DateTimeField(auto_now=True)),
                        ('nsn_code', models.CharField(blank=True, max_length=20, null=True)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('part_number', models.CharField(blank=True, max_length=25, null=True)),
                        ('revision', models.CharField(blank=True, max_length=25, null=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('directory_url', models.CharField(blank=True, max_length=200, null=True)),
                        ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                        ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'contracts_nsn',
                    },
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='SupplierNSNCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('price_reference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nsn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.nsn')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'db_table': 'supplier_nsn_capability',
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='nsn',
                    name='suppliers',
                    field=models.ManyToManyField(related_name='capable_nsns', through='products.SupplierNSNCapability', to='suppliers.supplier'),
                ),
            ],
            database_operations=[],
        ),
    ]
