# Generated by Django 6.0.3 on 2026-04-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsn',
            name='packaging_notes',
            field=models.TextField(blank=True, default='', help_text='Hazmat, crating, ORM-D, or other special handling notes.'),
        ),
        migrations.AddField(
            model_name='nsn',
            name='unit_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit height in inches.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='nsn',
            name='unit_length',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit length in inches.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='nsn',
            name='unit_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Unit weight in pounds.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nsn',
            name='unit_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Unit width in inches.', max_digits=8, null=True),
        ),
    ]
