# Generated by Django 6.0.3 on 2026-07-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_nsn_packout_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsn',
            name='nsn_normalized',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                editable=False,
                max_length=13,
            ),
        ),
    ]
