# Generated by Django 6.0.3 on 2026-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_backfill_nsn_normalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsn',
            name='dimension_source_notes',
            field=models.TextField(blank=True, default='', help_text="Where the weight/dimension figures came from, e.g. 'vendor spec sheet' or 'estimated from prior drawing'. Written by the quote app's freight sub-modal."),
        ),
        migrations.AddField(
            model_name='nsn',
            name='dimensions_last_verified',
            field=models.DateField(blank=True, help_text='Date the weight/dimensions were last confirmed against a real source. Stale dims produce bad freight adders.', null=True),
        ),
    ]
